[package]
name = "graduate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

license = "GPL-3.0"
repository = "https://github.com/Amazingkenneth/graduate"

[dependencies]
serde = { version = "1", features = ["derive"] }
toml = "0"
rodio = "0"
iced = { version = "0", features = ["image", "svg", "tokio"] }
iced_native = { version = "0" }
reqwest = "0"
tokio = { version = "1", features = ["full"] }
directories = "4"
rand = "0"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0", features = ["winuser"] }

[profile.release-opt]
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true  # Automatically strip symbols from the binary.

[package.metadata.deb]
assets = [
    ["target/release-opt/graduate", "usr/bin/graduate", "755"],
    ["graduate.desktop", "usr/share/applications/", "644"],
]