[package]
name = "graduate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

license = "GPL-3.0"
repository = "https://github.com/Amazingkenneth/graduate"

[dependencies]
toml = "0"
rodio = "0"
iced = { version = "0", features = ["image", "canvas", "svg", "tokio"] }
iced_native = { version = "0" }
reqwest = "0"
tokio = { version = "1", features = ["full"] }
directories = "4"


[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"