[package]
name = "graduate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

license = "GPL-3.0"
repository = "https://github.com/Amazingkenneth/graduate"

[dependencies]
csv = "1"
iced = "0"
