name_en = "Clarissa"
nickname = [
    "敖丙",
    "敖子",
    "只因",
]
relationship = [
    { with = 20, is = "亲爱的金主爸爸" },
    { with = 21, is = "“好弟弟”" },
]
plots = [
    "中午关怀",
]
[[comment]]
from = 5
date = 2022-12-03
description = """敖丙！！！你真的又高又瘦（没错像个竹竿子），还是个发量王者！！！所以这就是营养全都用在了该用的地方吗？
你真的是个尽职且乐于助人的数学课代hhh，对你每天“按时”收作业感激不尽么么么么（别让婷婷知道）
还有灰常开心和你住同同一个小区一栋楼哦，这一定是缘分。而且天湖居真是。。。景色宜人呢。也不知道以后能不能经常碰到，我可以悄悄爬去你们家吗（bushi）。但悄咪咪地说，我还是有一点点孩怕你的mom熊老师的呢。。。
算啦，最后只能含泪祝你保持你的好身材（哼），还有数学一直都那么好。"""
[[comment]]
from = 20
date = 2022-12-04
description = """敖丙你的性格真的很好！和你相处非常十分特别的愉快，完全不会有尴尬还有争吵。每次出去玩首选肯定有你！希望可以和你一直做好朋友！虽然真的很笨蛋，但是我超喜欢你哦！！拜托别再焦虑了，我长成你这样我做梦都得笑醒！！让我杜比8D立体环绕式的说：你超赞的好吧！！！！！！"""
[[comment]]
from = 21
date = 2022-12-11
description = """
    问：你见过会动的蘑古力吗？ 答：见过～ 
    把你比喻成蘑古力你应该没有意见吧（犯贱）注意看这个手长脚长的女孩，似乎刚和自己的身体认识，跑起步来就跟别说了（来自比你矮的人的倔强）身高这个硬伤恐怕你体会不了咯～刚来到1班，在这人生地不熟的原始森林中，认识了刚成为数学课代表的你。你恪尽职守，你看大家作业还未交齐时会延缓时间，同时你也会因为“娇羞”而不敢催作业（？
    随着初三学习任务的增加，你也时常通宵（dddd），所以每天课间必做主线任务之一便是补觉啦。希望只因同学你能重（bu）视（yao）睡（cu）眠（si）！还有还有，it is important for you to have breakfast！！在未来这短短的200+天，我们一起携手并进，向着心仪的学校冲冲冲！！！"""