name_en = "Clarissa"
nickname = ["只因", "敖丙", "敖子"]
plots = ["中午关怀"]
relationship = [
    { by = 2, is = "儿子" },
    { by = 20, is = "孙子" },
    { by = 21, is = "儿子" },
    { by = 29, is = "好盆友" },
    { by = 32, is = "朋友" },
]
reviews = [
    """你可真是个可爱的姑娘，初见时就对你印象颇深，更难忘的是你在开学初，班干部竞选时的演讲。透过你坚毅的目光，能感受到你内心对成功的渴望。你是个理性的人，知道自己真正想要的是什么，而不会被虚名所累。这一学期对于你来说并不是特别顺利，我见过你为学业而流的泪水，但更见过你灿烂的笑脸和在舞台上的风采。人生就是如此，五味杂陈才是真实的，不过也要劝你一句，要知道“不时不食”的道理，青春的花正在开放，现在真的要努力汲取营养，他日才能结出硕果。我相信你的实力，学习上的优势会更显露于有物理的初二和有化学的初三。加油敖丙，很高兴认识你！""",

    """你开朗、阳光，每天都能看到你美丽的笑脸；你人缘很好，课间休息时，你总是会与一群小姐妹嬉笑，叽叽喳喳。，肉眼可见的青春美好；你机灵、聪明，稍稍努力，就将成绩提潜力的女孩儿。但有一句话要悄悄和你讲，努力是根基，坚持是枝干，颜值只是开在枝叶顶端的花，不要本末倒置哈。发扬优点，你就会更讨人喜欢。""",

    """你热情大方，体贴同学，是个古灵精怪又温婉可亲的人，当你阻止整蛊万老师的同学们时，那一身正气让人肃然起敬，体现出你尊师重道和心有分寸的可贵品质；你在模型制作大赛中积极参与，专心致志粘贴零件的模样依旧历历在目；你和同学也可以和睦相处，心怀班级荣誉；你善良又暖心，与朋友打趣时幽默诙谐，在同学患病时为其购买食物，凡此种种，使你如冬日暖阳一般闪闪发光，照耀他人。
课堂上，你专心听讲，将笔记整理得井井有条，同时深知温故知新的道理，时常抽出学案，循着自己精致的笔记温习，细心的人都能看出你的努力。但是也许初中的压力有些大，也许你还没能找到真正适合自己的学习方法，目前还未发挥出自己的真实潜能。衷心希望你在接下来的学习过程中，状态一天比一天好，取得应有的佳绩！""",

    """战胜自我是一件快乐的事情。你战胜了自己的学业心魔，坚持勇敢地向各科发起冲击，勇敢地披荆斩棘，勇敢地一路向前，甚至勇敢地跻身年级中上游。因为你下决心向自己挑战，所以在这个学年，你当之无愧地成为进步最大的孩子。真为你高兴！""",

    """小茵子非常可爱，尽管目前还稍微落后一点点，但你从来都没有放弃自己的追求，一如既往地在拼搏，在努力。在学习方法上，你有了些许改进，有的科目的学习上，也已经见到起色。好样的！只要坚持勤向老师请教，多与同学交流，你的进步会更大的！记住：假期中不能玩太多手机哦！""",
]
[[comment]]
date = 2022-12-03
description = """敖丙！！！你真的又高又瘦（没错像个竹竿子），还是个发量王者！！！所以这就是营养全都用在了该用的地方吗？
你真的是个尽职且乐于助人的数学课代hhh，对你每天“按时”收作业感激不尽么么么么（别让婷婷知道）
还有灰常开心和你住同同一个小区一栋楼哦，这一定是缘分。而且天湖居真是。。。景色宜人呢。也不知道以后能不能经常碰到，我可以悄悄爬去你们家吗（bushi）。但悄咪咪地说，我还是有一点点孩怕你的mom熊老师的呢。。。
算啦，最后只能含泪祝你保持你的好身材（哼），还有数学一直都那么好。"""
from = 5
[[comment]]
date = 2022-12-04
description = """敖丙你的性格真的很好！和你相处非常十分特别的愉快，完全不会有尴尬还有争吵。每次出去玩首选肯定有你！希望可以和你一直做好朋友！虽然真的很笨蛋，但是我超喜欢你哦！！拜托别再焦虑了，我长成你这样我做梦都得笑醒！！让我杜比8D立体环绕式的说：你超赞的好吧！！！！！！"""
from = 20
[[comment]]
date = 2022-12-11
description = """
    问：你见过会动的蘑古力吗？ 答：见过～ 
    把你比喻成蘑古力你应该没有意见吧（犯贱）注意看这个手长脚长的女孩，似乎刚和自己的身体认识，跑起步来就跟别说了（来自比你矮的人的倔强）身高这个硬伤恐怕你体会不了咯～刚来到1班，在这人生地不熟的原始森林中，认识了刚成为数学课代表的你。你恪尽职守，你看大家作业还未交齐时会延缓时间，同时你也会因为“娇羞”而不敢催作业（？
    随着初三学习任务的增加，你也时常通宵（dddd），所以每天课间必做主线任务之一便是补觉啦。希望只因同学你能重（bu）视（yao）睡（cu）眠（si）！还有还有，it is important for you to have breakfast！！在未来这短短的200+天，我们一起携手并进，向着心仪的学校冲冲冲！！！"""
from = 21
[anecdote]
embarrassment = "不小心把一个我没看过的链接发到了有老师的班群qwq"
interests = "扒舞、追综艺（名学yyds！）、追电视剧、逛b站、逛街、当韭菜"
want = "去湖南和上海旅游，努力考上理想的高中qwq，去见想见的人"
[[article]]
content = "敖丙课前演讲"
date = 2021-03-03
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247485951&idx=1&sn=c4e2dcb4a7598b1c29607aae6bcc46dc"
[[article]]
content = "我以妙笔绘青春——第一届手绘杂志原创大赛"
date = 2021-03-04
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247487140&idx=1&sn=defc6000c7392dfb65d5a4afd7285bf5"
[[article]]
content = "敖丙生日快乐！！（原谅为师接连两次忘了爱徒生日）祝你早日找到自己的节奏，展现真正的实力！"
date = 2021-06-25
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247489612&idx=1&sn=3adc0963c1e4ab60d91dcb8f24c595fc"
