name_en = "Bonnie"
nickname = [
    "bobo",
    "李王爱",
    "李王八",
    "皮皮",
]
relationship = [
    { with = 29, is = "n年老友" },
    { with = 5, is = "好friend" },
    { with = 23, is = "好盆友" },
]
plots = [
    "赶最后的早餐",
    "叼包子进教室",
    "上课发困",
    "与阿姨去厕所，靠在墙上边睡边等",
    "周测艺术性留白",
    "宿舍开小灯补作业，仔细辨别宿管脚步，斗智斗勇",
]
[[comment]]
from = 21
date = 2022-12-05
description = """“猪八戒照镜子——李瑷不是人”（有点合理但不多）哎呀真的是，随手一翻，怎么那么多你的表情包啊。不过这也挺好，以后翻回来回忆也能涌现出来。小学六年再加初中三年同学情，我们这（父与子）关系不必多赘述了吧。言归正传，你开朗阳光☀️的性格深深吸引了我。跟你聊天不需要注重用词啥的，你那小脑瓜里也兜着奇奇怪怪的东西，和你在一起整个人都轻松了许多。哦对了，上课一定要好好上哦（刚去上厕所了≠刚从床上爬起来）最后，接下来的日子我们携起手来一起奋斗好吗？（穿着蛇皮演出服神龙摆尾的下场～）"""
[[comment]]
from = 28
date = 2022-12-07
description = """李瑷作为一般的乐观小天使，不管遇到什么困难，她总是可以用笑声解决一切，乐观是他最强大的武器。她十分努力，做任何事情都是这样，上课、睡觉、以及上课睡觉。李瑷性格开朗，十分讨人喜欢，你不管对他有什么要求，只要他能满足，他基本都会满足你。不知道为什么，她在初三对酸角糕，尤其钟爱每天都有三角糕，据她所言，她的脚都有酸角糕的味道了，虽然酸角糕真的很好吃。李瑷就像一个小天使一样，在他身边你永远不会担心自己会伤心，因为她的笑声真的很魔性。她的身边绝对会跟着罗心懿，不管是去厕所，还是去厕所。希望李瑷继续加油，波波加油，波波加油(ง•̀_•́)ง。"""
[[comment]]
from = 29
date = 2022-12-07
description = """李瑷：是初中三年一直带给我们欢乐的人，不经意间流露出的幽默和吐槽自己遇到的那些倒霉的事总能让我们笑到肚子痛。不算是一个出众的美女但是凭着自己的人格魅力交到了许多好朋友。每天也很认真地写课程表，默默的为班级付出。学习十分认真遇到不会的就主动找老师、同学提问，这是我认为我只得向她学习的地方。当然，她的性格开朗，会积极参加班级的活动而且能够做得很好。掌握着各种八卦的班级开心果谁能不爱呢？"""