name_en = "Bonnie"
nickname = ["bobo", "李王八", "李王爱", "皮皮"]
plots = [
    "上课发困",
    "与阿姨去厕所，靠在墙上边睡边等",
    "叼包子进教室",
    "周测艺术性留白",
    "宿舍开小灯补作业，仔细辨别宿管脚步，斗智斗勇",
    "赶最后的早餐",
]
relationship = [
    { by = 19, is = "好朋友" },
    { by = 23, is = "舔狗" },
    { by = 29, is = "n年老友" },
    { by = 33, is = "死忠粉" },
    { by = 5, is = "dear舍友" },
]
reviews = [
    """世界上的可爱有千万种，唯有你最与众不同。记得初见你时，你那一头蓬松的头发莫名地让人想起，初春枝头绽放的杨花，可可爱爱。一开始以为你会是文文静静的一只，没想到运动会上你竟然可以动如脱兔，女子4x100米接力赛上，你已经跑过弯道，被你带过来的风才刚刚掀起我的衣角，刷新了我对你的定义和印象；而且而且，在开放日和元旦汇演的排练中，又让我看到了更不一样的你：有点搞笑，又有点励志。李瑷呀，在排练过程中，我们经历了数次大改，多少辛酸只有我们自己知道。但是凭着心中一句“一班不能输”的信念，我们最终赢得了胜利的辉煌。活动如此，学习和人生亦复如是，相信你懂我的意思，看好你呦！""",

    """“小李瑷，真可爱”无意间看到你的小学毕业相册，记住了这句话。这出自你的老同学之手，还真是贴切呢。你性格开朗，风趣幽默，在班里人缘相当不错，只要有你在，大家都不用害怕没有话题去聊。作为班级的学习委员，你每周都会统计每一个迟交、缺交作业同学的名单和次数。这一学期对于你而言并不轻松，通过你日益憔悴的脸庞，我也感受到了你承受的巨大压力。我其实在尽我所能为你减压，但没有谁能护你一世周全，未来还是要靠自己的。小李瑷，加油吧。""",

    """你性格开朗，率真大方，在很多时候都可以看到你的优秀：运动场上，你身姿矫健，在跑道上一马当先冲在前；在元旦晚会上，你和各位同学在舞台上自信舒展地展示着自己的风采，让我们见识到了你优美的另一面，作为我们班一位负责的学习委员，每天，你都会拿着本子不厌其烦地登记作业并抄写课表……你的一举一动都让我们看到了你的活泼开朗、认真负责。衷心希望你在课上更加认真，在学习上取得更多的成就和进步。""",

    """你是一个聪明的孩子，生活中你能与大家和睦相处，平时能按时完成老师布置的作业，但学习上钻研不深，遇到疑难有畏难情绪，知难而退，学过的知识，也不太能灵活运用，正因如此，成绩还有提升空间。希望你在学习上能锲而不舍地努力进取，争取下学期有更新的进步。""",

    """小李瑷在许多方面的表现都是非常优秀的，特别是善于进行自我剖析，会及时发现自身的不足，并努力去改正。你也非常珍惜同学之间的友情，所以能够热心去帮助同学。你知道自己的弱项，所以你肯下功夫去弥补缺漏之处，每个午休，都会看到你悄悄回到课室，向我请教问题，有时还真性情地端着鸡柳或者骨肉相连回来继续品味，挺好挺好。这三年转眼就要结束了，剩下的一学期要继续加油哦！""",
]
[[comment]]
date = 2022-12-05
description = """“猪八戒照镜子——李瑷不是人”（有点合理但不多）哎呀真的是，随手一翻，怎么那么多你的表情包啊。不过这也挺好，以后翻回来回忆也能涌现出来。小学六年再加初中三年同学情，我们这（父与子）关系不必多赘述了吧。言归正传，你开朗阳光的性格深深吸引了我。跟你聊天不需要注重用词啥的，你那小脑瓜里也兜着奇奇怪怪的东西，和你在一起整个人都轻松了许多。哦对了，上课一定要好好上哦（刚去上厕所了≠刚从床上爬起来）最后，接下来的日子我们携起手来一起奋斗好吗？（穿着蛇皮演出服神龙摆尾的下场～）"""
from = 21
[[comment]]
date = 2022-12-07
description = """李瑷作为一般的乐观小天使，不管遇到什么困难，她总是可以用笑声解决一切，乐观是他最强大的武器。她十分努力，做任何事情都是这样，上课、睡觉、以及上课睡觉。李瑷性格开朗，十分讨人喜欢，你不管对他有什么要求，只要他能满足，他基本都会满足你。不知道为什么，她在初三对酸角糕，尤其钟爱每天都有三角糕，据她所言，她的脚都有酸角糕的味道了，虽然酸角糕真的很好吃。李瑷就像一个小天使一样，在他身边你永远不会担心自己会伤心，因为她的笑声真的很魔性。她的身边绝对会跟着罗心懿，不管是去厕所，还是去厕所。希望李瑷继续加油，波波加油，波波加油！"""
from = 28
[[comment]]
date = 2022-12-07
description = """李瑷：是初中三年一直带给我们欢乐的人，不经意间流露出的幽默和吐槽自己遇到的那些倒霉的事总能让我们笑到肚子痛。不算是一个出众的美女但是凭着自己的人格魅力交到了许多好朋友。每天也很认真地写课程表，默默的为班级付出。学习十分认真遇到不会的就主动找老师、同学提问，这是我认为我只得向她学习的地方。当然，她的性格开朗，会积极参加班级的活动而且能够做得很好。掌握着各种八卦的班级开心果谁能不爱呢？"""
from = 29
[anecdote]
embarrassment = "周测侧头睡觉流口水被看到，喜欢一个某班男的被全班知道"
interests = "做食物，画画，击剑，音乐，追番，韩漫，网络爽文，娇妻文学，猫猫狗狗"
want = "摆小吃摊，去泰国吃小吃，去日本上学，去韩国买周边，住在夜市"
[[article]]
content = "听李瑷谈公平"
date = 2021-06-11
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247489575&idx=1&sn=0b13552f0d082d2ac15abd92ecef5eb4"
[[article]]
content = "我以妙笔绘青春——第一届手绘杂志原创大赛"
date = 2021-03-04
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247487140&idx=1&sn=defc6000c7392dfb65d5a4afd7285bf5"
[[article]]
content = "记忆中的年味 - by bobo"
date = 2021-03-28
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247488283&idx=1&sn=84b0dc7879238bd4d9c5523eecc7fb78"
