name_en = "Sunny"
nickname = ["HR", "林主持", "泓睿", "消防栓"]
plots = ["元旦晚会朗诵", "开放日主持"]
relationship = [
    { by = 15, is = "知己" },
    { by = 16, is = "猪队友" },
    { by = 18, is = "孙子" },
    { by = 20, is = "儿子的初恋" },
    { by = 7, is = "玩笑箱" },
]
reviews = [
    """该用哪个词语来总结，我们之间这学期的故事呢？
欲扬先抑。
还记得一开始我是因为什么约见你的家长吗？竟然是因为你的小调皮，现在想想多么不可思议。你其实应该是一个有点腼腆，甚至讲话都会语带娇羞的男孩。这个学期，你不断以行动和实力给我一个又一个惊喜，我没想到看起来讲话都略显木讷的你，在开放日上做起英文主持人会那么帅气；没想到看起来有点天然呆的你，朗诵起苏东坡的《江城子·密州出猎》来会那么铿锵有力，；没想到看起来慵懒淡然的你，在绿茵场上也能凭实力在积分榜上闯出自己的一片天地；没想到看起来有点小迷糊的你，在长隆可以带为师寻找正确的方向，帮我缩短徘徊的距离……这学期你给了我太多没想到了，但定格在心里的，还是运动会结束，撤离大本营的时候，你跑过来救我的那一幕。林主持，很高兴认识你，下学期，我们精彩继续！""",

    """林主持一向以乐天知命、单纯可爱著称，这学期又很欣喜地发现你是如此孝顺。在开学之前的“还绿大夫山”志愿活动中，你亲手采摘的草莓一定要留给妈妈尝一尝，哪怕自己粗枝大叶笨手笨脚，完全不善于保存这种可爱的浆果。
作为班级的学习委员，你总是能够以身作则，每一周的作业内容你都会记录得清清楚楚。课间休息时，你青春灵动的身影纵身一跃，就会成为鹤立鸡群的制高点，真的很帅气呢！你多才多艺，团建的课本剧表演，你惟妙惟肖的演技也着实让人难忘。这学期在学习方面整体趋势也是渐渐趋于向上，但是也要记住“政入万山围子里，一山放出一山拦”放眼长远，才能履险如夷。加油哈我的林主持！""",

    """你有着极高的身材，每次排队你都站在队伍的最后，像夸父一般顶天立地，又有着夸父般强健的肌肉，超强的弹跳力使跳高跳远在你面前都是小菜一碟，操场上的你在沙坑边惊鸿一跃，面对全场的欢声雷动，你也镇定自如，似乎刚刚无事发生
你又对物理有极大的兴趣和极高的天赋，每天放学，同学们总是一哄而散，而你毅然放弃了干饭的宝贵时间，将智慧的头脑深深埋在物理电学仪器中，来回推导着那令人摸不着头脑的电路，调试着各种电子元件，整个人沉浸在物理学的宇宙中，内心富足，而在我们这些旁观者看来，是难得的天真和单纯。
这样的你真好，不疾不徐，不争不抢，就这样静静地守护着内心的安宁吧，少年。""",

    """天然呆的你虽然外表不苟言笑，但拥有火热的心肠。你个性独特，稳重中更透着一股韧劲。这学期，由于做题速度问题，老师没少跟你交流，有着上进心的你面对老师的建议总能虚心接受。一段时间的努力过后，你写字的速度慢慢提高了，作业也能按时完成了，成绩也是稳中有升。林主持，老师真为你的进步感到高兴。
""",

    """林主持这个学期一直把学习摆在第一位，不轻易放过每一节宝贵的上课时间，为同学们做出了表率。对待各门功课，你多了细心，多了认真，更是将本学期的“进步人物”收入囊中，实在是实至名归。在课余生活中，你也不是个呆头读书的人，而且你真是长大了，对人对事都有自己的见解，和你聊天，每每都能让我对你眼前一亮。暗探“孩子成熟了”。假期就要来临了，弯道超车的机会来了，不能做使自己前功尽弃的事情哦！""",
]
[[comment]]
date = 2022-12-03
description = """你是一位十分优秀的主持，记得七年级的时候，你在一节语文课上给全班朗诵了苏轼的《江城子·密州出猎》，你雄厚有力的声音给我留下了深刻的印象。在体育方面，你也十分优秀，你十分擅长跳远，每次你跳远时，都能引来全班人的围观。学习上，你十分认真，下课时，也经常找老师讨论问题，很高兴认识你，希望你的成绩能越来越好！"""
from = 30
[[comment]]
date = 2022-12-03
description = """林泓睿，是一个卷王。他和周诺一样卷；每次上英语课都卷。他有一台无人机，也精通拍摄，他跳远跳高很强，随便一跳就得满分。
每次我看到他努力学习时，我是快乐的。他的努力必能有所成就。他很喜欢飞机，他梦想是当飞行员。飞翔在蓝天中，这是人类自古以来的梦想。天空象征自由。他自由的梦想是会实现的。"""
from = 25
[[comment]]
date = 2022-12-05
description = """“是你是老师，还是我是老师啊？！”此话一出，我脑中第一浮现出的必是林泓睿啦。这个玉树临风仪表堂堂的男孩子因为口齿伶俐被称为主持。主持主持，难免会成为被爱丽点名模仿文章人物的同学之一。我无意间发现你在视频号里发了许多实验视频，不得不赞叹你的知识领域好广哦。因为有着逆天的身高所以经常看见你下课在教室里比赛跳高，不过还是得注意安全哦。希望你还能再创佳绩——耶！中考加油！！很高兴遇见你～"""
from = 21
[anecdote]
embarrassment = "拍vlog"
interests = "打球、飞行、航拍"
want = "考上理想的学校"
[[article]]
content = "林主持说世界获得满堂彩"
date = 2021-03-19
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247487389&idx=1&sn=08a9909965b9ccc105c4c70c24e57b78"
[[article]]
content = "林主持说世界——节约粮食，从我做起"
date = 2021-06-17
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247489576&idx=1&sn=1e4210c4004cbfc99f54fecd669580a4"
[[article]]
content = "值日班长林泓睿的述职报告"
date = 2021-12-08
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247490996&idx=1&sn=c1e27ce43a9b0a989fd94c0e5e00fa85"
[[article]]
content = "我以妙笔绘青春——第一届手绘杂志原创大赛"
date = 2021-03-04
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247487140&idx=1&sn=defc6000c7392dfb65d5a4afd7285bf5"
[[article]]
content = "林主持生日快乐！春华秋实 夏风冬雪 四季喜乐 感恩有你"
date = 2021-10-14
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247490649&idx=1&sn=e92361c72b8a2cad214342fc84865517"
[[article]]
content = "千日圆满 感动初三"
date = 2023-04-29
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247491100&idx=1&sn=3e48217a9493b07c1218c250cc000cfb"
[[article]]
content = "《一史》首发大作"
date = 2021-07-12
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247490369&idx=1&sn=7841598c75bc5737fadfb4bb7221c339"
[[article]]
content = "那天真遗憾"
date = 2021-05-07
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247489107&idx=1&sn=723a395d933e8557de47d82ca479b497"
