nickname = [
    "林主持",
    "泓睿",
]
relationship = [
    { with = 15, is = "老铁、飞友" },
    { with = 18, is = "基友" },
    { with = 34, is = "朋友" },
    { with = 7, is = "合作伙伴1" },
    { with = 16, is = "合作伙伴2" },
    { with = 25, is = "跑友" },
    { with = 9, is = "车友" },
]
plots = [
    "元旦晚会朗诵",
    "开放日主持",
]
[[comment]]
from = 30
date = 2022-12-03
description = """你是一位十分优秀的主持，记得七年级的时候，你在一节语文课上给全班朗诵了苏轼的《江城子·密州出猎》，你雄厚有力的声音给我留下了深刻的印象。在体育方面，你也十分优秀，你十分擅长跳远，每次你跳远时，都能引来全班人的围观。学习上，你十分认真，下课时，也经常找老师讨论问题，很高兴认识你，希望你的成绩能越来越好！"""
[[comment]]
from = 25
date = 2022-12-03
description = """林泓睿，是一个卷王。他和周诺一样卷；每次上英语课都卷。他有一台无人机，也精通拍摄，他跳远跳高很强，随便一跳就得满分。
每次我看到他努力学习时，我是快乐的。他的努力必能有所成就。他很喜欢飞机，他梦想是当飞行员。飞翔在蓝天中，这是人类自古以来的梦想。天空象征自由。他自由的梦想是会实现的。"""
[[comment]]
from = 21
date = 2022-12-05
description = """“是你是老师，还是我是老师啊？！”此话一出，我脑中第一浮现出的必是林泓睿啦。这个玉树临风仪表堂堂的男孩子因为口齿伶俐被称为主持。主持主持，难免会成为被爱丽点名模仿文章人物的同学之一。我无意间发现你在视频号里发了许多实验视频，不得不赞叹你的知识领域好广哦。因为有着逆天的身高所以经常看见你下课在教室里比赛跳高，不过还是得注意安全哦。希望你还能再创佳绩耶✌️！中考加油！！很高兴遇见你～"""