name_en = "Angelina"
nickname = [
    "阿陆",
    "花花",
]
plots = [
    "体育课跑步（烦），但又不敢摸鱼，怕完蛋",
    "晚饭后去校外玩",
]
introduction = """   英校初中这几年真的是一段令人难忘的回忆。
    我每天早上都要好早起床，一般都是班上前五名到达教室的人哈哈哈。森妈每天都第一个到教室开门，接着到教室的就是老鼠和龟龟和火山。这时候教室很安静就很适合补作业or预习，或者借鉴对方数学压轴题的答案(?
    接着去饭堂的路上就会遇到很多陆陆续续到校的同学。在饭堂里我经常会待比较久，因为可以等到别的同学一起来吃饭。回教室的途中总是会迎面遇到姗姗来迟的满满和她的妹妹(于是我们每次都完美错开吃饭时间。
    回到教室第一时间就是问问同学早上有没有语文小测，有的话就得赶在爱丽进教室前瞟几眼背诵资料，永远猜不到哪次小测要交上去，哪次要自行批改，所以都要好好写。接下来的五节课总是一眨眼就过去了，很幸运能遇到一群很好的老师，每节课都能学到很多，课堂氛围也因为一群爱问问题男生而变得活跃。
    午饭时间很快就到了，对干饭充满热情的同学们一秒都不耽搁拉上朋友立刻赶往饭堂，英校的伙食是很不错的了，有时候吃得很饱才回家。
    睡了一个短暂的午觉就要赶回学校了。下午的两节外教课是每一天最轻松的时间，但是一转眼就过去了。
    再过两节课就是晚饭时间，几乎每次晚饭都是和papa姐姐一起去吃的啦，每次都会有很多好玩的东西聊，吃完晚饭就会去升旗的草坪上看晚霞。
    晚自习是一段漫长的学习时间，也是这一天在学校的最后一件事，熬过晚自习就能回家睡觉了。虽然我每一天晚自习都会拼命写作业但还是有写不完的时候，因为有时候作业很难，所以晚自习以后还要带回家做。
    时光在不经意中流逝，翻开旧日的笔记，字里行间充满着情深意境的交错。仿佛回到了那曾经经历过的风风雨雨，坎坎坷坷中去，旧时的回忆依旧，只是少了几分忧郁，多了几分繁华。"""