introduction = """   英校初中这几年真的是一段令人难忘的回忆。
    我每天早上都要好早起床，一般都是班上前五名到达教室的人哈哈哈。森妈每天都第一个到教室开门，接着到教室的就是老鼠和龟龟和火山。这时候教室很安静就很适合补作业or预习，或者借鉴对方数学压轴题的答案(?
    接着去饭堂的路上就会遇到很多陆陆续续到校的同学。在饭堂里我经常会待比较久，因为可以等到别的同学一起来吃饭。回教室的途中总是会迎面遇到姗姗来迟的满满和她的妹妹(于是我们每次都完美错开吃饭时间。
    回到教室第一时间就是问问同学早上有没有语文小测，有的话就得赶在爱丽进教室前瞟几眼背诵资料，永远猜不到哪次小测要交上去，哪次要自行批改，所以都要好好写。接下来的五节课总是一眨眼就过去了，很幸运能遇到一群很好的老师，每节课都能学到很多，课堂氛围也因为一群爱问问题男生而变得活跃。
    午饭时间很快就到了，对干饭充满热情的同学们一秒都不耽搁拉上朋友立刻赶往饭堂，英校的伙食是很不错的了，有时候吃得很饱才回家。
    睡了一个短暂的午觉就要赶回学校了。下午的两节外教课是每一天最轻松的时间，但是一转眼就过去了。
    再过两节课就是晚饭时间，几乎每次晚饭都是和papa姐姐一起去吃的啦，每次都会有很多好玩的东西聊，吃完晚饭就会去升旗的草坪上看晚霞。
    晚自习是一段漫长的学习时间，也是这一天在学校的最后一件事，熬过晚自习就能回家睡觉了。虽然我每一天晚自习都会拼命写作业但还是有写不完的时候，因为有时候作业很难，所以晚自习以后还要带回家做。
    时光在不经意中流逝，翻开旧日的笔记，字里行间充满着情深意境的交错。仿佛回到了那曾经经历过的风风雨雨，坎坎坷坷中去，旧时的回忆依旧，只是少了几分忧郁，多了几分繁华。"""
name_en = "Angelina"
nickname = ["花花", "阿陆"]
plots = ["体育课跑步（烦），但又不敢摸鱼，怕完蛋", "晚饭后去校外玩"]
reviews = [
    """阿陆啊阿陆，古灵精怪的你是班里第一个和我在微信上坦诚相见的，那时你就成功引起了我的注意。本来我已经做好了战斗准备（你懂的），但后来越来越觉得，这不是个小对手，而是老师的好帮手，同学们学习的好榜样。开学之初的班干部竞选，你准备充分，U盘一插，实力直接呈现在屏幕上，碾压了一众对手；整个学期，你承包了课室墙报、运动会班牌和模型制作大赛展板等多项工程，质与量皆为上乘。艺术上的贡献不只这些，学术上的成就又让我们欣羡不已，粤港澳大湾区国际青少年写作创优奖，让年过半百的何校也激动不已，亲自上台为你颁奖。运动会上你留下了美丽的身影，开放日和元旦汇演时你的举手投足，又是那样的翩若惊鸿。
文能提笔安天下，舞能上场定乾坤，啊，爱了爱了！""",

    """你有极高的绘画天分，几次墙报都做的有声有色，尤其这学期的建党百年专题墙报，更是夺得了全校第一名的好成绩，真是了不起；你的作文写的相当不错，这一点在6月月考的作文答题卡上已经尽数体现了；你心思细密，别人不经意间的一颦一笑都会被你看在眼里，再适时用画笔描摹出来，比如墙报上的朕和阿怪；你还生性幽默，开学初去大夫山进行志愿活动的间隙，还不忘和为师打赌捞鱼……
略略一想，你的优点就已经不胜枚举，这一年匆匆而过，还没有来得及细细品味，好在赛程还未过半，我们还有两年可以创造回忆，希望你可以一直这样开心快乐，笑嘻嘻！
""",

    """你是我们班的宣传委员，作为宣传委员，这学期你为班级付出了许多：做板报期间，你放弃了午休的时间，为我们的板报竭尽全力；制作班牌的时候，你还利用在家的休息时间构思制作；绘制班旗的时候，你更是多方协调，最终为我们拿出了最佳方案。
你在为班级做贡献的同时，学习成绩还十分优异，尤其是英语一骑绝尘，你的作文尤其突出，每次都能拿到一个非常好的分数，你的英语演出能力也非常强，凭借着一己之力，将drama全组引领到了一个非常高的高度，带领全组拿下了全班最高分。总之一句话，对于你的优秀，我们已经习惯了。""",

    """看到墙报里张贴的“鲜衣怒马，不负韶华”几个大字，我就想起了你和你带领的宣传小队。你们积极上网，查询相关知识广做宣传；你们收集素材，尽力让墙报或班牌引人注目。在你的努力下，大伙的心里深深刻入了合作二字，队员们都行动起来，跟随着你的步伐，让团队更优秀。谢谢你，我们的宣传小能手。""",
]
[anecdote]
embarrassment = "进了男厕还没发现自己走错了"
interests = "画画、看电影、学语言、跳舞、弹琴"
want = "去好莱坞看奥斯卡影帝"
[[article]]
content = "值日班长陆英卉的述职报告"
date = 2021-12-25
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247491005&idx=1&sn=8bc07b390bfbfe9cfbc8b24afe821598"
[[article]]
content = "我以妙笔绘青春——第一届手绘杂志原创大赛"
date = 2021-03-04
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247487140&idx=1&sn=defc6000c7392dfb65d5a4afd7285bf5"
[[article]]
content = "阿陆生日快乐，祝你沉静执着，一直遇到懂你的人"
date = 2021-03-05
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247487141&idx=1&sn=5be067e93426e338d4c9ae33540d7a3b"
