name_en = "Jerry"
nickname = ["xyz", "吉吉king", "国王", "吉吉", "夏钰吉", "猴子"]
relationship = [
    { by = 18, is = "孙子" },
    { by = 25, is = "朋友" },
    { by = 7, is = "伙伴" },
]
reviews = [
    """哈！吉吉国王！一想起你，总会先记起你在那节语文课前的演讲。短短的3分57秒，让我认识了一个新的吉吉。记得刚刚见面的时候，一个唇红齿白的小少年坐在台下，端端正正，目光纯净。谁能想到这样一个标准的小乖乖，刚刚十几岁的小孩，对社会现象、对家庭教育会有如此之深的独到见解。你聪明、活泼，作为英语课代表，总是尽职尽责，这也让任人不明的为师十分羡慕英语老师。你又有点青春的羞涩腼腆，因为还记得那节主题班会上，你在讲台上拜为师所赐的尴尬瞬间。这学期你也全程积极参与着班级的各项活动，从校园模型的制作，到开放日和元旦汇演的排练和表演，都有你的付出，班级的荣誉离不开你的默默付出。因为快乐，这学期时光过得匆匆，下学期你又会给我们带来怎样的精彩呢？好期待！""",

    """语文课前的三分钟演讲，让大家对你刮目相看，你的演说潇洒动人，落落大方，而又独辟蹊径。上学期你成为了大家的英语课代表，便一直尽职尽责，这学期大家又发现你不仅有着老干部一般的严肃，更有着非同一般的搞笑细胞，亦正亦邪，常常让大家捧腹。
你的成绩很稳定，英语更是厉害，对人对事也都有很独到的见解，大家对你都很满意，继续保持就好哈。""",

    """啊，吉吉国王，你语文课前的三分钟演讲，你的演讲潇洒动人，落落大方而又独辟蹊径，让大家对你刮目相看，；你不仅是我们尽职尽责的英语课代表，还是一个精力旺盛的中学生，每次体育课跑步时，你永远冲在最前头。你还致力于为班级荣誉默默付出，无论是开放日还是元旦晚会的彩排中，都有你的参与；你性格温顺，脾气好，每次同学之间发生冲突，你都会上去劝架，即使被误伤，你仍然会用自己的笑容来扑灭同学们心中的怒火……与你相处真快乐，大家相互竞争，共同进步，期待下个学期更优秀的你。""",

    """篮球运动的确很有魅力，它的对抗，它的拼抢，它的战术，一个接一个的投篮令人着迷。你有这方面的天赋，所以，篮球场上的你是那么引人注目。其实在学习这个赛场上，也一样需要拼抢和战术，而且学习赛场上的对手更多，想在学习的战场上赢得喝彩吗？国王，要更加努力了!""",

    """自从做了班级的“善财童子”以后，你似乎在各个方面都有了更大的动力，所以你显得特别刻苦，善于抓紧时间去复习各门功课，勤于向老师请教疑难，乐于与同学研究不解。清晰地记得，几乎每个午休，你都会第一批跑回课室向我请教问题，有时甚至嘴里还塞着午餐。你的付出，自然就有了回报——成绩的进步。坚持自己的好的做法，中考一定有收获！加油！""",
]
[[comment]]
date = 2022-12-03
description = """你是一个阳光的大男孩，体育场上经常有你跃动着的身影，谈起篮球明星那根是如数家珍。知识面也很广，可以说是上知天文下知地理，学习成绩也不错，可以说是德智体美劳全面发展了，在高中，你一定会更加如鱼得水，加油吧。"""
from = 32
[[comment]]
date = 2022-12-04
description = """你为人乐观，热爱生活，开心快乐。每天放学在篮球场上都能看到你矫健的身影。你尊敬老师关心同学，热爱班级，科代表工作认真负责，学习上一丝不苟。你内心善良、天真无邪。在困难面前你也曾迷惘徘徊，甚至丧失了信心和方向，但我知道你没有屈服，你有一颗顽强上进的心，不会轻易放弃。你品行优良，待人诚恳，表里一致。宽厚仁道，不激进，不与人争锋，同学乐意亲近。你最突出的成果是学习逐步走向正轨，逐渐掌握了高中课程的学习方法。记得那次上数学课，老师出了一道关于边角关系的题目，一分钟未到，你便果断地举起了手，上讲台去，拿起粉笔刷刷点点，那些我们还尚未看懂的sin、cos、tan等函数就已解决了那道题。你现在一定要树立信心，没有翻不过的高山，没有越不过的大海，只要胸怀坚定，坚强果敢，乘风破浪会有时！"""
from = 11
[[comment]]
date = 2022-12-05
description = """夏钰喆，是我们班的篮球巨星。猴子捞月一个勾手直接进球。而且他很硬，根本顶不动。他投篮还贼准，盖都难盖。他跳绳也很行，双飞特别强，一分钟230个。他也是我们班的好人，十分热心肠，而且是个好朋友。他可是数学强者，在积分榜上是第二。他是大胃王，吃的是正常人的两倍，而且每次都坚持光盘行动，食堂里能做到这样的人少之又少。总而言之，能和他做朋友是让人愉快的。"""
from = 14
[[comment]]
date = 2022-12-06
description = """热爱打篮球，最喜欢的NBA球队是76ers。打篮球可以从一号位达到五号位，非常全能，做他的队友可以放心的把球传到他手上。为人和善，乐于帮助同学。不怎么打游戏（除了2K）。学习认真努力，有很多good ideas，学习成绩优异。"""
from = 18
[anecdote]
embarrassment = "空位三分三不沾"
interests = "打篮球"
want = "三分命中率100%"
[[article]]
content = "周末辅导——吉吉国王有话说"
date = 2021-03-24
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247488215&idx=1&sn=86335320610f2b54a0f62c37ef299a9a"
[[article]]
content = "值日班长夏钰喆的述职报告"
date = 2021-12-21
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247491003&idx=1&sn=c0558ee68b12a54a115b658d194017a1"
[[article]]
content = "我以妙笔绘青春——第一届手绘杂志原创大赛"
date = 2021-03-04
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247487140&idx=1&sn=defc6000c7392dfb65d5a4afd7285bf5"
[[article]]
content = "国王生日快乐，愿你永葆初心，一生相信圣诞童话"
date = 2021-03-07
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247487142&idx=1&sn=410858d1331c9feddf42b31e5555ce5d"
[[article]]
content = "千日圆满 感动初三"
date = 2023-04-29
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247491100&idx=1&sn=3e48217a9493b07c1218c250cc000cfb"
