name_en = "Eric"
nickname = ["又高又帅", "小垃圾箱", "峰哥", "怪"]
relationship = [
    { by = 34, is = "儿子" },
    { by = 35, is = "儿子" },
    { by = 6, is = "儿子" },
    { by = 7, is = "忠臣" },
]
reviews = [
    """阿怪你好呀！这学期我们过得不算和平哦。体育素质训练比赛上，你就凭着那忘乎所以的潇洒一抛，成功引起了我的注意，后来你的一系列操作，又让我觉得应该多给你一些关怀，所以我给你机会领略了中华汉字之美，给你机会体验了清洁工人打理下水道的辛劳，也给你机会在晚修时观察教师办公室墙壁的纹理……几番交流下来，我渐渐发现你其实不是个顽劣的学生，在足球赛上，看你尽情奔跑的样子，我知道那时的你是真的快乐；在一次早读时，我说你的发型好像被炸弹炸过一样，看你眼中闪现出的娇羞，我知道你内心其实很柔软；开放日和元旦汇演时，看花枪在你手中恣意翻飞，我知道你其实很多时候可以做到认真和坚毅。
阿怪呀阿怪，不必急着长大，现在的每一天都写满了青春的美好，我也愿意等你慢慢长大。很高兴能认识你！""",

    """你是一个异常聪颖机敏的男生，一脸机灵。想你天赋异禀，每次看前桌的你，都是游游逛逛，但是偏偏成绩却轻轻松松就名列前茅；你很有运动天赋，课间与同学玩闹的惊鸿一跃就有几米远；你长相也不错，各科老师都公认你是班里的颜值担当……但是你身上也存在着一些小毛病，虽然人不轻狂枉少年，但也愿你严于律己，放大自己的优点，删除自己的缺点。""",

    """当一个头发蓬乱，不修边幅，站没站样且“武功高强”的人站在大家面前的时候，背景音效却庄严肃穆地给了一段“这是学霸”的解说，想必任谁都会觉得无厘头吧。在相处了一年多以后，你还真的就一直这么无厘头着，首尾呼应，前后照应。
同学们评价你，看着精瘦“甚至能看见他手上突出的血管”，可是课间打闹却一点不处下风；你目光纯粹，每当找你来核实是不是又惹了什么祸，你总是点头承认，眼里放射的目光中，意志是如此的坚定；你是公认的“又高又帅”，当为师老不正经地找你聊隔壁班女生对你的青睐，意外地却看到了你脸上的娇羞，啧啧啧，真有意思。
率性帅行，同学们眼中的你会真诚赞美他人的优点，即使ta并不是特别优秀，这也是你难能可贵之处——虽然顽皮但是坦荡，仍有少年纯真的心。很喜欢这样的你（如果少惹点祸就更喜欢了）。""",

    """想到你，脑海中即刻就浮现你清俊的浅浅的笑，你的真诚，你的善良，加上你的勤奋和聪颖，让你的学习和生活如此快乐和充实，硕果累累。你的机智，如果能再加上一点沉稳，就更能让我们每个人感到踏实，充满信心。相信在今后的学习中，你会表现得更出色，成为当之无愧的又高又帅！""",

    """你实在是乐观向上，每个课间都能看到你矫健的身姿；你乐于积极地与老师沟通，待人接物成熟而自信；你在竞技体育方面颇有天赋，将本学期的“运动人物”先进人物提名收入囊中，更不必说，你的颜值也是顶格配置，是班级的颜值担当……算下来，你真是很优秀，但人无完人，对于你，如果想要成为完人，该苦练收纳技能了。""",
]
[[comment]]
date = 2022-12-03
description = """Some of us get dipped in flat, some in satin, some in gloss; but every once in a while, you find someone who's iridescent, and once you do, nothing will ever compare.
《Flipped》从来没见过你这么完美的人哦，不想夸你了怕你骄傲。祝你头发一直都那么多，越来越优秀，我们有缘再见吧，俊希~"""
from = 5
[[comment]]
date = 2022-12-03
description = """刘俊希，又高又帅，性格豪爽。他体育十分强，是国家二级运动员，游泳拿过许多奖项，而且跑步足球篮球都在行，他是我们班唯一一个能扣篮的人，他是计分表上的常客，有扣分也有加分。
事件：上英语网课时，一不小心打开麦克风，“世界杯”这个关键词被老师听到。在车上上网课时睡着，被老师以为旷课。
他和谁都合得来，他有很广的人脉。他虽然看上去像个调皮捣蛋的孩子，但他其实学习很认真。我不知道他的梦想，但目前看来，他的前途一片光明。"""
from = 25
[[comment]]
date = 2022-12-05
description = """好一个凡尔赛老祖！真是低调做人高调做事啊！体育场上，你健步如飞，大放异彩，是我们班的骄傲。一副矫健的身躯，让你把无数金牌纳入囊中，拿到手软。聪慧的思维，让你的破题、解题无懈可击。无论是体育还是学习，你都有远超常人的潜力与能力。即使你藏得再深，也不能掩盖你的光芒。"""
from = 16
[anecdote]
embarrassment = "网课开麦"
interests = "踢球、打球、打游戏"
want = "和狗子踢球"
[[article]]
content = "我以妙笔绘青春——第一届手绘杂志原创大赛"
date = 2021-03-04
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247487140&idx=1&sn=defc6000c7392dfb65d5a4afd7285bf5"
[[article]]
content = "硬币怪生日快乐！班主任这老东西后知后觉，又给忘了。名副其实 又高又帅 四季予你 静待花开。"
date = 2021-12-03
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247490993&idx=1&sn=90e9b15bbf424a9d6a2fcb08fef64515"
[[article]]
content = "千日圆满 感动初三"
date = 2023-04-29
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247491100&idx=1&sn=3e48217a9493b07c1218c250cc000cfb"
