name_en = "Nok"
nickname = ["周校", "脑壳", "诺哥", "锌"]
relationship = [{ by = 11, is = "老铁、飞友" }]
reviews = [
    """一个课间，我在办公桌上发现了几包小点心，还以为是哪位同事又来派零食了，却没想到是个田螺公子送给我的暖心下午茶；一个晚修，我在讲台上埋头批改作业，不经意间抬头一瞥，看到一个专注于完成作业的小可爱在自己的世界里很神气地调兵遣将，丝毫没有注意到对面那个偷拍的人已经将镜头对准他圆圆的脸；一个晚上，我在微信上收到几张照片，还以为是哪个学生有事找我，却没想到，是有人将我的微信头像做成了徽章戴在胸前……哎，糯米粥，你真的给了我太多的暖心瞬间，我曾经是做了什么惊天动地的好事，才让我此生有幸遇见了你呢？更因为看过你婴儿时期的可爱，所以我坚信如果真的有天使，那一定是你的样子。因为有你，我每天上班都觉得更有趣。周诺，很高兴认识你！""",

    """你为人很随和，优哉游哉的样子，整天笑呵呵；你很细心，朋友有难你都会给予帮助；你很会做手工，朋友圈里你制作的足球台灯实在精美，竟然有一丝宜家的北欧风；你细心体贴，积极向上，虽然成绩小有波动，但你坚毅的目光，让人觉得真的看到了未来的希望；你又活力四射，难忘课间休息时，你闪转腾挪的身影……你的优点不胜枚举，因为有你，我们都感到很轻松、很自在、很开心，遇到你、有你在，就会很安心。""",

    """诺哥，到现在我一想起你，脑海中浮现的都还是你小时候刚刚长出几颗小牙，带着绒线帽子傻乎乎笑嘻嘻的样子，啊呀也太可爱了！
现在的你样子基本没变，但是各项技能渐渐被点亮了：从纸艺台灯、到木工书签、再到模型制作大赛过程中的各种，你的手工技艺已经日臻成熟；从去年的绿萝到今年的蝴蝶兰，你的园艺技能也已经被点亮；每个课间，无论是通过监控还是亲眼看你充满活力的英姿，都能明白你的运动技能也已经被点亮；七年级的公众号文章和今年的课余文言文培优，都显示你的文艺技能也被点亮……
诺哥越来越优秀了，真喜欢你呀！""",

    """你见到老师总是礼貌相待，平时能做好老师的小助手，每天还能和同学们一起讨论功课。你忠厚、老实，更能和同学友好相处，你气量大，但上课偶尔会开小差，这点以后要改进哟，学习成绩还有一定的提升空间。周校，真心希望你争取更大的进步，再接再厉，乘胜前进！""",

    """虽然已经是初三的学生了，可你还是那个视频里笑哈哈，长着刚刚长出小牙的可爱的小婴儿，依然保持了那种天真、诚实与纯朴，被抓包依然会窘迫，被问到还是会羞涩，好可爱啊！这是非常难得的，应该继续保持。在日常的合作学习中，你又是非常主动与积极的。诺哥慢慢长大了，我们也快要说再见了，这一千多天回头想想真是很短暂，有太多很好的回忆呢，真心希望我诺哥万事顺遂，事事平安。""",
]
[[comment]]
date = 2022-12-03
description = """第一印象就是一个很文静的男孩，长得高大，但却十分心灵手巧。记得八年级的时候，你用单词卡做出了一个个精致的，长得像足球的灯。在学习上，你很刻苦认真，经常看到你拿着提分宝典在那里背。当我在写这个评价时，也能看到你奋笔疾书的背影。很高兴认识你，希望你的成绩能越来越好！"""
from = 30
[[comment]]
date = 2022-12-03
description = """周诺者，卷也。一名未成年男性，相貌帅气，情商颇高。其在刚初一时，不及吾高，但到初三时，已高吾一头。其善于学习，勤于背诵，勤于温故。
事件：每当吾与其去上英语课时，其必带资料于室中。每每老师视线不在其上，其必拿资料默背。因其努力，其成绩增长飞速。
其好无人机，有无人机一架，其摄影与剪辑造诣颇深，曾在B站上发视频，可惜能者无人赏，其B站名为“天空奇遇Nok”。
其在未来，欲从事无人机，做无人机拍摄。若其努力如现今之努力，其必能实现梦想。"""
from = 25
[[comment]]
date = 2022-12-04
description = """你活泼可爱，与你相识多年，我能感觉到，你的童年是最充满欢乐的。遇到不顺心的事，你不会大发雷霆，火冒三丈，而是沉静下来，最终解决问题。你热爱生活，热爱大自然之美。是的，你爱好摄影，一台单反，一台无人机，就是你业余生活的主角，因为你相信，生活中的美好，值得被记录。在你的引导下，我也逐渐与你拥有了同样的爱好。虽然我技术与经验可能没有你精湛、丰富，但志同道合必将成为知音。我庆幸自己在初中的这三年交到了一个真正趣味相投的朋友。希望我们能成为一辈子的老铁。"""
from = 11
[anecdote]
embarrassment = "化学题7错5"
interests = "航拍"
want = "考上六中，买微单"
[[article]]
content = "诺哥的空间思维"
date = 2021-03-25
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247488216&idx=1&sn=619b3a05932b946bb9aaec1702136ae9"
[[article]]
content = "值日班长周诺的述职报告"
date = 2021-12-07
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247490995&idx=1&sn=6f21e4d98fc0ecfe666821c974874ea6"
[[article]]
content = "我以妙笔绘青春——第一届手绘杂志原创大赛"
date = 2021-03-04
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247487140&idx=1&sn=defc6000c7392dfb65d5a4afd7285bf5"
[[article]]
content = "千日圆满 感动初三"
date = 2023-04-29
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247491100&idx=1&sn=3e48217a9493b07c1218c250cc000cfb"
[[article]]
content = "破 浪"
date = 2021-04-23
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247489104&idx=1&sn=1246c17acf776ff1059d2f40e7ec0f14"
