name_en = "Nok"
nickname = ["诺哥", "周校", "脑壳"]
relationship = [
    { with = 22, is = "朋友" },
    { with = 11, is = "知己" },
    { with = 25, is = "好友" },
]
[[comment]]
from = 30
date = 2022-12-03
description = """第一印象就是一个很文静的男孩，长得高大，但却十分心灵手巧。记得八年级的时候，你用单词卡做出了一个个精致的，长得像足球的灯。在学习上，你很刻苦认真，经常看到你拿着提分宝典在那里背。当我在写这个评价时，也能看到你奋笔疾书的背影。很高兴认识你，希望你的成绩能越来越好！"""
[[comment]]
from = 25
date = 2022-12-03
description = """周诺者，卷也。一名未成年男性，相貌帅气，情商颇高。其在刚初一时，不及吾高，但到初三时，已高吾一头。其善于学习，勤于背诵，勤于温故。
事件：每当吾与其去上英语课时，其必带资料于室中。每每老师视线不在其上，其必拿资料默背。因其努力，其成绩增长飞速。
其好无人机，有无人机一架，其摄影与剪辑造诣颇深，曾在B站上发视频，可惜能者无人赏，其B站名为“天空奇遇Nok”。
其在未来，欲从事无人机，做无人机拍摄。若其努力如现今之努力，其必能实现梦想。"""
[[comment]]
from = 11
date = 2022-12-04
description = """你活泼可爱，与你相识多年，我能感觉到，你的童年是最充满欢乐的。遇到不顺心的事，你不会大发雷霆，火冒三丈，而是沉静下来，最终解决问题。你热爱生活，热爱大自然之美。是的，你爱好摄影，一台单反，一台无人机，就是你业余生活的主角，因为你相信，生活中的美好，值得被记录。在你的引导下，我也逐渐与你拥有了同样的爱好。虽然我技术与经验可能没有你精湛、丰富，但志同道合必将成为知音。我庆幸自己在初中的这三年交到了一个真正趣味相投的朋友。希望我们能成为一辈子的老铁。"""
