name_en = "Jacky"
nickname = ["ou", "男神", "杰哥"]
relationship = [
    { with = 11, is = "猪队友" },
    { with = 7, is = "手机智慧助手" },
    { with = 31, is = "语法修正器" },
]
[[comment]]
from = 25
date = 2022-12-03
description = """欧嘉杰，是我们班的电教员，会很多关于电脑的知识。他学习很努力、很认真。他会打羽毛球，他在班里没什么特殊事件，但这并不意味着他没有贡献，老师电脑卡住、死机，都是他出面解决。如果没有他，很多的问题都无法解决。"""
[[comment]]
from = 21
date = 2022-12-05
description = """“诶这个电脑怎么回事？”每当老师们发出类似的问题，你便会第一时间冲上讲台，也因此喜获“电教员”“男神”的称号。下课时其他同学在嬉笑打闹，和正在埋头学习的男神形成鲜明的对比。有次下课我困的不行了倒头便睡，醒来时发现你怎么还在做题啊顿时自愧不如（听说你会熬夜哦，要早睡千万不要生病了！）除了好学，你也超级幽默。“（前桌周报掉地上了）诶这是谁的周报啊？怎么还有深深的烙印呀？（翻找）啊这不会是我的吧！（*惊恐 接着翻找）啊原来不是我的吓我一跳。”怎么说，小学时根本没发现你那么有趣。初中生活马上要结束了，很高兴成为你的同学并和你一起拼搏💪！"""
[[comment]]
from = 31
date = 2022-12-06
description = """一个很专心的人，对待一些他人不以为意的细节也会很认真。学习很好，也有很多才艺。祝你能得到自己所追求的东西。"""
