name_en = "Jacky"
nickname = ["ou", "杰哥", "男神"]
relationship = [{ by = 11, is = "合作伙伴" }, { by = 7, is = "兄弟" }]
reviews = [
    """时至今日，每天复习几遍你弹奏钢琴的视频仍是我必修的作业，看着视频里的你，从小小一只，手刚刚碰得到琴键，到后来渐渐长大，十指翻飞之间，流淌出的乐曲也慢慢变得刚毅起来，我在屏幕另一端好像看着自己的孩子慢慢长大一样，竟然也很欣慰，很有老母亲的自豪感。
一次开放日节目排练，你随手就将背景音乐的旋律弹了出来，于是赢得了“男神”之名，随着活动的不断开展，你男神的地位更是日渐稳固，就像视频传达的成长毕竟只是隔岸观火，真正让我惊诧的是校园模型制作大赛，赛程最后你展现出来的拼劲让我肃然起敬，原来男神不是一只小可爱，而是有杀气的中学生，失敬失敬。我的男神不仅有才华、很沉稳，更懂得时间规划，当班里同学吵成一片的时候，你总能在闹中取静，仿佛一位大隐隐于市的高人。成绩最然小有波动，但总体稳定，我相信你的成绩会更好。加油哦，有缘顶峰见！""",

    """我的男神思想独立又客观公正，对班级里的事件都会有自己的看法；我的男神心思细密，在家长开放日的前夕，你恨不得擦净剔除黑板里的每一粒尘埃；我的男神极其自律，时间观念极强，每次都能在午休或体锻时间，看见你错峰用餐，挤时间学习；我的男神是一个尽职尽责的电教员，几乎每天早晨都会赶在上课前，帮同学们打开课室的电脑，而晚修结束后，又是最后一批离开的人。我的男神的优秀大家都看在眼里，但有时候你也有一些小迷糊，比如作业的上交就不够自觉，如果可以再精致些，你就是你就不只是为师的男神，而是所有人的男神。""",

    """男神琴技高超，精通数理化，上课时正襟危坐，认真听课，内容再难理解，也依然挡不住你对知识的热情和渴望，上课时会把握机会，积极发言，维持纪律。
模型大赛期间，你从家里拿来慢慢一箱热熔胶棒，无私贡献自己的力量，义无反顾地担当起应尽的责任，全身心的投入，不言代价与回报，最终也如愿带领大家获得了模型制作大赛的一等奖。
只是男神纵然已经封神，但也还有需要加强的地方， 小脾气收敛一些、处事再大气一些，你会更受欢迎的哦！""",

    """你刚毅、机智，富有才气；你刻苦、勤奋、富有进取心。不论在哪个方面，你都具有巨大的潜能。现在你已经在许多方面崭露头角：电脑方面的才华令大伙心悦诚服，钢琴艺术的才华更令人赞叹不已……才华需要展现，更需要沉淀，小男神，希望你更加沉稳！""",

    """这是最后一次写评语给你了，看着你从刚刚入读时小小一只，穿着一袭红裙在舞台上擂鼓，到现在英气逼人目光笃定，让为师不得不暗叹时光匆匆，韶华易逝。我的男神有很强的自学能力和自我管理能力，无论在专业还是文化课学习上，主动性极强，经常在课件看到你飞奔找各科老师讨教问题的身影，听闻你已经自学完成了多门高年级课程，进步显著。你的适应能力很强，也希望最后一程，不负众望。""",
]
[[comment]]
date = 2022-12-03
description = """欧嘉杰，是我们班的电教员，会很多关于电脑的知识。他学习很努力、很认真。他会打羽毛球，他在班里没什么特殊事件，但这并不意味着他没有贡献，老师电脑卡住、死机，都是他出面解决。如果没有他，很多的问题都无法解决。"""
from = 25
[[comment]]
date = 2022-12-05
description = """“诶这个电脑怎么回事？”每当老师们发出类似的问题，你便会第一时间冲上讲台，也因此喜获“电教员”“男神”的称号。下课时其他同学在嬉笑打闹，和正在埋头学习的男神形成鲜明的对比。有次下课我困的不行了倒头便睡，醒来时发现你怎么还在做题啊顿时自愧不如（听说你会熬夜哦，要早睡千万不要生病了！）除了好学，你也超级幽默。“（前桌周报掉地上了）诶这是谁的周报啊？怎么还有深深的烙印呀？（翻找）啊这不会是我的吧！（*惊恐 接着翻找）啊原来不是我的吓我一跳。”怎么说，小学时根本没发现你那么有趣。初中生活马上要结束了，很高兴成为你的同学并和你一起拼搏！"""
from = 21
[[comment]]
date = 2022-12-06
description = """一个很专心的人，对待一些他人不以为意的细节也会很认真。学习很好，也有很多才艺。祝你能得到自己所追求的东西。"""
from = 31
[[article]]
content = "男神的强国宣言"
date = 2021-03-29
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247488284&idx=1&sn=3638b0d45425402a97a907ebdfe07ce0"
[[article]]
content = "男神生日快乐！祝男神年年胜意，岁岁欢喜！"
date = 2021-04-09
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247488392&idx=1&sn=a9a81439e0093fd28c5ec453e3ee6419"
[[article]]
content = "千日圆满 感动初三"
date = 2023-04-29
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247491100&idx=1&sn=3e48217a9493b07c1218c250cc000cfb"
