name_en = "Crystal"
nickname = ["火山"]
relationship = [{ by = 21, is = "儿子" }]
reviews = [
    """火山姐你好呀！早在正式开学前就有幸请到你来帮我布置课室，一手娟秀的小字让我对你影响深刻，你笑起来眼睛弯弯的，好可爱！你严于律己，处事客观公正，对工作认真负责，作为班级的纪律委员真是实至名归。而且你能够有全局观，我还记得你在微信上和我道出的委屈，其实我很能体会，但好在你最后还是坚持下来了。你还是个手工达人，你徒手制作的校门模型和缤纷汇天桥可以媲美定制手办，刺绣选修课上，你的作品上乘，丝毫不亚于为师的水准。你观察力超凡脱俗，出版的“火山新闻”报道及时，视角独特，对人物间的关系解读得精辟且令人恍然大悟。更难能可贵的，是你又有着和温婉外貌不是特别贴合的真性情，朋友圈对我完全不设防，从认真干饭的演讲到面对偷拍者镜头风雨不动安如山地化妆。谢谢你的信任，很高兴认识你！""",

    """我家火山聪明伶俐，在课堂上总是能看到你认真思考的样子；我家火山活泼可爱，在课室总是能看到你笑脸；我家火山幽默风趣，处事公正，大家都很认可由你来做班级的纪律委员……总之，你在班里很受欢迎，人气很旺哦！
记得这学期体检验血时，你花容失色却还是显得很端庄；记得线上授课时，屏幕上的你眉头紧皱，用心勾描记录每一个知识点；更记得你王者荣耀打得很好，但是渐渐地战绩超越了成绩。
你这么聪明，一定知道该怎样取舍，“很暴躁的火山”息怒，静心，加油！""",

    """张灿你好呀，在班级里担任着纪律委员你，在执行任务的时候，不徇私情，对任何事件处理的都非常客观负责。上课时你严于律己，并且每次发言都精辟且令人恍然大悟，那一次次角度独特的发言，都引起大家热烈的掌声；课间经常能看到你坐在座位上，认真完成作业或刷题，完全不受任何外界因素的干扰；建模时你心灵手巧，将一个个物品涂上恰当的颜色，放到合适的位置；你性格温和，虽然被同学们称为火山，却从没见过你“爆发”；你的观察力超凡脱俗，总能发现别人未曾注意的事……你有如此之多的优点，很高兴认识你哦！""",

    """火山这学期过得起起伏伏颇有波折，有尝试时的拼搏，有竞争时的激烈，有比较时的徘徊，还有最后的坦然。过程中老师没有找过你太多，但是整个学期其实都关注你，好在波折没有影响成绩，你仍然是那个雄姿英发的火山，下学期，爆发给大家看看！""",
]
[anecdote]
embarrassment = "唱歌唱一路发现后面有人"
interests = "画画书法"
want = "想学会自己做衣服"
[[article]]
content = "火山姐二次革命"
date = 2021-04-07
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247488390&idx=1&sn=0e127e3b34015d0ea3f663ff5cf64a42"
[[article]]
content = "值日班长张灿的述职报告"
date = 2021-12-12
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247490998&idx=1&sn=9ba58cb0a36f7e8fffa105b17e098208"
[[article]]
content = "我以妙笔绘青春——第一届手绘杂志原创大赛"
date = 2021-03-04
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247487140&idx=1&sn=defc6000c7392dfb65d5a4afd7285bf5"
[[article]]
content = "火山姐三岁零一百二十个月生日快乐！"
date = 2021-09-16
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247490623&idx=1&sn=132d86b21ebc1404f4b8086810711b53"
[[article]]
content = "大单朝钟帅三变法 平杠王皇权稳如山"
date = 2021-07-25
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247490567&idx=1&sn=5fd134138df2210d7c35a0dae71be4d8"
[[article]]
content = "岁岁年年，元宵喜乐"
date = 2021-02-26
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247483702&idx=1&sn=295f4d94cf5be39ddb112e378372d2c0"
