name_en = "Tony"
nickname = ["傻儿子", "土豆", "地主家的", "大垃圾箱", "说唱教父", "铁块"]
plots = ["上课摸鱼", "中午关怀", "体锻打球", "晚修发呆", "课间吹水", "走路上学", "走路回家"]
relationship = [
    { by = 11, is = "基友" },
    { by = 25, is = "朋友" },
    { by = 31, is = "儿子" },
    { by = 34, is = "儿子" },
    { by = 7, is = "猪队友" },
]
reviews = [
    """在班里可能很难找出一个和你相似的学生了，兼具热血与沉静，就像冰与火，明明互不相容，在你身上却又完美融合。你的热血表现在那一次与长寿的武艺切磋，更表现在对篮球的痴迷，甚至在课堂上也兴致高昂地利用一切来练习抛球；你的沉静表现在严于律己，整整一学期，你从未迟到，还有着超乎寻常的好脾气，因为我还记得，开放日表演时，当多数人看到我的化妆水平后，见到我都会四散奔逃，岿然不动的，你是硕果仅存的几个，纵然被我描化得惊心动魄，也仍然一脸淡定，一笑而过。我当时看着你潇洒的背影暗暗感叹，真有成大事者的风范。你又有点天然呆，因为我还记得你的课前演讲，慌乱之中急中生智，给大家表演七步洗手大法。另外我也还没忘记，你在校园模型制作大赛上，为模型喷漆，隔着照片我已经被气味熏得上头，你却可以自在微笑，实在是让人佩服。
这个学期，承蒙关照，下学期我们精彩继续哈！很高兴认识你！""",

    """不得不承认，你身上有着自己独树一帜的幽默气息，只要有你在，大家都不会害怕无聊。也不必说些什么，也许只需要一举手、一低眉，自然就有一段幽默态度。作为班级的幽默担当，你实至名归。另外，这学期为师还发现你真的是一只呆瓜，换班考试时，隔壁班小女生在你桌上留下的热情邀请，你却一丝不苟地给涂掉了，引得一票八卦群众直呼浪费，纷纷摩拳擦掌，准备进行“刮刮乐”大业，这时你脸上的淡然就已经尽数体现了。
但“人不轻狂枉少年”，纵然好脾气如你一般，也还是有抓狂的时候，为师就曾亲眼见你怒胀双腮，狠狠地踢同学的书包撒气，细问之下，竟然只是因为零食被拿……果然真性情……""",

    """一提到你，首先想到的就是你幽默的语气和天真的笑容，遇事沉着冷静，无论在哪看到你，你都迈着那大爷一般的步伐，慢悠悠地走着；数学是你的强项，数学课上，你常用自己独特并且简单明了的方法，给同学们上台解答题目，一些独特的方法连老师都没想到，好几次都令老师拍案叫绝，获得了“面积法小王子”的美誉；你平常话不多，但只要一开口，绝对能逗得大家哈哈大笑；课余时间的你还有点呆，对什么事都懵懵懂懂，但又总能随机应变，随着时间的流逝、年龄的增长，你成熟了，收敛了自己的小脾气，将温顺的一面展示给了大家，这个集体，也因为你多了一份色彩，感谢有你，感恩遇见。""",

    """挥洒自如的投篮小将：你颇具大将风度地站在球场，举重若轻地将篮球投进篮筐，那份轻松与洒脱令人欣赏。书声和笑声常常伴随着多才多艺的你。美中不足的是展开作业本，那潦草的字体使人难以相信出自你白皙秀气的十指。字是门面，理当早练！真诚地希望在新的学期里，你能撷取更多的学习硕果，家希，愿成功伴你同行！""",

    """你知道吗？一开始我们都以为你是一个生性冷静的学生，你有聪明的头脑，数学成绩可以作证，可文科（尤其作文）却没有让人特别满意。如果说你是一个“懒”孩子，倒也委屈。作为本班考场作文三巨匠之一，磕磕绊绊地写了很多作文了，线下课的午休辅导，你也是每天都参加。所以相信，你只要坚持下去，认真学习，一定会考上理想的高中。""",
]
[[comment]]
date = 2022-12-03
description = """你是一个积极阳光的男生，总是能看见你跟男生一起打闹。你总能语出惊人，希望你以后上课能忍住，因为高中老师也许直接把你拉去办公室。你真得很好笑，坐在你旁边听到你和别人的对话都忍俊不禁。上课憋笑很难，不要这么对高中同学。你挺负责的，总是按时收语文题目，虽然总是在我睡觉时叫我起来交。希望你未来能更好，将老师都没有的颜色保留住。"""
from = 10
[[comment]]
date = 2022-12-03
description = """作为班里的傻儿子，你总能给课堂增添乐趣，给班级带来欢笑，虽然平时看起来“傻傻”的，但你的成绩却十分优异，学习也很认真。在数学课上，你总能破解出那些难题，下课时，你也经常和同学讨论问题。很高兴和你成为同学，希望你的成绩能越来越好！"""
from = 30
[[comment]]
date = 2022-12-03
description = """rap教父兼地主家的傻儿子风靡一班，无人不晓。论理科，计算速度飞宇不凡，解几何中善用面积。论体育，篮球有独家秘诀，一炸球，一过人，三步上篮，一气呵成，让人拍手称快，惊叹不已。有表面悠闲自在，且又有过人才能的气质，恐怕也只有地主家的“傻”儿子了吧。"""
from = 15
[[comment]]
date = 2022-12-03
description = """从地主家的傻儿子到希望之光，你一直是班级不可或缺的重要人物，不断为我们创造新梗，带来欢乐。不仅唱跳rap篮球样样精通，而且幽默也在线。有幸成为你的同学。因为你，我们的初中生活更加精彩"""
from = 33
[[comment]]
date = 2022-12-03
description = """林家希，是个可回收“LJX”（垃圾箱），我们都叫他儿子。他语言文明有礼，时刻注意他人感受，在恰当的时候问候别人，以控制他人情绪，防止不必要的事情发生。他热爱打篮球，下雨天时都去打篮球。
事件：他曾与我和猴子投篮比赛，他连进六七个球秒杀全场。我卡在第一个点，猴子差一点追上儿子。
他编程能力很强，他曾组建开发一个项目，可惜创业未半而中道崩砠。他数学也很强，曾嘲讽我，“连巩固一都不会啊？”，还在一次赌做数学题中赢了我50块。"""
from = 25
[anecdote]
embarrassment = "打ball被sb拍下来"
interests = "打ball、打game"
want = "扣篮"
[[article]]
content = "我以妙笔绘青春——第一届手绘杂志原创大赛"
date = 2021-03-04
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247487140&idx=1&sn=defc6000c7392dfb65d5a4afd7285bf5"
[[article]]
content = "双生同庆，可喜可贺，同年同月同日生的缘分呢，肉姐和傻儿子生日快乐，可可爱爱，期中加油！"
date = 2021-10-27
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247490987&idx=1&sn=360f279f28f3c0a35ab95dde9601023d"
[[article]]
content = "《一史》首发大作"
date = 2021-07-12
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247490369&idx=1&sn=7841598c75bc5737fadfb4bb7221c339"
[[article]]
content = "这样的人让我感动"
date = 2021-04-16
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247488417&idx=1&sn=5b62b024e2d5edc7c6813c794040af35"
