nickname = [
    "说唱教父",
    "大垃圾箱",
    "土豆",
    "傻儿子",
    "地主家的",
]
relationship = [
    { with = 11, is = "孙子" },
    { with = 31, is = "孙子" },
    { with = 13, is = "孙子" },
    { with = 25, is = "孙子" },
    { with = 34, is = "孙子" },
    { with = 7, is = "孙子" }
]
plots = [
    "走路上学",
    "上课摸鱼",
    "课间吹水",
    "中午关怀",
    "体锻打球",
    "晚修发呆",
    "走路回家",
]
[[comment]]
from = 10
date = 2022-12-03
description = """你是一个积极阳光的男生，总是能看见你跟男生一起打闹。你总能语出惊人，希望你以后上课能忍住，因为高中老师也许直接把你拉去办公室。你真得很好笑，坐在你旁边听到你和别人的对话都忍俊不禁。上课憋笑很难，不要这么对高中同学。你挺负责的，总是按时收语文题目，虽然总是在我睡觉时叫我起来交。希望你未来能更好，将老师都没有的颜色保留住。"""
[[comment]]
from = 30
date = 2022-12-03
description = """作为班里的傻儿子，你总能给课堂增添乐趣，给班级带来欢笑,虽然平时看起来‘傻傻’的，但你的成绩却十分优异，学习也很认真。在数学课上，你总能破解出那些难题，下课时，你也经常和同学讨论问题。很高兴和你成为同学，希望你的成绩能越来越好！"""
[[comment]]
from = 15
date = 2022-12-03
description = """rap教父兼地主家的傻儿子风靡一班，无人不晓。论理科，计算速度飞宇不凡，解几何中善用面积。论体育，篮球有独家秘诀，一炸球，一过人，三步上篮，一气呵成，让人拍手称快，惊叹不已。有表面悠闲自在，且又有过人才能的气质，恐怕也只有地主家的“傻”儿子了吧。"""
[[comment]]
from = 33
date = 2022-12-03
description = """从地主家的傻儿子到希望之光，你一直是班级不可或缺的重要人物，不断为我们创造新梗，带来欢乐。不仅唱跳rap篮球样样精通，而且幽默也在线。有幸成为你的同学。因为你，我们的初中生活更加精彩"""
[[comment]]
from = 25
date = 2022-12-03
description = """林家希，是个可回收“LJX”（垃圾箱），我们都叫他儿子。他语言文明有礼，时刻注意他人感受，在恰当的时候问候别人，以控制他人情绪，防止不必要的事情发生。他热爱打篮球，下雨天时都去打篮球。
事件：他曾与我和猴子投篮比赛，他连进六七个球秒杀全场。我卡在第一个点，猴子差一点追上儿子。
他编程能力很强，他曾组建开发一个项目，可惜创业未半而中道崩砠。他数学也很强，曾嘲讽我，“连巩固一都不会啊？”，还在一次赌做数学题中赢了我50块。"""