name_en = "Fiona"
nickname = ["frog", "芳菲", "奶牛", "尖叫鸡"]
relationship = [
    { by = 20, is = "养的大frog" },
    { by = 29, is = "好friend" },
    { by = 32, is = "朋友" },
]
reviews = [
    """提起你，我首先想起来的竟然是你爽朗的笑声和因为笑而涨红的脸，魔性而毫不掩饰，这也透露了你的性格，耿直率真。你好像没有太多心事，每每见到你，不是拉着小姐妹在校园游逛，就是到办公室偷瞄我有没有发现你的游手好闲，一旦被我目光锁定，便略显尴尬地落荒而逃，同时又会留给我一串大笑。我本来以为你就是这样一个没心没肺的姑娘，却没想到那一次的课前演讲，你准备得那么认真，讲述得那么动情。原来你把喜悲都深深藏在了心里，原来你的内心这样细腻。你对同学很热心，那一次开放日演出，我还没到课室，你已经开始帮同学一笔笔细心描化了，经过你细心勾画的她们，都妆容精致动人。你是一个善良的姑娘，为师希望你在学习上再用心一些，沉静下来，你会更优秀。下学期，希望你给我更多惊喜哦！很高兴认识你！""",

    """“黄梅时节家家雨，青草池塘处处蛙”每当读起这两句诗，都会想起我家frog。
一直认为你是率性乐观的，也就是通俗所说的心大，直到昨天看到你脚边掉落的成团黑发，才意识到其实你承受的压力也相当大。这一学期于你而言并不轻松，陡然空降的周测如同一把双刃剑，一边斩断大家的懒惰，一边也给了你们或大或小的压力，你便属于后者。
我曾愤恨于你的懈怠，而今又心痛于你的苦苦承压。frog，这世上没有谁能一直跟随你到最后的，你能做的只有自己一路向前冲，我们会尽力帮你，但是你终究要靠自己。""",

    """每次路过生物园，听到一声声蛙叫，总能使人想起你那爽朗的“蛙笑”。你总是自嘲自己的成绩不尽人意，课室同学却说，为你讲解物理，你理解的速度惊人，让人不禁感叹你的悟性之高；你很聪明机智，下课时你常常拉着小伙伴去办公室问老师问题，往往一问就是整个课间。你还细心体贴，圣诞节你为大家精心准备了礼物，你的大方使大家动容。
芳菲呀，你人真的很不错，很高兴能认识你，同学们说，古有望子成龙，今有望友成凤，希望你越来越好，更上一层楼哈！""",

    """你在校能严格遵守各项规章制度，团结同学，人缘很是不错。你也很聪明，但不足的是老师发现你的听课效率不高，容易受到外界因素的影响。老师希望在今后的学习中你能以更高的标准严格要求自己，使自己有更大的进步。""",

    """这个学期你做了不应该做的事，把心思放在了别的事情上，结果使自己的成绩骤然下降。这让老师和家长都为你深深担忧。你是聪明的，但是却短视。如果几个月后，你失利了，将何去何从呢？记住：做好自己分内的事情，分内的事，就是为自己负责哦！""",
]
[[comment]]
date = 2022-12-03
description = """在第一次看到你时，就被你那阳光向上的气质所感染，你在各个领域都表现活跃，在我们班的团建中可以不止一次的看到你活跃的身影，你在艺术方面也是一把好手，在许多方面都令人赞叹，只不过在学习上的天赋似乎没有被你太看重，谁都不希望你的才华被埋没，在高中继续加油吧！"""
from = 32
[[comment]]
date = 2022-12-06
description = """一个很热情的女生。学习方面虽然还有很大的调整空间，但也在用自己的方式努力着，进步更是有目共睹。祝——前程似锦。"""
from = 31
[[comment]]
date = 2022-12-07
description = """伍纯菲作为一般的零食小柜，她的零食数不胜数。她的书包就像哆啦A梦的袋子，似乎永远掏不完，而且什么都有。八年级本人有幸与她做一次同桌，因为人性格大方，所以我在八年级被她进行了零食投喂，胖了五斤。。。虽然学习有待努力，但她在绘画上的天赋无人能敌，九年级的板报就是她画的。她的笑声异常魔性，总是能让我感觉身处鬼屋，又或者说她的笑声余音绕梁，把我的梁都快绕断了。作为跟她九年的同学，她的变化真的异常的大，不仅没有胖，还越得越高了。伍纯菲的性格阴晴不定，说的好听，就是乐观，说的实在，就是人格分裂。记得之前有一次她问我要作业，整个人就跟一只小狗一样，楚楚可怜，可转眼，但我向她要零食的时候，她突然又变得高冷。让我对伍纯菲表示真诚的感谢，感谢她将我喂胖。"""
from = 28
[anecdote]
embarrassment = "和朋友去看5D电影（好像是），然后电影院那个椅子会动还会喷水。电影中间的时候，又被喷了，还吓得一激灵，很大声的尖叫，然后全部人齐刷刷地看过来"
interests = "画画、听歌、打游戏（看视频？）、睡觉"
want = "和泡菜去海边度假～"
[[article]]
content = "我以妙笔绘青春——第一届手绘杂志原创大赛"
date = 2021-03-04
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247487140&idx=1&sn=defc6000c7392dfb65d5a4afd7285bf5"
[[article]]
content = "Frog.菲生日快乐，祝你让快乐成为日常，率性爽朗"
date = 2021-04-30
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247489106&idx=1&sn=2bcb1136295e2606300bd0ba9f5adc57"
