name_en = "Kaleena"
nickname = ["恩琦"]
relationship = [
    { with = 32, is = "曾孙" },
    { with = 1, is = "儿子" },
    { with = 21, is = "孙子" },
    { with = 20, is = "欧美圈共同爱好者" },
]
plots = ["写完作业画画，被土灰骂", "与同学抱怨社畜生活", "下课找老师聊天，成为老好人"]
