name_en = "Kaleena"
nickname = ["Ajer", "小红", "恩琦", "小任", "雨荨"]
plots = ["下课找老师聊天，成为老好人", "与同学抱怨社畜生活", "写完作业画画，被土灰骂"]
relationship = [
    { by = 23, is = "九年老同学" },
    { by = 32, is = "朋友" },
    { by = 33, is = "女神" },
]
reviews = [
    """记得第一次见面时，你小小一只，戴着黑框眼镜，一脸严肃的样子，让人不免对你肃然起敬。但没想到，你其实是一颗伪装成学术大儒的开心果。记得运动会上，你毫不胆怯于我班主任的身份，公然拍我丑照并做成表情包；记得微信聊天时，我们称兄道弟相见恨晚，毫无压力和代沟，畅快淋漓；记得你一次次对同学发言的神补刀，也从每一次的接触中感受到，你很善良，很好。印象最深的还是模型比赛前一晚，阿杠在隔壁桌犯蠢时，你劝他的那句“杠，你适可而止吧”，善意又点到为止。你多才多艺，唱跳俱佳，在开放日和元旦汇演的舞台上，你都风采出众。英语口音又极其纯正，配音对于你而言仿佛信手拈来。难能可贵的是，你还拥有独立的精神，对事情有自己的判断，对世界有自己的理解。小姑娘不简单，很高兴认识你！（只是不要太贪睡，还差5张瞌睡照，我就要召唤神龙了）""",

    """你口才了得，热爱集体，是一个大方开朗的同学；你遇事有主见，每每遇到问题乃至分析问题，你都有自己的观点和看法；你成绩优异，无论是单科成绩还是总分，甚至曾跃居年级榜首；你细心体贴，朕也曾得到过你的温暖关怀；你多才多艺，团建时的课本剧表演，你证明了自己的不俗演技，学生会组织的英文歌唱比赛你也表现不俗……
但是你要承认自己有一些小缺点，其实良言一句三冬暖，如果豆腐心，何必刀子嘴呢，对吗？""",

    """这学期就这么结束了？为师还没缓过神来。
想想这学期，你还真是能给人带来欢乐，从你生日那幅别有一般滋味的对联，到每次课间的欢快畅谈，现在想起来都很开心，你真是个聪明孩子，公开课结束后，校长明明要点评为师的课上得怎么样，结果老先生一直夸奖你，可想而知你是有多讨人喜欢了。
可是这学期，还是有些需要改进和反思。你很能体察人心，可是凡事往往有度，你这么聪明，一定能懂。""",

    """你虽是女孩，却有男孩般的性格，不娇气，有正义感。学习嘛，还比较认真，平时能按时完成老师布置的作业，成绩优良，做事认真。但课后不太喜欢运动，希望你尽量多多锻炼身体，成为更好的自己。像一瓶飘柔，就是那么自信！""",

    """你可真是古灵精怪，这个学期的学习很大一部分都是线上教学，结果给了你这厮截我表情包的机会。不过这也侧面证明了我们关系亦师亦友。其实这学期你的表现更加优秀了，文科的缜密思维成就了你，这是好样的！但是有句忠告希望你能静心听听：能够友好相处，要有颗宽容的心，得让人处且让人，你一定会做好的，对吗？""",
]
[anecdote]
embarrassment = "4岁的时候踩树叶意外踩到狗屎"
interests = "唱歌、听音乐、画画"
want = "完成一本小说出版"
[[article]]
content = "恩琦的青春宣言"
date = 2021-04-11
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247488393&idx=1&sn=031bb84f60c69706942aefcb907fbb16"
[[article]]
content = "正视而不妖魔化——任恩琦谈性话题"
date = 2021-05-25
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247489555&idx=1&sn=f40d94fa816fde6c70dcc0551aae51c1"
[[article]]
content = "我以妙笔绘青春——第一届手绘杂志原创大赛"
date = 2021-03-04
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247487140&idx=1&sn=defc6000c7392dfb65d5a4afd7285bf5"
[[article]]
content = "一份特（tu）殊（wei）的生日祝福"
date = 2021-08-22
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247490618&idx=1&sn=f48a699fd3d0e9dbdd060b9861af3521"
[[article]]
content = "大单朝钟帅三变法 平杠王皇权稳如山"
date = 2021-07-25
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247490567&idx=1&sn=5fd134138df2210d7c35a0dae71be4d8"
[[article]]
content = "这样的人让我敬佩 - by 恩琦"
date = 2021-04-08
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247488391&idx=1&sn=a97dfa33db1194a30a385a84bd86c058"
