name_en = "Fiona"
nickname = ["富裕", "Fia云", "没有姓名摆大烂的物理科代", "健忘的纪律委员"]
plots = ["与八年级抢饭", "中午关怀", "厕所天花板上的纸巾球", "厕所开盖有惊喜", "雨中跑步，裤子全湿"]
relationship = [
    { by = 1, is = "亲爱的金主爸爸" },
    { by = 19, is = "好friend" },
    { by = 2, is = "欧美圈共同爱好者" },
    { by = 21, is = "狗子" },
    { by = 29, is = "好朋友" },
]
reviews = [
    """早在开学之初，听到你的名字我直接就是一愣。这应该是我目前为止见到的最有自己特点的名字了。之后终于见到你，如果不是这个与众不同的名字，你会因为鹤立鸡群的身高优势被最先记住，你会因为娟秀的字迹被最先记住，你也会因为变幻莫测的发型被最先记住。
作为班级的学习委员，你尽职尽责，班级几乎没有因为缺交班务日志而被扣过分，这是一份日复一日，旷日持久的工作，能坚持至如此实属不易，更何况我还见到了你贴在桌面的提醒便签，更让我感慨于你的细心；你热心公益，冒雨参与捐衣送暖志愿活动的身影真美；你敢作敢当，校园模型制作大赛时的小插曲我还记忆犹新，但那是青春的小小张狂，好在你及时改正过来了。你已经很优秀了，如果在时间管理方面再注意一点，在班里见贤思齐，那你会让自己大吃一惊的，要不要给自己一个机会呢？？""",

    """你就像你的名字一样，烟云袅袅，如花似玉，豆蔻年华就已然身高出众，出落成一个温婉端庄的女孩。也许是家传的基因让你可以轻松对一众庸才进行血脉压制，一手娟秀的小字实在让人赏心悦目。文静幽默是大家对你最中肯的评价，在课室总是能看到你甜美的笑。因为你的坚持，班级从未因班务日志而扣分。成绩上虽有起有落，但为师相信你沉静下来后，就能绽放自己的精彩。方向对了，还怕路远吗？""",

    """小富裕还是一如既往的活泼，灵动又可爱，经过这一学期的进一步交往，你那充满活力的行为深深吸引了同学们，大家反映，最难忘的还是你的茉莉绿茶，因为你几乎一周买一次，所以周围小馋猫往往也能沾光来几口。
你性格开朗，那独特的音色，颇有搞笑区up主的风范，颜色极具个性，让人一听便知，原来是我家小富宇啊。
你身上有无穷的魅力，但是也要认识到自己还有很大的提升空间。既然选择了远方便，希望你坚定风雨兼程。""",

    """你对生活观察细致，绘画认真，课上画出的漫画人物栩栩如生，真不简单。但是你自由的思想活动占据了太多宝贵的时间，作业也经常完成得拖拖拉拉。老师真希望看到你能珍惜时间，能将你的聪明才智更多地用到学习上去，能成为一个更加优秀的好学生。""",

    """要怎么说呢，小富裕的提升空间确实不小，因为这学期不知是什么原因，这学期你的学习态度不够端正，对学习兴趣不甚浓厚。老师提醒你，学习不是买卖商品，说买就买，现在不努力的话，将来要后悔。希望你能在剩下的时间里，发奋图强，刻苦钻研，争取在中考时考出好成绩，回报培养你的家长。""",
]
[[comment]]
date = 2022-12-04
description = """符玉雅云，姓符，名玉雅云，身高大约一米七五（不是很准），性别女，银河系第一悬臂猎户臂太阳系（从太阳往外数第三颗）地球，亚洲中国广东省广州市番禺区祈福英语实验中学9B1的学生之一。身份物理课代表。任职期间视数年如一日，兢兢业业，一丝不苟，认真对待老师发给的任务，从不懈怠丝毫。性格十分开朗，和一班众女生能打成一片，也能脱颖而出。理科方面较为突出，能有奇思妙想，令人惊叹。文科也毫不逊色，文理均衡发展，未曾偏科。"""
from = 9
[[comment]]
date = 2022-12-06
description = """她是我在这个班认识时间最久的人之一，所以自然而然她也是我很好的朋友。她超赞的好吧，对朋友很真诚，很好，没有伪装，喜欢把她最真实的一面展现给她的好朋友。我特别羡慕她一点，就是她总能将我记不住的知识点说成是常识。"""
from = 1
[[comment]]
date = 2022-12-06
description = """从小学就认识但却没有很熟，直到初二才开始真正的了解。性格很好很活泼很开朗（搞笑女，每次跟你聊天都有说不完的话，有笑不完的梗。是一个梯粉（师妹嘻嘻，因为都是kpop人所以共同话题非常多，经常会被魔性的歌词洗脑。总是不是很自信，，但是我想说，你很高很瘦很美，不需要这么在意别人的眼光，你真的很棒！"""
from = 29
[anecdote]
embarrassment = "七年级的时候因为“谁是油头公主”和伍纯菲拳打脚踢，现场一度十分混乱，你一脚我一脚"
interests = "音乐、画画、唱歌、看视频"
want = "陪想见的人世界旅行，把美丽的景色印在脑海里，用画笔和相机记录给所有人看，告诉每一个爱的人他们有多重要，学习作曲作词编曲用自己的风格的音乐表达情感，学习很多种语言"
[[article]]
content = "值日班长符玉雅云的述职报告"
date = 2021-12-02
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247490992&idx=1&sn=4dc12a6eaa013a9527ac1ef253a7aea3"
[[article]]
content = "我以妙笔绘青春——第一届手绘杂志原创大赛"
date = 2021-03-04
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247487140&idx=1&sn=defc6000c7392dfb65d5a4afd7285bf5"
[[article]]
content = "富裕生日快乐，你的尽责和进步我们有目共睹，祝你学业更上一层楼，个子高高"
date = 2021-03-02
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247484133&idx=1&sn=3cd0496bb843a5b86e6cea33dd11f006"
[[article]]
content = "那束光，照亮我的世界"
date = 2021-09-18
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247490646&idx=1&sn=5871940946468acc5089c70c990844f6"
