name_en = "Queen"
nickname = ["cky", "匡匡", "匡匡小盆友", "匡匡老盆友"]
plots = [
    "和妹妹一起去上学开始",
    "和敖子不紧不慢地去干饭，在关怀的提醒下愉快地离开饭堂",
    "回到学校第一件事就是用我粉色小水杯去接水，顺便和刚睡醒还迷迷糊糊的同学们挨个打招呼。课间我依然坚守着自己的一亩三分地，绝不会离它太远",
    "大家从一开始在课间聊天变成了大部分同学选择在课间休息",
    "打完餐后第一件事就是寻找曾铉雅（她每次都比我早到） 回班后寻找敖卓茵，'施舍'给她",
    "晚上通常会在班里待一会儿再慢悠悠晃回家吃饭，但体锻的话我们一下课就直奔厕所换衣服 or 梳头发 or 擦防晒最后女生们才三个一群五个一伙地走向操场～",
]
relationship = [
    { by = 1, is = "“好弟弟”" },
    { by = 2, is = "孙子" },
    { by = 20, is = "儿子" },
    { by = 32, is = "朋友" },
    { by = 7, is = "好帮手" },
]
reviews = [
    """匡匡你长得真好看！笑起来乖乖甜甜的，眼睛好像会说话。你很有礼貌，老师们都很喜欢来一班上课，一部分也是因为可以听你道一声“老师好”。还记得自编操比赛时，站在第一排的你动作到位，活力四射，每个节拍都洋溢着青春的气息，及至后来在开放日的演出和元旦的汇演上，你的舞姿更是惊艳了众人。
但是毕竟，这些都是外在的美好，好看的皮囊千篇一律，美丽的灵魂却万里挑一。难能可贵的是，你的性格也如长相般甜美，记得校园模型大赛结束后，你也参与到了主动打扫中庭的活动当中，我们三个在别班同学的趴窗鼓励下，完成了整个中庭的清扫工作，还真是让人难忘。
学习上，评阅你的作业也是一种享受，字迹工整，认真美观，条理清晰，“祈福杯”现场书法大赛上，你轻而易举就获得了二等奖就是最好的证明。一拼到底的英语比赛上，你也大显身手。虽然这学期，你的成绩还有较大的提升空间，但是我相信你，坚持下去，一定会把成绩提高上来的。有志者，事竟成，加油我的小匡匡，很高兴认识你！""",

    """我家匡匡还是那么好看，青春乖巧又可爱。回望这一学期，你过得还真是有惊无险:一开始就精准打击了无聊学长的骚扰，后来又扛过了预警签单的压力，整个学期的成绩还稳中有升。
最难以忘怀的就是你尽职尽责的模样，每逢周三周五，就有一个美丽的身影出现在讲台上：“拿出中方英语书，翻到117页……”，被大家笑称“匡里匡气”。
整个学期就这样度过了，很开心能和这么可爱的匡匡一起，下学期继续哈！
""",

    """匡匡啊，这学期就这样匆匆过去了，好像还没来得及和你好好聊一次天，不过细细想想，这学期又这么慢，慢到你可爱的妹妹总是要来课室等你下课，慢到怪阿姨得逞，抱了好机会小姑娘：开学帮我们搬书（虽然你这么瘦）、周五放学你迟迟不走、甚至校运会也是“披星戴月”而归，要为师拍照给你的父母报平安。把青春都献给了学校生活。
就这样不断地努力着努力着，你也帮助集体赢得了很多荣誉，无论校运会还是模型制作大赛。
好可爱的匡匡啊，好喜欢你啊！""",

    """这学期你的进步非常大，这是人所共知的，老师为你感到高兴，也知道优异的成绩来自你不懈地发愤苦读。你即将成为一名初三学生，新的学习生活将在你面前展开。此时此刻，老师想送你一句话：耐心是一切聪明才智的基础，胜利者不一定是跑得最快的人，而是最能耐久的人。""",

    """我家匡匡真好看！而且不仅仅是长得好看，跳舞更好看！而且匡匡不管在什么方面，都是一个优秀的女孩子：字迹工整，每科作业都是一件艺术品；有文明礼貌的待人之道，见到哪位老师都会甜甜地问好；有刻苦认真的学习决心，能吃苦耐劳……匡匡这么可爱，就让为师更加舍不得你了，还剩最后一个学期，为师最大希的望是你能把所有的信心和决心全部放在学习上，好好努力，我家匡匡一定能考上理想的学校的，看好你呦！""",
]
[[comment]]
date = 2022-12-03
description = """陈匡莹，是个好女孩。她长得漂亮，这是公认的。她的进步，也是公认的。每次进步奖都有她的位置。她体育在女生中算十分优秀，是体育标兵。她善于交往。她对谁都很热情，无论男女老幼，这是一种难能可贵的热心。"""
from = 34
[[comment]]
date = 2022-12-04
description = """陈匡莹，是我们班上女生中的明星人物，不仅是体育中的佼佼者，也是学习的开拓者。她体育很好，是体育标兵。她学习一直在进步，是让人值得学习的。她，很热情开朗。作为不常与女生交往的我，写女生是很难的，但她是个例外。因为她的人尽皆知的善良。她的善良也吸引了很多人，我们班上也不乏欣赏她的人。很高兴能和她做三年同学，这是值得回忆的时光。"""
from = 6
[[comment]]
date = 2022-12-06
description = """她学习认真刻苦，乐于帮助他人，真诚友善，在学校期间积极参加各项活动。，在运动会上，他屡次站上领奖台，多次为班级争取荣誉。该生品质优秀，思想觉悟高，尊敬师长乐于帮助他人，成绩优异，深受师生喜爱。她是一位称职的课代表，收发作业当数她最积极，每当老师需要她的帮忙时，她总会放下正在做的事情，立刻给予老师帮助。而看看我们班级某些科代表，每天都不作为，两者一对比，她尽职尽责的品德，显得更加突出。"""
from = 13
[anecdote]
embarrassment = "体锻回校黑灯瞎火（没带眼镜）跟迎面走来的韩老师打招呼叫成“石老师好”"
interests = "唱歌，跳舞，烘焙"
want = "考上理想高中！！！（也希望下次自己做的蛋糕像样~）"
[[article]]
content = "我以妙笔绘青春——第一届手绘杂志原创大赛"
date = 2021-03-04
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247487140&idx=1&sn=defc6000c7392dfb65d5a4afd7285bf5"
