name_en = "Queen"
nickname = [
    "匡匡",
    "cky",
]
relationship = [
    { with = 1, is = "儿子" },
    { with = 17, is = "儿子" },
    { with = 8, is = "女儿" },
    { with = 20, is = "狗子" }
]
plots = [
    "和妹妹一起去上学开始",
    "打完餐后第一件事就是寻找曾铉雅（她每次都比我早到） 回班后寻找敖卓茵，'施舍'给她",
    "大家从一开始在课间聊天变成了大部分同学选择在课间休息",
    "和敖子不紧不慢地去干饭，在关怀的提醒下愉快地离开饭堂",
    "回到学校第一件事就是用我粉色小水杯去接水，顺便和刚睡醒还迷迷糊糊的同学们挨个打招呼。课间我依然坚守着自己的一亩三分地，绝不会离它太远",
    "晚上通常会在班里待一会儿再慢悠悠晃回家吃饭，但体锻的话我们一下课就直奔厕所换衣服 or 梳头发 or 擦防晒最后女生们才三个一群五个一伙地走向操场～",
]
[[comment]]
from = 34
date = 2022-12-03
description = """陈匡莹，是个好女孩。她长得漂亮，这是公认的。她的进步，也是公认的。每次进步奖都有她的位置。她体育在女生中算十分优秀，是体育标兵。她善于交往。她对谁都很热情，无论男女老幼，这是一种难能可贵的热心。"""
[[comment]]
from = 6
date = 2022-12-04
description = """陈匡莹，是我们班上女生中的明星人物，不仅是体育中的佼佼者，也是学习的开拓者。她体育很好，是体育标兵。她学习一直在进步，是让人值得学习的。她，很热情开朗。作为不常与女生交往的我，写女生是很难的，但她是个例外。因为她的人尽皆知的善良。她的善良也吸引了很多人，我们班上也不乏欣赏她的人。很高兴能和她做三年同学，这是值得回忆的时光。"""
[[comment]]
from = 13
date = 2022-12-06
description = """她学习认真刻苦，乐于帮助他人，真诚友善，在学校期间积极参加各项活动。，在运动会上，他屡次站上领奖台，多次为班级争取荣誉。该生品质优秀，思想觉悟高，尊敬师长乐于帮助他人，成绩优异，深受师生喜爱。她是一位称职的课代表，收发作业当数她最积极，每当老师需要她的帮忙时，她总会放下正在做的事情，立刻给予老师帮助。而看看我们班级某些科代表，每天都不作为，两者一对比，她尽职尽责的品德，显得更加突出。"""