name_en = "Benson"
nickname = ["Benben", "小自信", "笨孙子", "自信男人", "龙虾"]
relationship = [{ by = 15, is = "朋友" }, { by = 28, is = "儿子" }]
reviews = [
    """提起你，首先想起的是你那张白净可爱的脸和温暖柔和的目光。你真是乖得要命，我曾经以为我永远都不会听到你讲话，其实现在也不是痕迹的你的声音。小小的你总是安静地坐在座位上，认认真真地学习，有时会看到你和同学合作背题，互相提问，态度紧张又和谐，那个画面让人明白了属于青春的奋斗的意义，你的成绩也因为这一路的稳扎稳打而一直保持稳定。相比于班里其他同学，你显得更加神秘一些，如果可以，希望你可以给我更多机会了解你。很高兴认识你！
""",

    """长隆的春游之旅，让为师记住了你恐高的窘相，在肆无忌惮取笑你的同时，我们的友谊也加深了呢。小自信真的很乖巧，一头浓密的秀发也让为师羡慕不已。平时的你十分安静，无论学习还是做事都一丝不苟，井井有条，连写的字都是安分守己的。大家都很喜欢这样优秀又不张扬的你。
这学期很开心能更了解你，下学期我们未完待续哈！""",

    """晚自习时，窗外的月亮格外明亮，正埋头苦学的你，就如月亮般清明澄澈，在同学眼中，你乌黑浓密的头发和白净的皮肤，充满了青春的格调，眼睛里又闪着求知的光芒，浑身散发着如月光般温和的气息。
从七年级开始，大家就被你专注认真的学习态度所震撼，大家说每天吃完晚饭，都能看到你与同学结伴复习的身影。你平时驯顺得像只小白兔，从来不闹腾，从来没跟其他人发生过冲突。
大家都很高兴能和你成为同学，祝你前程似锦，能在青春之时谱写出最美的乐章。""",

    """你言语不多，待人和气、善良，学习和做人一样，默默用功。真喜欢你笑的样子，别人与你讲话时，你总喜欢轻轻一笑，那么乖巧。有几次写作文时，你怯怯地告诉我你不想上交，怕写不好。小自信，为什么对自己说不呢？其实，你的语文基础知识很扎实。鼓起勇气，展示自己，衷心希望来年的你，能扬鞭奋起勇超他人，记住：“爱拼才会赢！”""",

    """你似乎一直以来都是一个不善言辞的学生，也许是学习紧张，也许是天生腼腆，但老师觉得你一定天性懂事、善良，这一学期，看着你一直默默努力，成绩稳中有升，老师相信只要你这样坚持不懈地努力下去，你一定会有收获。初三还剩下最后半学期了，老师希望你大胆提问，学好基础知识，弄懂、弄通每一个基础知识点，相信你一定会考上理想的高中！""",
]
[[comment]]
date = 2022-12-03
description = """你不会像其他男生那样吵吵闹闹，文文静静的，勤奋踏实，不骄不躁。可能是因为皮肤白和比较纤细的缘故，总是给人一种和你弱不禁风的错觉，但体育课上你总能很好地完成体能训练，记得那次全班一起做平板支撑，你竟是坚持到最后的两个人之中的一个！和你做同桌的时候，看到你上课时非常认真，下课也经常和周围同学讨论问题，学习态度认真，积极向上，希望你能越来越好！"""
from = 23
[[comment]]
date = 2022-12-03
description = """口罩下的你，总把实力深藏，九年级你变得好卷啊，教室里，总能看到你奋笔疾书的认真；体育课上，总能听闻你又把一大群同学甩在身后，凭借不凡的那样以冲进前列；谈笑中，总能想象到你被遮住的谦卑而温和的奇妙表情，常见你和黄森夕阳下跑道边捧着政治、历史资料，互考对方的快乐身影，每回看到都不由得心头一震：天啊，都这么拼搏的吗？Anyway，怀着敬佩，相信沉稳的你一定未来可期。"""
from = 7
[[comment]]
date = 2022-12-06
description = """我们班有一姓李的神人，长得跟普通人没啥区别，唯独脸上总挂着一样东西--口罩，因此我给它取名口罩李。口罩李对自己的口罩十分爱惜，除了吃饭，其余什么时候也不将其取下，我仔细观察过，口罩李早餐平均用时30秒，午餐和晚餐加起来用时不足4分钟，也就是说他一天中他只有5分钟是摘下口罩的，至于戴口罩的原因也有很多猜测，有的说他自疫情开始就习惯戴口罩，有的说他是为了遮住自己的绝世容颜，至今都没有统一的说法，但不可否认的是口罩李对他的口罩是真爱。要说口罩李最强悍的地方，那必须是他的体育，作为我们班最强体育生，他可以毫不费力地在800米，最后50米跑出4秒的成绩，还可以和我们说笑的同时持续做十几分钟的平板支撑，当然这一切都基于戴口罩之上，最让我惊叹的是他每次长跑时前面总是放水，直到最后200米才突然加速，将我们远远甩在身后，使我们叹为观止。"""
from = 13
[anecdote]
embarrassment = "作文写了5分"
interests = "睡觉"
want = "放假"
[[article]]
content = "我以妙笔绘青春——第一届手绘杂志原创大赛"
date = 2021-03-04
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247487140&idx=1&sn=defc6000c7392dfb65d5a4afd7285bf5"
[[article]]
content = "小自信生日快乐，全体师生祝愿您勇敢执着，不怕卫生间的小虫子"
date = 2021-08-19
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247490615&idx=1&sn=7639b66420ecefa91c8819309436334a"
