name_en = "Winnie"
nickname = ["肉姐", "花椒油", "痛苦黄瓜", "大星瓢虫", "温雷"]
relationship = [
    { by = 10, is = "好盆友" },
    { by = 30, is = "儿子" },
    { by = 33, is = "儿子" },
    { by = 5, is = "死鬼" },
    { by = 7, is = "支持者" },
]
reviews = [
    """开学不久，我就因为那张晚修观看《开学第一课》的照片记住了你，大大的眼睛里写满了对未知的好奇，真好看！但是你没有把美貌放在心里，在学习上你目标明确，踏实认真。每次批改你字迹工整的作业、翻阅你画满重点的练习册，我都能透过文字感受到你的用心。
但是你似乎并不快乐，总是看你眉头紧锁，很有一副忧心忡忡的样子。我猜想，你应该是为了成绩着急，为了在这个班级的压力而烦忧吧。其实大可不必，正是因为班级里优秀的同学多，所以才让你得以在良好的氛围中学习和进步，你要懂得林密树直的道理，每天进步一点点，和昨天的自己相比就好了。尽力而为，青春就是无悔的。美丽又踏实的肉姐，很高兴认识你哈！""",

    """这学期学了一个词“麂子”，又让我想起了沈从文的《边城》:“人又那么乖，和山头黄麂一样”，多像你。
黄麂有灵气，就像你，大眼睛透着聪慧的光；黄麂很单纯，就像你，没有圆滑世故的小聪明；黄麂很胆小，就像你，每每考完试你就鱼一般游过来，声音轻忽地诉说着刚刚的不足与失利，惹得为师也心头不忍，加以好言相劝。这一学期你过得波澜不惊，主要矛盾便是与每次成绩的较量，印象最深的就是那次你超过了班级平均分，脸上洋溢的那种笑让为师看了都不由自主地跟着你一起开心，但是似乎因为这种快乐来的格外稀少，才显得那么珍贵。
学习之路道阻且长，需要你披荆斩棘，如果有需要我的地方，尽管放马过来哈！""",

    """肉姐在我心里，一直是个文静端庄的江南美人形象，第一次遇见你的时候，应该是在小学初见时，惊艳于你的容颜与气度，当然还有你温和的澳门口音；后来的相处过程中，更钦佩于你的彬彬有礼，温润如玉，渐渐发现你温和的外表下，有一颗开朗细腻的心，你的世界里有自己的一套原则，有自己的一套体系。你做事有条理，有逻辑，井井有条，和你相处时，大家都会有一种如沐春风的温暖，平淡却又温馨安宁。七年级时，大家看到了你在学业上的专注和求知欲；八年级筹备元旦晚会时，大家又看到你希望为团队付出和承担责任的心；模型大赛，大家又看到你做事时的专注、认真。认识肉姐，真的超级幸运、超级开心，祝我们人美心善的肉姐，万事顺遂，平安健康。""",

    """你渴望学习成绩的进步，为此一如既往地坚持着自己刻苦努力、奋发图强的求学原则。所有这些努力最终也换来了令人满意的成绩。学习成绩仍然还可以“更上一层楼”，但你有坚定的信念。老师相信，成功的花朵在汗水的浇灌下一定会更加鲜艳。""",

    """肉姐一直都是一个性格温柔，态度亲和的文静女生。漂亮的大眼睛忽闪忽闪的，有着不一般的洞察力，对班里的不和谐总是能指出问题所在。肉姐能尊师爱友，有着很强的荣誉感和责任心；作为学习委员，堪称班主任的左膀右臂，总是那么自觉地完成老师布置的任务，将缺交情况登记得清清楚楚，让人一目了然。惊闻你要到国际学校继续学习了，为师真是不舍得你啊，但是老师也为肉姐的目标清晰而欣慰，加油肉姐，无论你去哪里，你都一定很优秀的！""",
]
[[comment]]
date = 2022-12-03
description = """黄嘉玉，一个很好看的女生。还会说粤语。为人善良，不会惹是生非。然而，作为一名男生，我可能评价较为片面。她可能课上没什么存在感，比较安静，经常坐在那里头朝下独立思考，但是平时也为我们的班级作出了许多的贡献"""
from = 34
[[comment]]
date = 2022-12-03
description = """你一次听说你是在江某口中，一向成熟稳重的他给了你极高的评价。这不禁让我好奇，你究竟是个怎样的人。初见你时，我便为你所惊艳。你生的极美，一双好看的眸子中透着清冷。我一向眼高于顶，却突然有了种心动的感觉。雨夜，我望着那倾盆的大雨一筹莫展。你的出现似一束光照亮我的心房。八年级，我请求老师将你我调成同桌，只为每天能看着你。自卑如我，只能将这份感情埋藏心底。临近毕业，我们马上各奔东西。我知道，再不说便没机会了。我从不奢求什么，只是毕业前的最后一次疯狂。以上都是ztz真情流露，我的评价是不如宵宫"""
from = 35
[[comment]]
date = 2022-12-03
description = """喜欢你的高马尾，喜欢你的大眼睛，高冷女神的人设不可避免～无数男生都拜倒在你的石榴裙下～作为九亿少男心中梦，你既有靓丽的外表又有温婉的性格，而同时也不乏幽默细胞。超喜欢你做的年刊上我们班的海报！！会画图会排版的女人帅炸了好吧！！！有幸遇到你，一起奔赴美好的未来"""
from = 33
[anecdote]
embarrassment = "八年级坐第一排正中间，在地理课睡着了，韩老师就把手搭在我肩膀上继续讲课，等我完全清醒过来之后，回头看到最后一排的几个同学笑我笑得停不下来。"
interests = "睡觉"
want = "去住云南的安曼酒店"
[[article]]
content = "肉姐礼仪小课堂"
date = 2021-04-17
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247488418&idx=1&sn=2d1618ec941f226b271f5c45d3a3a9d0"
[[article]]
content = "值日班长黄嘉玉的述职报告"
date = 2021-12-10
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247490997&idx=1&sn=19abbf295bec89318c8c1070a7342c5e"
[[article]]
content = "我以妙笔绘青春——第一届手绘杂志原创大赛"
date = 2021-03-04
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247487140&idx=1&sn=defc6000c7392dfb65d5a4afd7285bf5"
[[article]]
content = "双生同庆，可喜可贺，同年同月同日生的缘分呢，肉姐和傻儿子生日快乐，可可爱爱，期中加油！"
date = 2021-10-27
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247490987&idx=1&sn=360f279f28f3c0a35ab95dde9601023d"
