name_en = "Winnie"
relationship = [
    { with = 10, is = "舔狗" },
    { with = 2, is = "九年老同学" },
    { with = 7, is = "男神" },
]
[[comment]]
from = 34
date = 2022-12-03
description = """黄嘉玉，一个很好看的女生。还会说粤语。为人善良，不会惹是生非。然而，作为一名男生，我可能评价较为片面。她可能课上没什么存在感，比较安静，经常坐在那里头朝下独立思考，但是平时也为我们的班级作出了许多的贡献"""
[[comment]]
from = 35
date = 2022-12-03
description = """你一次听说你是在江某口中，一向成熟稳重的他给了你极高的评价。这不禁让我好奇，你究竟是个怎样的人。初见你时，我便为你所惊艳。你生的极美，一双好看的眸子中透着清冷。我一向眼高于顶，却突然有了种心动的感觉。雨夜，我望着那倾盆的大雨一筹莫展。你的出现似一束光照亮我的心房。八年级，我请求老师将你我调成同桌，只为每天能看着你。自卑如我，只能将这份感情埋藏心底。临近毕业，我们马上各奔东西。我知道，再不说便没机会了。我从不奢求什么，只是毕业前的最后一次疯狂。以上都是ztz真情流露，我的评价是不如宵宫"""
[[comment]]
from = 33
date = 2022-12-03
description = """喜欢你的高马尾，喜欢你的大眼睛，高冷女神的人设不可避免～无数男生都拜倒在你的石榴裙下～作为九亿少男心中梦，你既有靓丽的外表又有温婉的性格，而同时也不乏幽默细胞。超喜欢你做的年刊上我们班的海报！！会画图会排版的女人帅炸了好吧！！！有幸遇到你，一起奔赴美好的未来"""
