introduction = """    在英校恍然一待就是十一年，最有感触的就是初中这几年。
    早上好不容易爬起来，翻山越岭来到学校饭堂，最大的希望一是早餐有好喝的，二是能在饭堂找到同学一起吃。说起来还挺好玩儿的，阿陆每天的去得很早，我和她总是在饭堂门口打照面，说“你这也太晚了”“你也太早了吧”。记得以前在二楼饭堂的时候，经常看到我们班女生已经坐满了一条桌子，跟别人家零零散散的比起来，真的很有一家人的氛围。吃完早餐回教室的路上，我每次路过游泳池旁边的小门都有亿点点期待能碰上肉姐。九年级换了教室以后，每次都在走中间的楼梯和7B9那边的楼梯之间徘徊，感觉选择困难症支配着我的脚，要么是站着不动了，要么是左脚拌右脚两只脚想法不一样，总之最后靠菲姐决定走哪边解救了我。
    早上进班之前得先观察一下班里的气氛，不然不是很庄重的笑声舞到老师面前就得戛然而止一口气上不来下不去了，那确实是挺梗人的。。。上课的时候，听着老师讲课，一边做笔记，一边把快要飘出去的注意力拉回来，想开个小差写作业，又怕老师突然点名，又觉得要尊重老师的劳动成果，到头来还是干脆认真听讲算了。
    上午最后一节课是坚决不接受拖堂的，尤其现在下课时间有所改动，但凡拖个五分钟冲到饭堂排完10分钟的队之后也没什么好吃的了。午饭环节最重要的是要有人同行，三五成群呼朋唤友的才算热闹。另外，如果想吃你某他的螺蛳粉就更得抓紧时间了，不提飞到你某他还有一段距离，光是其他年级的学生们的三早（早下课早动身早占座）优势就让人束手无策了。另诚恳建议大家带上纸巾去。
    下午的体锻真是很要命了，虽然只参加过几次，但是留下的深刻印象是不可磨灭的。到了现在，我总觉着这个天气跑步是一种享受，凉风拂面，暖阳当空，当然了凉凉的空气吸多了实在容易让人感觉肺炸掉了。
    晚上周测的时候，白炽灯（教室里是白炽灯吗）的光打在白纸上，总给我自己要得雪盲症的忧虑。伏案写作（业）的时候，总觉得时间真的一眨眼就过去了，总是会想到电视剧里表示主角长大的手法，镜头从稚气的脸上晃开，晃回来的时候就已经从小孩变成少年了。可能等我们到了年纪，回过神来想想，反而会觉得这样的拍摄手法挺有道理的，日月云中游，不留尘与痕。"""
name_en = "Valery"
nickname = ["周周", "周嘤嘤", "周妈咪", "满满"]
plots = [
    "上完体育课觉得教室太远了",
    "周测教室灯光晃眼",
    "打完早餐假装不经意在餐桌间往返，实则在找同班同学",
    "接水时找人陪同",
    "晚饭在你我他·缤纷汇·饭堂间犹豫",
]
relationship = [{ by = 28, is = "老朋友" }, { by = 7, is = "合作者" }]
reviews = [
    """第一次见到你，就觉得你拥有超越年龄的成熟，及至第一次班级干部竞选，你的竞选演讲条分缕析，对班长的职责做了相当清晰的明确和界定，并且能提出自己就职后的工作计划，这就让我对你更加刮目相看了。果然，你做事井井有条，很有领导风范。记得在元旦节目策划群里，你在每次彩排后的总结都是那么有针对性和可操作性。而且你不只是说说而已，而是真的多才多艺，唱跳俱佳。开放日的《金蛇狂舞》、元旦晚会的《双城记》和《晴天》等，展现了你不同于班级领导人的一面，我在台下不禁为你而喝彩。而最令我感动的是，你竟然把生日票圈的C位留给了我。我们应该可以称得上是真正意义上的亦师亦友了吧。如果说我应该向上苍感谢什么的话，那其中一定有一部分原因，是我认识了你。""",

    """乐观积极、开朗阳光、成熟踏实是大家对你的一致评价。对于为师而言，和你相处，实在感觉你不像学生，更像为师的同事，有着真实可感的超越年龄的成熟。
你淡泊且明志，宁静并内敛，常常能看到你在课室安稳地捧着书本，静静地阅读；你热爱班级，有很强的集体荣誉感；你彬彬有礼，工作认真，作为班长，大家都非常信任你；你有着一股不服输的韧劲儿，谁都不会质疑你将来的优秀。
满满很棒，继续保持就好。""",

    """满满啊，同学们都说你是一位贤者呢，我倒是更觉得你像以为同事。无论做什么，都是淡然如水，从未见过你因为什么事而失态过；无论面对谁，都是真诚大方，从未见过你因为什么人而激动过。一个青春期的初二学生，竟然如此沉稳，再看看已经老大不小的自己，为师着实汗颜。
有你在，所以值日班长制度开了一个好头，后续的各位都学得有模有样；有你在，所以班里大事小情都会有人做主，为师在或不在其实都没什么区别；有你在，所以一班才是一班，这份内心的踏实实在要感谢你。
有你真好啊，满满。""",

    """人不是因为美丽才可爱，而是因为可爱才美丽。你是大家心中的美少女。不仅落落大方，有着出众的领导力，更有着优秀的综合素质。你学习勤奋，任劳任怨地为班集体服务，就像一个懂事的大姐姐，总能想他人所想，急他人所急。更难能可贵的是，你还知晓省吃俭用。举手投足间，你让大家知道了美的内涵。我和你的父母同为有你这样的孩子而骄傲。 """,
]
[anecdote]
embarrassment = "自作多情以为帅哥在跟我说话"
interests = "唱歌"
want = "托福上100"
[[article]]
content = "（上传延迟）母亲节特供——满满的感恩"
date = 2021-05-10
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247489420&idx=1&sn=a7d69b13fefa0265c6db8ec1000f8bf2"
[[article]]
content = "首位值日班长的述职报告"
date = 2021-11-30
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247490990&idx=1&sn=a3881e47d361c95b93787c60cac9b2ec"
[[article]]
content = "我以妙笔绘青春——第一届手绘杂志原创大赛"
date = 2021-03-04
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247487140&idx=1&sn=defc6000c7392dfb65d5a4afd7285bf5"
[[article]]
content = "福气满满，收获满满！ 满满生日快乐！"
date = 2021-11-28
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247490989&idx=1&sn=38220f46f0fbff522d590c4375727f2d"
[[article]]
content = "记忆中的年味 - by 满满"
date = 2021-03-18
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247487388&idx=1&sn=86abe65302a481b440311dd415865ac7"
