nickname = [
    "满满",
    "周妈咪",
    "周周",
    "周嘤嘤",
]
relationship = []
plots = [
    "打完早餐假装不经意在餐桌间往返，实则在找同班同学",
    "接水时找人陪同",
    "上完体育课觉得教室太远了",
    "晚饭在你我他·缤纷汇·饭堂间犹豫",
    "周测教室灯光晃眼",
]
introduction = """    在英校恍然一待就是十一年，最有感触的就是初中这几年。
    早上好不容易爬起来，翻山越岭来到学校饭堂，最大的希望一是早餐有好喝的，二是能在饭堂找到同学一起吃。说起来还挺好玩儿的，阿陆每天的去得很早，我和她总是在饭堂门口打照面，说“你这也太晚了”“你也太早了吧”。记得以前在二楼饭堂的时候，经常看到我们班女生已经坐满了一条桌子，跟别人家零零散散的比起来，真的很有一家人的氛围。吃完早餐回教室的路上，我每次路过游泳池旁边的小门都有亿点点期待能碰上肉姐。九年级换了教室以后，每次都在走中间的楼梯和7B9那边的楼梯之间徘徊，感觉选择困难症支配着我的脚，要么是站着不动了，要么是左脚拌右脚两只脚想法不一样，总之最后靠菲姐决定走哪边解救了我。
    早上进班之前得先观察一下班里的气氛，不然不是很庄重的笑声舞到老师面前就得戛然而止一口气上不来下不去了，那确实是挺梗人的。。。上课的时候，听着老师讲课，一边做笔记，一边把快要飘出去的注意力拉回来，想开个小差写作业，又怕老师突然点名，又觉得要尊重老师的劳动成果，到头来还是干脆认真听讲算了。
    上午最后一节课是坚决不接受拖堂的，尤其现在下课时间有所改动，但凡拖个五分钟冲到饭堂排完10分钟的队之后也没什么好吃的了。午饭环节最重要的是要有人同行，三五成群呼朋唤友的才算热闹。另外，如果想吃你某他的螺蛳粉就更得抓紧时间了，不提飞到你某他还有一段距离，光是其他年级的学生们的三早（早下课早动身早占座）优势就让人束手无策了。另诚恳建议大家带上纸巾去。
    下午的体锻真是很要命了，虽然只参加过几次，但是留下的深刻印象是不可磨灭的。到了现在，我总觉着这个天气跑步是一种享受，凉风拂面，暖阳当空，当然了凉凉的空气吸多了实在容易让人感觉肺炸掉了。
    晚上周测的时候，白炽灯（教室里是白炽灯吗）的光打在白纸上，总给我自己要得雪盲症的忧虑。伏案写作（业）的时候，总觉得时间真的一眨眼就过去了，总是会想到电视剧里表示主角长大的手法，镜头从稚气的脸上晃开，晃回来的时候就已经从小孩变成少年了。可能等我们到了年纪，回过神来想想，反而会觉得这样的拍摄手法挺有道理的，日月云中游，不留尘与痕。"""