name_en = "Lee"
nickname = [
    "Fly",
    "球神",
    "阿杠",
    "飞飞",
    "甲级战犯",
    "银",

    "9B1军区司令（即班长）",
    "世界征服者4海军五星上将兼陆军上将",
    "东部同盟复兴军（计划已失败）军长",
    "东部同盟（已解散）大统领",
    "艾尔迪亚耶格尔派（小丑派）支持者",
    "蒙古海军总司令",
]
plots = ["上课发蒙", "驾驶载人鱼雷击伤猴子"]
relationship = [
    { by = 11, is = "跑友" },
    { by = 13, is = "88世孙" },
    { by = 15, is = "好友" },
    { by = 18, is = "孙子" },
    { by = 7, is = "小丑" },
    { by = 9, is = "好朋友" },
]
reviews = [
    """哈，阿杠，现在提笔给你写评语，脑海里首先浮现的就是你执着地高举右手要回答问题的画面。一开始你的这种积极让我很欣慰，哪位老师不喜欢上课积极回答问题的学生呢？但是后来渐渐发现，阿杠你这名号真是实至名归，至今仍然记得模型比赛前一晚的晚修，你那一句坚定的“不需要”让我一路搬椅子的辛苦失去了意义，也给你自己争取来了一连站满三小时的难忘经历。那一次我记住了你的坚定，即使自己累也绝对不能输了气势。
我以为你会一直那么倔强，这份耿直曾让我暗暗替你唏嘘着急，但是渐渐让我欣喜的是，你其实也可以很暖心:如果不是你的执着追问，我就不会有那么暖心的生日体验；如果不是你的爱心花花，我就不会在生日过去那么久还有幸福的芬芳陪伴；如果不是你的细心观察，我就不会在忍受病痛的时候还有力量坚定继续做老师的信念。你总能给我们带来欢乐，从课间操的视频里欢脱的表演，到研究易经扮演神棍逗大家开心。无厘头的外衣下，你其实有一颗金子般的心。
我的阿杠坦荡磊落，真实地享受着每一天的生活。如果可以送你什么，我要把我最好的祝福都给你，保持原样就好，很高兴认识你！""",

    """每天清晨，我们都会看到一个忙碌的身影，他指挥同学们准备资料，提醒同学们朗读或者默写，这就是我们的语文兼历史课代表。你是大家公认的尽职尽责的典范，关心每个同学的学习；你才思敏捷，为师不过一句玩笑话，你却挥笔立就，写出一篇惊世骇俗的《印度蟑螂觅食记》；你思路清奇，几乎每节课都有你执着发问的身影……虽然你身上也有小缺点，但是瑕不掩瑜，你还是大家最喜欢的杠哥！""",

    """阿杠同学是一个想象力极为丰富，脑洞新奇的好同学，时常能看到他那淳朴厚实的笑脸上，洋溢着灿烂的笑容，发散的思维，搞笑的语言，充斥着课堂的每个角落，给我们留下了深刻的印象，你的活泼机灵为班里带来了生机和欢笑。你平日热爱研究学术，学习成绩也名列前茅。你的人缘也非常好，交游广泛，人称“fly神”，连续多周雄踞“本周榜样”的榜首，德智体美劳全面发展，同学们都评价你为“优秀的社会接班人、信仰坚定的好同志”加油哈，你的青春正绽放出绚丽的光彩。""",

    """杠，你的热情，你的憨厚，你的大方，无时无刻不在感染着你身边的每一个人。你思维活跃，课堂发言积极，常常有出色又独特的见解。你具有较强的集体荣誉感，你总是用你的勤奋来带动其他同学认真学习，只是思路有时方向略有偏差，老师相信，你一定会有更开阔的发展空间。""",

    """勤于思考、有主见、凡事有自己的见解，这是一直以来你留给大家的印象。你凡事有自己的主张，不管遇到什么困难都能坚持自己的想法，稳步地把工作向前推进。专业学习勤奋认真，一个学期以来，进步显著。如果能合理安排课内学习课外学习，真正了解自己的长处短处，知道如何在有限的时间学到更多的东西，发展自己的综合能力，你就更加优秀了！""",
]
[[comment]]
date = 2022-12-06
description = """对同学非常友善，非常热爱帮助同学。在熟人面前非常开朗，在陌生人面前会害羞、有一点社恐。想象力强，总能想出一些天马行空的事情。声称自己经常做预言梦。做事分主次，能够为了目标而奋斗，不轻易放弃。打篮球强，是我们班打篮球最强的。"""
from = 18
[[comment]]
date = 2022-12-06
description = """黎鹏飞，带艺术家，地狱笑话人，一班之神。起初黎鹏飞创造世界。一班是空虚混沌，渊面黑暗。黎鹏飞说要有地狱笑话，于是就有了地狱笑话，然后自己就被钉了在十字架上。"""
from = 31
[[comment]]
date = 2022-12-06
description = """你是一个非常优秀的同学。你尊敬老师，团结同学，你憨厚纯真，聪明机灵。每天都能见到你在课堂积极回答问题，大胆表现自己且能言善道。上课时你听课认真，眼睛里满是渴求知识的目光，所以成绩总是名类前茅。老师们肯定都很喜欢你，对你有很高的期望。你平时很擅长写文章，经常能看到你的长篇大论，有政治人物的高谈阔论，有肝胆相照的侠盗秘籍，乃难的人才也。希望你一如既往的保持你优异的成绩，发挥所长，考出理想的成绩，考入你理想的高中。不断进取，在知识的海洋中扬帆远航！祝福你！"""
from = 19
[anecdote]
embarrassment = "玩英国的时候，登陆法国对战德国却被德国推下海，美国加拿大见死不救，孤军死守到80回合时战败"
interests = "指挥盟军登陆欧洲本土反攻德国或造一大堆海军封锁日本"
want = "三分秒全场"
[[article]]
content = "阿杠的篮球兄弟情"
date = 2021-03-15
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247487148&idx=1&sn=5c0da5f0d9980665bc3b8a5841a61ff4"
[[article]]
content = "我以妙笔绘青春——第一届手绘杂志原创大赛"
date = 2021-03-04
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247487140&idx=1&sn=defc6000c7392dfb65d5a4afd7285bf5"
[[article]]
content = "千日圆满 感动初三"
date = 2023-04-29
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247491100&idx=1&sn=3e48217a9493b07c1218c250cc000cfb"
[[article]]
content = "大单朝钟帅三变法 平杠王皇权稳如山"
date = 2021-07-25
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247490567&idx=1&sn=5fd134138df2210d7c35a0dae71be4d8"
