nickname = [
    "阿杠",
    "球神",
    "飞飞",
    "东部同盟（已解散）大统领",
    "蒙古海军总司令", 
    "世界征服者4海军五星上将兼陆军上将", 
    "东部同盟复兴军（计划已失败）军长", 
    "9B1军区司令（即班长）", 
    "艾尔迪亚耶格尔派（小丑派）支持者",
]
relationship = [
    { with = 13, is = "朋友" },
    { with = 18, is = "朋友" },
    { with = 9, is = "朋友" }
]
plots = [
    "驾驶载人鱼雷击伤猴子",
    "上课发蒙",
]
[[comment]]
from = 18
date = 2022-12-06
description = """对同学非常友善，非常热爱帮助同学。在熟人面前非常开朗，在陌生人面前会害羞、有一点社恐。想象力强，总能想出一些天马行空的事情。声称自己经常做预言梦。做事分主次，能够为了目标而奋斗，不轻易放弃。打篮球强，是我们班打篮球最强的。"""
[[comment]]
from = 31
date = 2022-12-06
description = """黎鹏飞，带艺术家，地狱笑话人，一班之神。起初黎鹏飞创造世界。一班是空虚混沌，渊面黑暗。黎鹏飞说要有地狱笑话，于是就有了地狱笑话，然后自己就被钉了在十字架上。"""
[[comment]]
from = 19
date = 2022-12-06
description = """你是一个非常优秀的同学。你尊敬老师，团结同学，你憨厚纯真，聪明机灵。每天都能见到你在课堂积极回答问题，大胆表现自己且能言善道。上课时你听课认真，眼睛里满是渴求知识的目光，所以成绩总是名类前茅。老师们肯定都很喜欢你，对你有很高的期望。你平时很擅长写文章，经常能看到你的长篇大论，有政治人物的高谈阔论，有肝胆相照的侠盗秘籍，乃难的人才也。希望你一如既往的保持你优异的成绩，发挥所长，考出理想的成绩，考入你理想的高中。不断进取，在知识的海洋中扬帆远航！祝福你！"""