name_en = "Dora"
nickname = ["瑶瑶", "瑶瑶公主"]
plots = ["晚饭后去教学楼外的升旗台阶上背书和看风景"]
reviews = [
    """我和我的瑶瑶公主度过了快乐的一学期，我们可以毫无代沟地嬉笑打闹，还记得运动会上某人因为拍了我的丑照被我追出几条街，还被脱了鞋吗？这学期快乐有之，烦忧也有之。我的瑶瑶公主其实有点小迷糊，对你的印象更多的是课堂上迷离的眼神和摇晃的身影，显得有点疲惫，不由得让人心生怜爱。你总会像一只被吓到的小猫，张着一双惊慌的眼睛过来询问，自己是否会因为学业问题被处罚，你会因为自己的表现而懊恼，也会因为已经过去的事情而焦虑，你会为我的动员誓师而热血沸腾，也会捧着小嘟囔粉丝应援学勋章很珍惜地笑。每每看到你这样，也会在你没有察觉的角落暗暗感受你的喜悲。担心过往不如珍惜当下，其实你已经在进步了，作为语文课代表的你不再迟到，成绩也慢慢有了更好的起色，我愿意等你变得更好，瑶瑶公主最棒，很高兴认识你！""",

    """开学之初，那本原创杂志的配图，着实很配你的气场。平常的你多数时候都是慵懒的，像一只小猫趴在桌上，满脸的享受。而这样懒洋洋的你，成绩也实在让人担忧。你成绩方面的进步空间越来越大，我能在每次你与我的沟通中，感受到你的忐忑。我也了解你的细心和懂事，但是你要明白，活在当下才是对关心你的人的最好报答。如果你可以多笑一笑，课间多和大家沟通，少睡懒觉，大家会更喜欢你。""",

    """你是我们班的瑶瑶公主，一个文静又可爱的女孩儿，像一只慵懒的小猫，你是一个安静的女孩儿，浑身上下都透露着文静的气息，不论班级吵闹与否，你都能保持安静。你在班里堪称是纪律模范，上课时总能看到你犯困的身影，你的画画得也很漂亮，比为师的涂鸦好了不止一星半点，你画画的时候总是很认真，全身心都沉浸在其中。你们是一个很好的孩子，不争不抢，不骄不躁，心中充满善意，温温和和，难忘圣诞假日里，你给我画的小贺卡，用心勾画的图案和涂抹的色彩，都让为师开心到现在，谢谢你，瑶瑶。""",
]
[[article]]
content = "我以妙笔绘青春——第一届手绘杂志原创大赛"
date = 2021-03-04
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247487140&idx=1&sn=defc6000c7392dfb65d5a4afd7285bf5"
[[article]]
content = "瑶瑶公主生日快乐，愿你执着勇敢，一生纯美！"
date = 2021-02-24
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247483678&idx=1&sn=0b590e973ca1f88a71a97b0cdb046033"
