name_en = "Jennifer"
nickname = [
    "佩奇",
]
introduction = """犹记历史没考好的时候被留下背诵历史知识点，对于我这个历史痴来说属实不容易。一直一直拖到窗外的阳光都一点点消失在远方的地平线下，许多与我一同留下的同学都匆匆离开，剩下的人越来越少，我也越来越焦急。直到老师因有约必须离开的时候，我不免狠狠的松了口气。提纲上冗长的知识点让我全部背下简直是酷刑，收拾好书包离开的时候，月光已然降临。我与剩下的同学相约，带着囫囵背在脑中的知识点与散漫的月光一起回家。还记得每一节数学课上每一道让人抓耳挠腮的题目与繁杂的几何图像让人无从下手的感觉，记得我们敬爱的数学老师张婷在黑板上写下的知识点与她站立在讲台的背影。记得噩梦般的爱丽的签筒与抽签回答问题时木签碰撞的声响。也记得掐着点等着上午最后一节课结束一起冲向饭堂的着急，还记得体育课时对每节课增加的跑步圈数所发出的不满的抱怨。很喜欢在8B1的每一个瞬间。"""