introduction = """    犹记历史没考好的时候被留下背诵历史知识点，对于我这个历史痴来说属实不容易。一直一直拖到窗外的阳光都一点点消失在远方的地平线下，许多与我一同留下的同学都匆匆离开，剩下的人越来越少，我也越来越焦急。直到老师因有约必须离开的时候，我不免狠狠的松了口气。提纲上冗长的知识点让我全部背下简直是酷刑，收拾好书包离开的时候，月光已然降临。我与剩下的同学相约，带着囫囵背在脑中的知识点与散漫的月光一起回家。还记得每一节数学课上每一道让人抓耳挠腮的题目与繁杂的几何图像让人无从下手的感觉，记得我们敬爱的数学老师张婷在黑板上写下的知识点与她站立在讲台的背影。记得噩梦般的爱丽的签筒与抽签回答问题时木签碰撞的声响。也记得掐着点等着上午最后一节课结束一起冲向饭堂的着急，还记得体育课时对每节课增加的跑步圈数所发出的不满的抱怨。很喜欢在8B1的每一个瞬间。"""
name_en = "Jennifer"
nickname = ["佩奇", "壮汉"]
reviews = [
    """佩奇啊佩奇，对你我真是又爱又恨。作为为师的黑粉头目，你对为师的点评总是辛辣又犀利。我曾经想过这一小只是不是上天派来收拾我的？你还有恶趣味，爱玩水晶泥，而且偏爱重口味的颜色，导致为师在二班误判，伸手将另一个同学无辜的果冻戳了又戳，从那以后，“单大窘，前后受其敌”就在二班广为传颂。这种相爱相杀一直持续到我生日那天，我收到了你在午夜0：00整，发来微信、贺卡和朋友圈的三重问候，这种细心的小浪漫我已经阔别已久。开放日的表演，你又展现给我不一样的精彩，原来看起来圆圆润润的你跳起舞来可以那么灵动，真是有点小意外呢。就在刚刚，我又收到你微信传来的手绘图画，画面上我们舒服地缩在被窝里，我在认真地给你读绘本，而你看着我，眼睛里满是暖暖的柔波，我想你一定很喜欢我吧，就像我喜欢你一样。好高兴啊，能认识你！""",

    """我家佩奇口才好，不会忘记课间吵架时你顶嘴的伶俐；我家佩奇人缘好，开朗大方，班里几乎所有同学都很喜欢你；我家佩奇正义感极强，每当班里吵闹喧嚣时，这条好汉都会路见不平一声吼；我家佩奇身体好，不会忘记多少个课间朕这九五之尊被你追着打；我家佩奇画画好，无论是上学期的亲子阅读画，还是这学期的人物传记连环画，甚至作业的边角，都会被你随手画上卡通大头画，且生动传传神，大家都叹服不已。你有这么多优点，让大家都很喜欢和你在一起，无论学习还是游戏。
这学期很开心和你在一起。""",

    """白芷香，温瑜美，这大概就是你名字的意义吧，温润而美好，乐观而开朗，你像《小猪佩奇》里的佩奇一样，给人带来快乐，总是咧着嘴角放肆大笑。
你的笑声很有魔力，总是可以让别人跟着你一起笑，同学总是因为你的笑容忘记烦恼。佩奇，谢谢你把快乐都带进课堂，带进我们的生活。
如果仅仅如此，你就不是张芷瑜了，你极其细心，在任何时候都会考虑他人的感受，现在想起你说“班里大家已经很累了”，那一刻我还是满心温暖。
日子一天天过去，对你的印象也随之不断变化，这学期事情很多，你又是个闲不下来的人，这学期语文课代表工作中，你仍可以完成得极为出色。很开心终于选到了这样一个好帮手，谢谢你呀！""",
]
[anecdote]
embarrassment = "无"
interests = "画画、听歌"
want = "做一名服装设计师"
[[article]]
content = "我以妙笔绘青春——第一届手绘杂志原创大赛"
date = 2021-03-04
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247487140&idx=1&sn=defc6000c7392dfb65d5a4afd7285bf5"
