name_en = "Danny"
nickname = ["三木", "共由三木", "林森", "森哥", "森妈", "森森"]
relationship = [
    { by = 13, is = "86世孙" },
    { by = 5, is = "好大儿" },
    { by = 7, is = "指路人" },
]
reviews = [
    """还没见到你的时候，就已经听到太多关于你的赞美，以至于真的看到你时，为师小小地失落了一下“哦，原来就是这个笑眯眯的小胖孩，还行吧，挺可爱的”。
日子一天天过去，对你的印象也随之不断变化。这学期活动超多，你又是个闲不下来的人，很难想象在完成正常任务之外又给自己揽下那么多工作的你，怎么会有那么充沛的精力。开学伊始你带领大家过关斩将，拿下体育训练汇演的一等奖；自编操比赛也同样带着全班夺得了冠军，多才多艺的你现在又登上了开放日和元旦晚会的舞台；艺术细胞有时候会挤占学术空间，但对于你偏偏不是，超级努力的你成绩稳中有升，这一点在这个高手如云的班级是难能可贵的；这学期，你参加了多次演讲比赛、征文比赛，都斩获了极优秀的成绩；你参加了运动会的跳远项目，给我们留下了大鹏展翅的惊艳身影；你在校园模型大赛上全程参与，还让我们了解了你的手工技能；学校布置的德育作业你也积极完成，牛排意面和修好的涂改带还静静躺在我的相册……智体美劳已经全面发展。
如果仅仅如此，你就不是黄森了。你极其细心，现在想起你对我说“今天是大家相遇的一百天”那一刻，我还是满心惊讶。你异常暖心，最不能忘的，是在我生病去医院时，你带全班写给我的那张联名慰问信，以及后来通过监控视频还原的、你的超强领导力所带给我的震撼。你本性淳良，想起你在自己生日时冒着风雨去做志愿者，雨中只为他人撑伞；想起校园模型制作大赛结束后，偶然看到你拿着扫把独自打扫中庭的背影，不用谁要求，一切都只是因为出于本心。那个背影潇洒得像位侠客，却更多一分善良……
历数一幕幕过往，时间也就这样溜走了，于千万年之中，时间的无涯的荒野里，这一百多天只是沧海一粟，很庆幸没有早一步，也没有晚一步，刚巧赶上了，那也确实没有别的话可说，惟有轻轻地道一声：“很荣幸认识你，黄助理。”""",

    """怎么一看到这名字，就想起一张笑嘻嘻的脸呢？
那个寒假好像已经很久远了，有位三木同学帮我筹划过一场“还绿大夫山”的志愿活动，与其说是环保之旅，不如说是夹带私货的春游，采摘野餐捞鱼，三木都乐在其中，活动很成功，多亏有他；“南粤最美少年”的评比好像也是很久之前的事了，细节记不清，记得的只有三木同学的“所获奖项”名目繁多，站在屏幕前一看，那由奖项组成的图形竟然被他填出了一棵凹凸有致的圣诞树；好像还有“学长讲堂”这回事，三木作为风云学长上台演讲，别的都忘了，只记得那句“我们是在为这个社会读书”，听完一愣，忽而又想起他上学期说的“彻夜偷学”和最近的午休状况，猜想也许疏窗细雨，三木又伴夜夜孤灯了吧。
雨中芒果落，灯下草虫鸣，惟笔耕不辍，写下的是此去沿途、漫山层林森森，青山为他举杯，林下一株忘忧。
""",

    """啊呀森哥，你知道吗，竟然有人说，以前一直认为你是一个很难接触的人，匪夷所思呢。你对人总是非常友好，在班里也很受欢迎，你对待任何事都很认真，不管是学习还是班里的一些活动。听他们说，每次聊起你时，大家都会不禁感叹起，这人真是文武双全。
在学习上你用功努力，在哪里都能看见你背书写题，和小自信徜徉于校园的身影；每次出成绩后，又都能听见新晋“凡人”深深的叹息；在体育方面，纵使为师也还没忘记您当年的大鹏展翅，这学期你每次跳绳，成绩都会让人忍不住地感叹“这么快，怕不是要飞起来”？！1000米的跑道上，你也冲在最前头；在舞台上，你也尽情散发魅力，做出如此难的动作，着实让我们羡慕不已……
啊呀呀，一直控制着呢，综评系统不允许为师表达更多对于我大森哥的赞美，先到这吧~ """,

    """如果我们班的每位同学都是夜空的繁星，那么你一定是其中最璀璨的那一颗。办公室里每每聊到你，老师们都不约而同地叫你“那个靠谱小伙儿”，你也确实俨然以为称职助理，默默热心地帮助我，也帮助每一位需要帮助的同学。看着你为班级事务忙碌的身影，看着你优异的成绩，我真为你高兴。森哥，你只会越来越优秀的！""",

    """我家森哥性格开朗，热情活泼，对班级的各项活动永远积极参与，更有着良好的团队精神，与同学们相处极其融洽，因此本学期的“感动初三”森哥将极大提名都收入囊中，实在是实至名归。这三年匆匆而过，从戏谑地夺了你班长的职位又给你助理的头衔，到大夫山抓鱼求助，再到恐龙叫的暗搓搓调侃，都是很让人开心的回忆。就快毕业了，如今的日常即将变成一生回味的过往，很高兴认识你呀！""",
]
[[comment]]
date = 2022-12-03
description = """黄森，是我们班上的老好人，他和谁都合得来，因为他情商高。
他学习好，作文从未下40，他体育强，跳绳跳远拿过奖，他有一个很强的能力是我一直未具有的，那就是组织力。集中力量办大事，看起来很简单，实际上很难，要考虑群体意见，还要有领导力震住众人。而在每次班级大事时都有他组织，且组织得很好。
他有梦想，他的梦想是从事生物科技，研发医药，这是一个漫长、艰苦但伟大的梦想，但他一直坚持。每次晚修他都会拿出自己的高中生物套题自学，这种为梦想不懈奋斗的精神十分让我钦佩。"""
from = 25
[[comment]]
date = 2022-12-06
description = """森哥，你是我们班的风向标。学习优异的人有你，多才多艺的人里有你，和同学相处融洽有你，老师的得力助手有你，家长口里的好孩子更是你。班级所有的表扬都少不了你的一份。你是一个品学兼优的好孩子。你那双珍珠般的眼睛里，盛满热情聪慧，上课时，你思维敏捷，积极发言，那独到的见解令人敬佩。友好的谈吐，优美的文笔，全面发展，令老师赞叹，同学们羡慕。运动场上也有你为班级拼搏的身影，文艺晚会的班级节目中你每次都是主角。你一直不懈努力和追求，希望你继续施展你的才干，越来越出色。期待你早日实现自己的人生理想。"""
from = 19
[[comment]]
date = 2022-12-07
description = """黄森，可以说是我们班的“地头蛇”，有组织，有纪律，有实力。我们班的大活动，运动会，元旦晚会，都有他的助力。台前，他是主角演员，幕后，他是组织老大。他是我们班的班主任助理，是老师们的得力助手。老师一有任务，第一想到的是课代表或钟彦慷或他，其次才是其他同学。他成绩也很好，作文很强力，写植物，煽情，就这看着简单的技巧却能助力他作文分数长期上40。"""
from = 14
[anecdote]
embarrassment = "参加模联，被一个阿姨误认为是服务员"
interests = "看小说，思考人生，深夜emo"
want = "做一次梦，在梦里体验各种各样的极限运动"
[[article]]
content = "值日班长黄森的述职报告"
date = 2021-12-06
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247490994&idx=1&sn=ca47822c653921aa4df2d203c46a2c8d"
[[article]]
content = "我以妙笔绘青春——第一届手绘杂志原创大赛"
date = 2021-03-04
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247487140&idx=1&sn=defc6000c7392dfb65d5a4afd7285bf5"
[[article]]
content = "最美好的样子你都有 风云学长 三木同学生日快乐！"
date = 2021-11-15
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247490988&idx=1&sn=6887b038cb3a93a4d551026c0e0c40ba"
[[article]]
content = "千日圆满 感动初三"
date = 2023-04-29
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247491100&idx=1&sn=3e48217a9493b07c1218c250cc000cfb"
[[article]]
content = "大单朝钟帅三变法 平杠王皇权稳如山"
date = 2021-07-25
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247490567&idx=1&sn=5fd134138df2210d7c35a0dae71be4d8"
[[article]]
content = "这样的人让我敬佩 - by 单高祖"
date = 2021-04-20
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247488912&idx=1&sn=8e89b6bceef333842a419803fbce01cc"
[[article]]
content = "记忆中的年味 - by 黄森"
date = 2021-03-23
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247487454&idx=1&sn=314270dc312918cf97eb7956d3025ec4"
