name_en = "Danny"
nickname = ["森妈", "共由三木", "森哥", "森森", "三木", "林森"]
relationship = [
    { with = 22, is = "儿子" },
    { with = 5, is = "女儿" },
    { with = 4, is = "革命盟友" },
    { with = 24, is = "老朋友" },
]
[[comment]]
from = 25
date = 2022-12-03
description = """黄森，是我们班上的老好人，他和谁都合得来，因为他情商高。
他学习好，作文从未下40，他体育强，跳绳跳远拿过奖，他有一个很强的能力是我一直未具有的，那就是组织力。集中力量办大事，看起来很简单，实际上很难，要考虑群体意见，还要有领导力震住众人。而在每次班级大事时都有他组织，且组织得很好。
他有梦想，他的梦想是从事生物科技，研发医药，这是一个漫长、艰苦但伟大的梦想，但他一直坚持。每次晚修他都会拿出自己的高中生物套题自学，这种为梦想不懈奋斗的精神十分让我钦佩。"""
[[comment]]
from = 19
date = 2022-12-06
description = """森哥，你是我们班的风向标。学习优异的人有你，多才多艺的人里有你，和同学相处融洽有你，老师的得力助手有你，家长口里的好孩子更是你。班级所有的表扬都少不了你的一份。你是一个品学兼优的好孩子。你那双珍珠般的眼睛里，盛满热情聪慧，上课时，你思维敏捷，积极发言，那独到的见解令人敬佩。友好的谈吐，优美的文笔，全面发展，令老师赞叹，同学们羡慕。运动场上也有你为班级拼搏的身影，文艺晚会的班级节目中你每次都是主角。你一直不懈努力和追求，希望你继续施展你的才干，越来越出色。期待你早日实现自己的人生理想。"""
[[comment]]
from = 14
date = 2022-12-07
description = """黄森，可以说是我们班的“地头蛇”，有组织，有纪律，有实力。我们班的大活动，运动会，元旦晚会，都有他的助力。台前，他是主角演员，幕后，他是组织老大。他是我们班的班主任助理，是老师们的得力助手。老师一有任务，第一想到的是课代表或钟彦慷或他，其次才是其他同学。他成绩也很好，作文很强力，写植物，煽情，就这看着简单的技巧却能助力他作文分数长期上40。"""
