name_en = "Serena"
nickname = ["罗心蕊", "罗阿姨", "sta"]
plots = ["与波波抢厕所，还抢不过", "体育课后挤在厕所擦防晒", "厕所小惊喜", "往天花板上扔纸巾球"]
relationship = [{ by = 10, is = "n年老友" }, { by = 19, is = "好盆友" }]
reviews = [
    """一开始对你的印象，是你的眼睛会笑。开学初的班干部竞选演讲上，你罗列的一系列奖项让我们闻之而倾倒，不禁赞叹你的才貌双全，也对你的舞姿充满期待。果然，在开放日的排练和表演过程中，你临危受命，凭着超强的执行力和学习力，让我们班的节目大放异彩。更让我惊艳的是元旦晚会的舞蹈，真的看不出平时乖乖静静的你，跳起舞来会有那么强大的力量感，为师一瞬间就被你的气场降服了。
本来如此优秀，可能会有相应的骄傲，但你偏偏又机灵搞怪，丝毫没有盛气凌人的睥睨感。不单单是舞蹈方面，运动上你也丝毫不肯逊色于他人。而成绩方面，其实也还算让人满意，毕竟在这个班级，强者如云，能保持稳定就已经很不错。坚持做自己就很好了，如果可以，学习上再认真那么一丢丢，我们就会更喜欢你哦！很高兴认识你！""",

    """至今难忘元旦联欢会上你火辣的舞蹈，很难想象你瘦弱的身体竟然可以迸发出如此强大的气场，着实让我们欣羡不已。细细回想大家的惊讶，也不无道理。学期伊始的你还略显慵懒，因为成绩优势不明显，你被老师们提醒过的次数，像雨天的涟漪一样多，但好在你懂得及时补救，成绩也随着学习状态的起落而涨跌。你的字迹很工整。性格也开朗大方，关心同学，还很善于交往。学习方面如果可以再加把劲儿，你就会是最优秀的女生了。""",

    """罗大妈性格开朗大方，语言温柔，给大家都留下了深刻印象，一头乌黑的头发如乌云扰扰，尽态极妍。你很无坡，在课余时间里会和其他同学一起玩耍打闹，在跳舞方面也有很大的天赋，在元旦晚会演出的排练室，因为我们展现了优美的舞姿，作为一班中不可或缺的一员，你尽职尽责，为班级荣誉做出了巨大的贡献，要是你能在学习上更加认真一点，更努力一点，就会变得更加优秀，很开心遇到你，谢谢你为我们带来这么多快乐。""",

    """在端午节汉服节的活动中，我惊讶又自豪地看到你翩然的舞姿，骄傲地对同事说：“看！那个，那个女孩是我的学生！”我欣喜地发现你正在蜕变。那个腼腆内秀的小女孩不见了，一个更加自信的你向大家走来。你求知上进，热烈讨论；你常带笑容，开朗乐观。炎热而漫长的假日，要坚持练舞练笔哟！""",

    """在为师的心中，你一直是一个才华横溢的小女孩，舞姿热辣，之前历届元旦晚会上你的精彩表演给大家留下了深刻的印象；你同时又是一个关心同学，热爱集体的好学生，这学期的很多事，比如速干服的尺码统计和发放，都有赖于你的帮助;你对工作兢兢业业，学习抓得比较紧，但也许是对节奏不适应的原因，总体成绩仍有提升空间，千万要及时调整心态哦。""",
]
[[comment]]
date = 2022-12-03
description = """你是一个活泼开朗的女生，你在舞台上能自信地展现自己。作为音乐课代表，你带领着我们班的人参加的节目都很不错。你在初中三年里，组织能力越来越强，而且舞蹈也跳得越来越好。你幽默可爱，女生都很喜欢和你一起玩。你在初中成长，你开始学会自己控制自己，逼自己刷题等等。希望你以后少向我问一个问题，那就是你xx写了吗"""
from = 10
[[comment]]
date = 2022-12-03
description = """罗心懿一班之黑马，在这三年里，时不时就能看见她复习的背影，与周围形成了鲜明对比。在课外，又有钢琴和舞蹈等绝技，每逢音乐课，总能让人眼前一亮，叹为观止。在交友，人脉广，关系好。真，六边形战士"""
from = 15
[[comment]]
date = 2022-12-03
description = """第一印象就是一个跳舞很厉害的女生啊，每次看到你上台表演都会被狠狠惊艳到。在一起相处久了，就会发现你特别爱笑，那具有感染力的笑容和笑声也经常给同学们带来欢乐。在为元旦晚会做准备的时候就能看出你很有责任心，也有很强的组织能力，在节目编排设计上尽心尽力。在学习上也能看到你的不懈努力，不时就能看到你找其他同学请教。很高兴能认识你呀！"""
from = 23
[anecdote]
embarrassment = "把别人认成朋友，说了一堆尴尬的事情"
interests = "跳舞、追星"
want = "和朋友一起去环游世界"
[[article]]
content = "罗阿姨的佳片推荐——《Hi, Mom》"
date = 2021-05-13
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247489421&idx=1&sn=955b46a8d1346187a55a5a820845d864"
[[article]]
content = "值日班长罗心懿的述职报告"
date = 2021-12-24
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247491004&idx=1&sn=45ed98f272cd3a5cbe5f52762535c9a6"
[[article]]
content = "我以妙笔绘青春——第一届手绘杂志原创大赛"
date = 2021-03-04
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247487140&idx=1&sn=defc6000c7392dfb65d5a4afd7285bf5"
[[article]]
content = "千日圆满 感动初三"
date = 2023-04-29
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247491100&idx=1&sn=3e48217a9493b07c1218c250cc000cfb"
