name_en = "Serena"
nickname = [
    "罗阿姨",
    "罗心蕊",
]
relationship = [
    { with = 10, is = "n年老友" },
    { with = 1, is = "好盆友" },
    { with = 19, is = "好friend" },
    { with = 20, is = "好朋友" }
]
plots = [
    "厕所小惊喜",
    "与波波抢厕所，还抢不过",
    "往天花板上扔纸巾球",
    "体育课后挤在厕所擦防晒",
]
[[comment]]
from = 10
date = 2022-12-03
description = """你是一个活泼开朗的女生，你在舞台上能自信地展现自己。作为音乐课代表，你带领着我们班的人参加的节目都很不错。你在初中三年里，组织能力越来越强，而且舞蹈也跳得越来越好。你幽默可爱，女生都很喜欢和你一起玩。你在初中成长，你开始学会自己控制自己，逼自己刷题等等。希望你以后少向我问一个问题，那就是你xx写了吗"""
[[comment]]
from = 15
date = 2022-12-03
description = """罗心懿一班之黑马，在这三年里，时不时就能看见她复习的背影，与周围形成了鲜明对比。在课外，又有钢琴和舞蹈等绝技，每逢音乐课，总能让人眼前一亮，叹为观止。在交友，人脉广，关系好。真，六边形战士"""
[[comment]]
from = 23
date = 2022-12-03
description = """第一印象就是一个跳舞很厉害的女生啊，每次看到你上台表演都会被狠狠惊艳到。在一起相处久了，就会发现你特别爱笑，那具有感染力的笑容和笑声也经常给同学们带来欢乐。在为元旦晚会做准备的时候就能看出你很有责任心，也有很强的组织能力，在节目编排设计上尽心尽力。在学习上也能看到你的不懈努力，不时就能看到你找其他同学请教。很高兴能认识你呀！"""