name_en = "Jimmy"
nickname = ["狗狗", "奶狗", "小神童"]
[[comment]]
from = 25
date = 2022-12-03
description = """刘佳庚者，强也。身体强壮，也爱好踢球、打球，但是非常脏。是老师眼里的明星，好借人之物，大部分借的时候都如探取物。
事件，曾在班中曝光诸多信息，如周某的桃色新闻，吾等不知真假。此外，其曾在墙上喷涂黑料，拭之不妥，遭处分等。
成绩好，常位列前20名。
其有一车，不及其一人之高，小巧玲珑，赶于校中转。佳庚曾驾驶其车，如鱼雪贯之于一人，其人怒，且训佳庚，使佳庚少骑于路上。
其今在澳洲，吃大龙虫下不带吾等，不义也。"""
