name_en = "Jimmy"
nickname = ["奶狗", "小神童", "狗狗", "乙级战犯"]
relationship = [{ by = 34, is = "儿子" }, { by = 35, is = "儿子" }]
reviews = [
    """奶萌呀，我该给你怎样的评价？这学期我们算是不打不相识吧。对于你，除去足球赛时，你在绿茵场上的潇洒身影外，印象最深的还是你作为班级“三杠”的江湖地位了。浓眉大眼可可爱爱的长相和你粗犷豪放的嗓音有那么一丢丢不搭，你偏偏又每天仰着这样人畜无害的娃娃脸到处惹祸捣蛋，多少次接到同学和老师们的抱怨和投诉，你这样那样又去撩嫌，我也曾因你而恼火，毕竟推同学进别班、藏同学书包让人家着急等等，不是很讲武德……但是好在，我最终耐住性子等你长大，也好在，你给了我与你和解的机会。
其实你也有很多可爱之处，比如热心参与体育运动，比如认真完成为师布置给你的关于磨牙棒的任务，又比如积极参与捐衣送暖的志愿者活动中……不知道下学期又会和你有怎样的精彩。少侠，很高兴认识你，请多指教！""",

    """如果可以的话，我们仍然希望选你作我们班的吉祥物，因为你长得真的好可爱，浓眉大眼萌萌哒，眼里透着机灵的光，果然，你对人对事都会有自己的见解，时常提出自己的看法。有时也会闯些小祸，但你自己知道及时改正。你成绩不错，人缘也不错，在课堂上能积极回答问题，不过学习方面可以再努力一些。你有着极高的运动天赋，日益黝黑的皮肤就是最好的证明，至今仍然难忘足球比赛时，你为班级荣誉而战的身影，更期待下学期校运动会上你的精彩表现，加油哈！""",

    """你啊你，软软的，脸上泛着红晕，两只大大的眼睛，犹如泛着光泽的宝石一般，又如清泉明亮澄澈，睫毛纤细而浓密，声音也软软糯糯的，你一笑，仿佛全世界都要融化。
随着时间的增长，你愈发活跃在大家的视线里，你是操场上跑去踢球的体育委员，是课堂上积极发言的抬杠选手，是课下打闹的冠军。你性子调皮，甚至常常惹祸，可你的成绩又总是名列前茅，而且总是给大家带来惊喜和快乐，活跃着沉闷的课堂，足球比赛时，你为了班级的比分奋力奔跑的样子真让人感动，小小身体里藏着巨大的能量。
“庚”在《新华字典》第157页中，是年龄的意思，佳庚佳庚，美好的年纪，美好的少年，希望你可以带着心中的光一直向前，胸中有丘壑，立马振山河，在浪漫的青春中，变成自己想要的模样。""",

    """你是一个非常聪明但又很调皮的男孩。你思维活跃，善于思考，表达能力很强。课堂上常常能看见你高举的双手，那一口响亮而又悠长的普通话更让人印象深刻。作业本上那独具特色的字体让同学们很是佩服。学习上你如果可以再很努力一些，肯定能取得更大进步！""",
]
[[comment]]
date = 2022-12-03
description = """刘佳庚者，强也。身体强壮，也爱好踢球、打球，但是非常脏。是老师眼里的明星，好借人之物，大部分借的时候都如探取物。
事件，曾在班中曝光诸多信息，如周某的桃色新闻，吾等不知真假。此外，其曾在墙上喷涂黑料，拭之不妥，遭处分等。
成绩好，常位列前20名。
其有一车，不及其一人之高，小巧玲珑，赶于校中转。佳庚曾驾驶其车，如鱼雪贯之于一人，其人怒，且训佳庚，使佳庚少骑于路上。
其今在澳洲，吃大龙虫下不带吾等，不义也。"""
from = 25
[[article]]
content = "足球先生奶萌的独到见解"
date = 2021-03-09
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247487143&idx=1&sn=184dea87181aaab088fd03b98ac360b9"
[[article]]
content = "值日班长刘佳庚的述职报告"
date = 2021-12-13
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247490999&idx=1&sn=bd95073b05f9916d4634b2c6e6d1dfdf"
[[article]]
content = "我以妙笔绘青春——第一届手绘杂志原创大赛"
date = 2021-03-04
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247487140&idx=1&sn=defc6000c7392dfb65d5a4afd7285bf5"
