name_en = "Yabbie"
nickname = ["Yabbie", "papa", "绿箩妈妈", "老曾"]
relationship = [{ by = 33, is = "八世孙" }, { by = 5, is = "傻儿子" }]
reviews = [
    """哈，老曾！你真是个沉稳安静的女孩，你似乎总是在学习，无论什么时候。这曾让我有点为你担心，因为要知道凡事过犹不及，太过专注于学习，会错过一些享受生活的乐趣。如果可以，我希望你能参与到同学们课间的打闹和嬉笑中去，所以我尽力带着你一起嗨。还记得我硬拉着你拍合影，你却宁死不屈吗？那时候看着你，我忽然想起徐志摩的诗：最是那一低头的温柔，像一朵水莲花不胜凉风的娇羞，娇羞中，又有蜜甜的忧愁……
后来慢慢了解了你，我也慢慢放下了心来。你在学习之外，其实也积攒了一些人脉，那次见你在别班门口笑着等待小姐妹，我也很开心你有了更多的朋友。这学期你为班级设计并绘制了展板和墙报，又为我们带来了那么美的班牌。好开心遇到如此乖巧可爱的你，接下来还要一起精彩哦！""",

    """无意间听到“老曾”这个昵称，觉得和你真的很搭。你文静内敛，言语温柔，在班里话虽不多，最喜欢安然地坐在座位上静静刷题，很有点与世无争的感觉，但是你身上却腾腾透着一股杀气。
还记得除夕之夜，你可爱的妈妈向我倾诉：你认真学习甚至已经到了“六亲不认”的地步，着实让我倍感震惊，读罢你的《写在期末》，才明白你内心的刚毅。
后生可畏，老曾，你这一学年的拼搏和成绩，让我们知道了努力真的有回报。
谢谢你！""",

    """曾铉雅同学给人的印象也是两个字：沉稳。沉稳的表情、沉稳的步伐、沉稳的举止、沉稳的气质，你像一位看破红尘、岿然不动的高人，如老僧入定，每当周围的同学们都在嬉戏打闹时，你却丝毫不受影响，独自在刻苦刷题。你总是位列年级前十的队伍之中，每次领奖都能看见你的身影，从未缺席。
对于你，全班同学都敬佩不已，不只是仰慕你良好的道德品质，也因为你无论取得多好的成绩，你都从未骄傲自满，还会谦虚地来一句，这次发挥的不好，下次继续努力，优秀而不骄傲，沉稳并保持进步。除了优秀，真找不出更合适的词儿来形容你了，你真是一个有趣的人，很高兴认识你。
""",

    """想告诉你——在老师心中，你是一个文静灵秀的女孩；想感谢你——总是默默无闻地为班级做贡献；想对你说——愿你在知识的海洋中不息的奋斗，执着的追求；想提醒你——任何一种容器都装得满，惟有知识的容器大无边，“以有涯追无涯，殆矣”。要记得张弛有度哦。希望你快乐学习每一天！""",

    """父母眼里你是乖巧、懂事的好孩子，同学的眼中你是助人为乐、成绩优异、关心集体的同学，老师眼里你是善解人意、思维敏捷的好学生。你团结同学，待人有礼貌，诚恳。为师布置的事情，你能默默地记在心里，积极去做，从来不用为师操心。只是为师希望你今后能大胆发言，更加开朗，老师想，如果你能主动回答问题，那么你将更加出色，更加完美!""",
]
[[comment]]
date = 2022-12-03
description = """看到老曾的第一眼就知道她是一个可爱的女孩子呀！呆萌的眼神，厚厚的刘海是她的专属标志。熟络后就会发现她是个漫威影迷，她特别喜欢那些超级英雄。一旦提起就能说个不停，给你介绍她喜欢的角色。不知何时她承担起给班里的绿植浇水的任务，被我们称为绿萝妈妈，她每天记得给孩子们浇水，网课时也担心着它们的安危。老曾在学习上经常帮助我，她也是我在学校的一大快乐源泉，很高兴能和她成为朋友"""
from = 23
[[comment]]
date = 2022-12-06
description = """曾铉雅也是我在这个班里认识很久的人之一，虽然很早之前就认识，但还是不是很熟（聊的太少了qwq）。她在老师面前就是一个标杆，因为她的确特别努力，所以成绩也自然而然地很优秀。她虽然话少但是真的很可爱！"""
from = 1
[[comment]]
date = 2022-12-06
description = """初一认为她是一个沉默寡言（？难以接触的学霸，都后面荣幸的当了几次同桌发现十分幽默有趣。学习的时候非常认真，稳扎稳打，别人家的孩子呜呜呜爱了爱了。是一个腼腆的女孩呀，和熟的人就玩得来。Yabe的幽默不是那种幽默，而是不经意间制造出来的幽默。"""
from = 29
[anecdote]
embarrassment = "无"
interests = "看电影、旅游、听音乐、玩"
want = "去奥兰多的迪士尼和环球影城看电影，玩"
[[article]]
content = "值日班长曾铉雅的述职报告"
date = 2021-12-19
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247491001&idx=1&sn=d96a643f503be97011832223deacdf9d"
[[article]]
content = "我以妙笔绘青春——第一届手绘杂志原创大赛"
date = 2021-03-04
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247487140&idx=1&sn=defc6000c7392dfb65d5a4afd7285bf5"
[[article]]
content = "老曾生日快乐，愿你有张有弛，开心快乐每一天"
date = 2021-03-17
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247487328&idx=1&sn=28bae4e719666f97f1c6d2d1d9a12bbd"
[[article]]
content = "千日圆满 感动初三"
date = 2023-04-29
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247491100&idx=1&sn=3e48217a9493b07c1218c250cc000cfb"
