nickname = [
    "papa",
    "Yabbie",
    "绿箩妈妈",
    "老曾",
]
relationship = [
    { with = 23, is = "儿子" },
    { with = 5, is = "儿子" }
]
[[comment]]
from = 23
date = 2022-12-03
description = """看到老曾的第一眼就知道她是一个可爱的女孩子呀！呆萌的眼神，厚厚的刘海是她的专属标志。熟络后就会发现她是个漫威影迷，她特别喜欢那些超级英雄。一旦提起就能说个不停，给你介绍她喜欢的角色。不知何时她承担起给班里的绿植浇水的任务，被我们称为绿萝妈妈，她每天记得给孩子们浇水，网课时也担心着它们的安危。老曾在学习上经常帮助我，她也是我在学校的一大快乐源泉，很高兴能和她成为朋友"""
[[comment]]
from = 1
date = 2022-12-06
description = """曾铉雅也是我在这个班里认识很久的人之一，虽然很早之前就认识，但还是不是很熟（聊的太少了qwq）。她在老师面前就是一个标杆，因为她的确特别努力，所以成绩也自然而然地很优秀(๑•̀ㅂ•́)و✧。她虽然话少但是真的很可爱！"""
[[comment]]
from = 29
date = 2022-12-06
description = """初一认为她是一个沉默寡言（？难以接触的学霸，都后面荣幸的当了几次同桌发现十分幽默有趣。学习的时候非常认真，稳扎稳打，别人家的孩子呜呜呜爱了爱了。是一个腼腆的女孩呀，和熟的人就玩得来。Yabe的幽默不是那种幽默，而是不经意间制造出来的幽默。"""