name_en = "John"
nickname = ["江哥", "脏狗", "题之恶魔"]
plots = [
    "写不完作业",
    "宿舍有各种虫子",
    "晚修后洗澡违规但因为体锻而迫不得已",
    "有的住宿生素质有待提高，半夜大喊大叫",
    "洗好的衣服总是分错房间，衣服上还会有纸巾屑",
    "餐厅卫生糟",
]
relationship = [
    { by = 16, is = "语法修正器" },
    { by = 18, is = "孙子" },
    { by = 9, is = "好朋友" },
]
reviews = [
    """对于你，初见的印象更多的是沉稳二字:沉稳的表情、沉稳的举止、沉稳的步伐，连握笔姿势都是沉稳地用手护住笔杆，如此与众不同，成绩更是一路稳到最后，创造了属于自己的高分神话。我一直以为你是个看破世间乱象、我自岿然不动的高手，如老僧入定，不理会尘世烦忧，直到第一次团建，同学们说我不了解你，我才打开了新世界的大门。朗诵起东坡豪放的《江城子》，你会很认真地展现你的气魄；运动会上面对偷拍者悄悄探出的镜头，你会很勇敢地直面被偷拍的恐惧；开放日化妆的时候，即使被为师化成艺伎也没有丝毫怨言；元旦晚会排练的间隙，你还会和同学们切磋武艺；搞笑的是，综合通技课的期末作业，你竟然交了一只肥皂雕刻的抽水马桶，细节控的你还将其特意处理成没有冲洗的状态……稳而不僵，强而不躁，让人不禁感叹不是谁都有命生江哥这样的儿子。你是个有趣的人，很高兴认识你！""",

    """江哥真是深藏不露，之前一直以为您是呆呆的学霸，也许不会轻易听到您的声音，这学期却不断看到您不同的另一面：开学之初的原创杂志上，您的直男设计就让人印象深刻，这学期的英语课堂上，也见识到了您的实力；尤其刷新印象的是，您在期末团建时写下的小故事，思路清晰，卓尔不群：为了保护同学生命健康，您带领众好汉奋不顾身吃掉所有水煮肉片，实乃吾辈之楷模；江哥平易近人，无论哪位同学有困难找到你，你都绝无二话进行帮助；江哥还很爱笑，常常会在课室里看到江哥绽放的笑容……
江哥的优点数不胜数，继续保持就好，您老人家好优秀！""",

    """当年初次见面，就发现你有着与年龄不相称的沉稳，相当于一群喧闹的人群之中，只有你向江心的石头沉默着，又像五光十色之中沉淀下来的精华，直到上个学期的期末，大家才发现，你还有着反差极大的另一面，你会为了同学的一次玩笑而动怒，也有时会在人前做出一些超出我们认知范围的举动，让大家知道了你并不是高冷之人。
你的成绩极好，尤其是英语，几乎每一次上课我们都会为你倾倒，你的理科也并不差，所以你的成绩让许多人望尘莫及。希望我们大江哥在下个学期中，可以更加进步，天天向上！""",

    """你总是默默无语地认真学习，即使遇到了挫折也毫不气馁，沉静之中带着几分倔犟，淳朴之中透着踏实。你是一个内心世界丰富，但不爱表达的男孩，你有思想、聪明。在班里你团结同学，劳动踏实，有集体荣誉感。在学习上你能认真听老师上课，作业能按时完成。老师记住了你的优点。老师希望你在学习上再刻苦些，相信你一定能做好。每次打开作业都能欣赏到你清楚的字迹。虽然这学期妈妈生病了，家人关心你的时间也没以前多了，但你各方面反而更自觉懂事了。加油，我始终对你充满信心。""",

    """江哥上课听讲总是那么认真，课后学习也是一样，很有上进心。你的刻苦学习的精神各科老师都很欣赏，你也是把“沉稳”（至少是老师面前）从初一贯穿到初三的少数几个同学之一。算算时间，这三年就快过完了，我们相信，你一定能在初三的最后半学期里，保持优势，最后考入自己理想的重点高中，江哥没错的！""",
]
[[comment]]
date = 2022-12-03
description = """你是一个比较安静的同学，虽然说在初三已经自暴自弃这个形象了。从刚入学的那天起，我们便感受到了你的高冷。好像除了在那么一两个男生面前，你一直都将自己包起来。感觉你总是在学习，现在还记得万圣节我吃东西你做题，被老师嘲笑了。其实之前听说你在小学骚操作挺多的，however，这些在初中好像没被看见（除了漏腿毛）哈哈。希望你以后能大胆将自己的样子展现给身边的朋友，越来越好。"""
from = 10
[[comment]]
date = 2022-12-03
description = """“低调奢华”，你在我们班简直就是一个神奇人物般的存在。常见你端正地坐在书桌前，一笔一划地写下几乎全对的标准作业。八年级英语课上，你是我们扛分而拖时间的完美代言人，只要你一开口论理，老师都要紧张三分。记得我们宿舍里一起度过的玩闹时光：你坐在床上大讲特讲哲学道理；各种各样的梗层出不穷，就连我上个厕所都能被扯上“鲤鱼跃龙门”；貌似我总是那个被整的人，睡觉时袜子总是“自己跑去了”某些意想不到的地方；出去接杯水，一回来却发现枕头失踪了；据说你们还常趁我不在对某些人实施“例行检查”。话说当年寻宝游戏中被疯狂糊弄的感觉，至今想来还是饶有趣味的。三年来我们一起成长，我也见证了一个不断成熟的你。希望我们这份友谊可以永存，不随时光而褪色。"""
from = 7
[[comment]]
date = 2022-12-03
description = """江浩哲，人称江哥。在初一时，他十分安静，让人觉得他是那种内向的人。然而，当有了共同话题后，会发现他是一个十分开朗的的人。他喜欢高达，看过很多高达。我在以前一直以为他不打游戏，事实上他也玩，但他玩得很少，至少在我看来是这样的。
事件：曾和我在电脑上联机玩泰拉瑞亚，他开局挂了多次导致我们的出生点变成墓地，整整一个晚上全是怪。
他学习很好，他能在浮躁的环境中静下心来，我敢说这种毅力绝对不是大多数人所拥有的。他有梦想吗？我并不知道，但我觉得了他一定有说不定是个远大的梦想。
他也喜欢看动漫，拉我入坑《电锯人》。《电锯人》是纯爱超甜后宫番，玛奇玛善良温柔是群剧中的好女人。"""
from = 25
[anecdote]
embarrassment = "小时候跟妈妈去书店看书，后来去找她的时候认错人了，对一个陌生的大姐姐喊“妈妈”"
interests = "追番、听歌、睡觉"
want = "活下去"
[[article]]
content = "眼见为实——江哥基于柏拉图洞穴理论的感悟"
date = 2021-05-17
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247489422&idx=1&sn=4efea62f4be641723387b7f0a5cc39cb"
[[article]]
content = "我以妙笔绘青春——第一届手绘杂志原创大赛"
date = 2021-03-04
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247487140&idx=1&sn=defc6000c7392dfb65d5a4afd7285bf5"
[[article]]
content = "江哥生日快乐！前程锦绣，率性帅型。请收下为师迟到五天的祝福"
date = 2021-10-15
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247490650&idx=1&sn=d3b2e330fb30560a18ea6ebb81ea67e2"
