nickname = [
    "江哥",
    "脏狗",
    "题之恶魔",
]
relationship = [
    { with = 9, is = "兄弟" },
    { with = 34, is = "兄弟、损友" },
    { with = 18, is = "儿子" }
]
plots = [
    "餐厅卫生糟",
    "写不完作业",
    "晚修后洗澡违规但因为体锻而迫不得已",
    "洗好的衣服总是分错房间，衣服上还会有纸巾屑",
    "宿舍有各种虫子",
    "有的住宿生素质有待提高，半夜大喊大叫",
]
[[comment]]
from = 10
date = 2022-12-03
description = """你是一个比较安静的同学，虽然说在初三已经自暴自弃这个形象了。从刚入学的那天起，我们便感受到了你的高冷。好像除了在那么一两个男生面前，你一直都将自己包起来。感觉你总是在学习，现在还记得万圣节我吃东西你做题，被老师嘲笑了。其实之前听说你在小学骚操作挺多的，however，这些在初中好像没被看见（除了漏腿毛）哈哈。希望你以后能大胆将自己的样子展现给身边的朋友，越来越好。"""
[[comment]]
from = 7
date = 2022-12-03
description = """“低调奢华”，你在我们班简直就是一个神奇人物般的存在。常见你端正地坐在书桌前，一笔一划地写下几乎全对的标准作业。八年级英语课上，你是我们扛分而拖时间的完美代言人，只要你一开口论理，老师都要紧张三分。记得我们宿舍里一起度过的玩闹时光：你坐在床上大讲特讲哲学道理；各种各样的梗层出不穷，就连我上个厕所都能被扯上“鲤鱼跃龙门”；貌似我总是那个被整的人，睡觉时袜子总是“自己跑去了”某些意想不到的地方；出去接杯水，一回来却发现枕头失踪了；据说你们还常趁我不在对某些人实施“例行检查”。话说当年寻宝游戏中被疯狂糊弄的感觉，至今想来还是饶有趣味的。三年来我们一起成长，我也见证了一个不断成熟的你。希望我们这份友谊可以永存，不随时光而褪色。"""
[[comment]]
from = 25
date = 2022-12-03
description = """江浩哲，人称江哥。在初一时，他十分安静，让人觉得他是那种内向的人。然而，当有了共同话题后，会发现他是一个十分开朗的的人。他喜欢高达，看过很多高达。我在以前一直以为他不打游戏，事实上他也玩，但他玩得很少，至少在我看来是这样的。
事件：曾和我在电脑上联机玩泰拉瑞亚，他开局挂了多次导致我们的出生点变成墓地，整整一个晚上全是怪。
他学习很好，他能在浮躁的环境中静下心来，我敢说这种毅力绝对不是大多数人所拥有的。他有梦想吗？我并不知道，但我觉得了他一定有说不定是个远大的梦想。
他也喜欢看动漫，拉我入坑《电锯人》。《电锯人》是纯爱超甜后宫番，玛奇玛善良温柔是群剧中的好女人。"""
# [[comment]]
# from = 6
# date = 2022-12-04
# description = """江浩哲性情开朗积极乐观，懂得在学习中享受生活；你团结同学，具有强大的凝聚力，是同学们的朋友也是学习的楷模；你尊敬老师，珍爱友谊，拥有阳光一般灿烂的心情。很高兴你能在初中三年里取得优异的成绩，顺利完成人生第一步的转折。在今后的学习中，相信你会以你执着的信念和勤奋的汗水争取属于你的成功!"""