name_en = "Susan"
nickname = [
    "阿贤",
]
relationship = [
    { with = 2, is = "朋友" },
    { with = 19, is = "朋友" },
    { with = 1, is = "朋友" },
    { with = 21, is = "朋友" }
]
[[comment]]
from = 33
date = 2022-12-03
description = """数学课上、物理课上、化学课上一直有你的身影、这样的理科女简直帅炸了好吧！作为同学口中的小天才，你依旧谦虚谨慎，不断为难题贡献新的思路与解法。一晃三年将满，有幸成为你的同学，让我们共勉，一起奔赴美好的未来吧"""
[[comment]]
from = 9
date = 2022-12-04
description = """容颖贤，姓容，名颖贤，身高大约一米七五（不是很准），性别女，银河系第一悬臂猎户臂太阳系（从太阳往外数第三颗）地球，亚洲中国广东省广州市番禺区祈福英语实验中学9B1的学生之一。身份化学课代表，前生物课代表。任职期间视数年如一日，兢兢业业，一丝不苟，认真对待老师发给的任务，从不懈怠丝毫。性格稍为开朗，理科方面较为突出，常处贵族于败军之地，能有奇思妙想，令人惊叹。"""
[[comment]]
from = 7
date = 2022-12-07
description = """不得不说，你的理科真的太强了。你当生物课代表那一会儿，你几乎就是班里的权威；数学课上也常见你提出各种新奇思路，直接把老师的解法按在地上摩擦；化学课上也见你屡次被老师表扬，获得高分。另一方面，你也有着强烈的好奇心，当我打算出点什么新政策，你总会过来打探个究竟。平时在学校里面常见你端着一本书，忘我地阅读，有时在上着课也看到过你把一本小说放在抽屉下边略上一点的位置，帅气地无视了老师的滔滔讲演，躲过了目光的来回横扫。我也曾看到过你一手拿着苹果，一手认真记笔记。当时的我曾疑惑，上课时吃，吃完后手不会因为果汁而变得很黏吗？不知道你是不是有什么超能力，能够把黏手带来的心烦给屏蔽掉。最后祝你在未来的日子里能够继续保持优势，前程似锦！"""