name_en = "Susan"
nickname = ["阿贤"]
relationship = [{ by = 2, is = "曾孙" }, { by = 7, is = "门客" }]
reviews = [
    """第一眼见你，就觉得你有着超越年龄的成熟，你似乎对阅读十分痴迷，无论何时见你，你都会捧着一本书，静静地在那里，或站或坐。图书角被你管理得井然有序，优秀图书管理员对于你而言，实至名归。在长隆游历鬼屋的经历让我们更了解彼此:好巧，原来你也是个胆小鬼。但你又与我不同在于，一样高度近视，却还要挑战过山车，所以原来你也年少轻狂的一面。你是个率真的女孩，和你相处很开心。只是有一点小建议:你的阅读输入和输出之间，并没有成正比哦，错别字也有点多……文字水平再提高一点点，那你就是最靓的崽了！很高兴认识你！""",

    """阿贤理科真厉害。提起你的成绩走势，几科老师都一致认为优势在后头，数学思维有时让级长都感叹不已（当然，我听不懂她在感叹啥），很厉害的样子。本来兼有阅读量的支撑，你的成绩应该更好，但是细看之下，你的阅读也实在是过于个性化，即使敌军政治历史三个小时后就要到达战场，我家阿贤还是可以气定神闲，坐在座位大翻特翻沈石溪的《警犬》。一计空城让为师不由得替你捏一把汗，因为实在知道城中真空。聪明需要踏实做助攻，否则做空中楼阁，很难笑到最后的，无论做人还是做学问，此理通同。""",

    """当你出现在阳光下，就给大家留下了许久都不会忘记的深刻印象：身材高高的，十分匀称，浑身上下穿的干干净净，只有一头蓬松的黑发在风微微飘动。
你总是很睿智，在厚厚的镜片后，藏着一双智慧的眼睛，浑身上下都散发着智慧的气息，在生物课上，你可以自信地回答老师的问题；数学课上，你确乎是一位女中豪杰，解题如同砍瓜切菜；物理化学，也都尽显天赋……真羡慕你啊，更希望你能一直智慧下去，一直自信下去。""",

    """“书山有路勤为径，学海无涯苦作舟。”勤勉永远是成功的要素。事实上你拥有着聪慧的资质，但目前来看，你缺少一份恒心。还记得你时时的发呆和慵懒的小憩，其实只要你执着地去做了，那么，从长远看，胜利必将属于你。阿贤，请珍惜你的拥有，并大胆地去开拓进取吧。""",

    """你是一个很懂事的女孩，在老师的心中，你其实是一个积极要求上进的学生，但这一学期，你似乎努力不够，翻翻童话，做做手工，成绩却停滞不前。阿贤啊，初三已到了冲刺阶段，希望你坚持不懈地努力，向着自己的既定目标努力，抓住主要矛盾，相信你一定能成为重点中学的一名学生，老师相信你能行！""",
]
[[comment]]
date = 2022-12-03
description = """数学课上、物理课上、化学课上一直有你的身影、这样的理科女简直帅炸了好吧！作为同学口中的小天才，你依旧谦虚谨慎，不断为难题贡献新的思路与解法。一晃三年将满，有幸成为你的同学，让我们共勉，一起奔赴美好的未来吧"""
from = 33
[[comment]]
date = 2022-12-04
description = """容颖贤，姓容，名颖贤，身高大约一米七五（不是很准），性别女，银河系第一悬臂猎户臂太阳系（从太阳往外数第三颗）地球，亚洲中国广东省广州市番禺区祈福英语实验中学9B1的学生之一。身份化学课代表，前生物课代表。任职期间视数年如一日，兢兢业业，一丝不苟，认真对待老师发给的任务，从不懈怠丝毫。性格稍为开朗，理科方面较为突出，常处贵族于败军之地，能有奇思妙想，令人惊叹。"""
from = 9
[[comment]]
date = 2022-12-07
description = """不得不说，你的理科真的太强了。你当生物课代表那一会儿，你几乎就是班里的权威；数学课上也常见你提出各种新奇思路，直接把老师的解法按在地上摩擦；化学课上也见你屡次被老师表扬，获得高分。另一方面，你也有着强烈的好奇心，当我打算出点什么新政策，你总会过来打探个究竟。平时在学校里面常见你端着一本书，忘我地阅读，有时在上着课也看到过你把一本小说放在抽屉下边略上一点的位置，帅气地无视了老师的滔滔讲演，躲过了目光的来回横扫。我也曾看到过你一手拿着苹果，一手认真记笔记。当时的我曾疑惑，上课时吃，吃完后手不会因为果汁而变得很黏吗？不知道你是不是有什么超能力，能够把黏手带来的心烦给屏蔽掉。最后祝你在未来的日子里能够继续保持优势，前程似锦！"""
from = 7
[anecdote]
embarrassment = "上课看闲书被发现"
interests = "看闲书"
want = "永远无忧无虑看闲书（痴人说梦）"
[[article]]
content = "值日班长容颖贤的述职报告"
date = 2021-12-17
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247491000&idx=1&sn=c215e6bbe10c1e346f1fa6eda29096dc"
[[article]]
content = "我以妙笔绘青春——第一届手绘杂志原创大赛"
date = 2021-03-04
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247487140&idx=1&sn=defc6000c7392dfb65d5a4afd7285bf5"
[[article]]
content = "阿贤生日快乐！ 一直在等你展示真正的实力，加油哈！"
date = 2021-06-22
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247489577&idx=1&sn=df6129b9adb7ac202da52735bf21d5c7"
