name_en = "Sophia"
nickname = [
    "菲姐",
    "苏er菲",
    "苏公鸡",
    "苏菲~",
    "菲菲", 
    "苏伊士运河", 
]
relationship = [
    { with = 30, is = "八世孙" },
    { with = 23, is = "儿子" },
    { with = 5, is = "儿子" },
    { with = 2, is = "女神" },
    { with = 10, is = "死忠粉" }
]
plots = [
    "上课睡觉，下课疯玩",
]
[[comment]]
from = 35
date = 2022-12-03
description = """你是一个浑身充满魅力的女孩，你认真努力并且积极向上。我总是能在排行榜上看见你名列前茅，你很聪明。但是更多的，是你那平易近人的气质，令我沉醉其中。我喜欢与你一起探讨题目，一起有一搭没一搭地聊天。你很有风趣，很幽默，总是令我在课堂上忍俊不禁，我很喜欢与你相处。希望以后你的日子里，满是快乐与色彩，鲜花与掌声。我们顶峰相见，我可敬的同桌！以上都是la胡言乱语的我的评价是不如宵宫"""
[[comment]]
from = 32
date = 2022-12-03
description = """你从来都是我们班上的佼佼者，琴棋书画样样精通。为人和善，学习成绩也十分亮眼，是许多大人口中的“别人家的孩子”是许多人仰望并且追逐的对象。所有人都相信你会考入理想的高中，加油，在高中继续奋斗吧！"""
[[comment]]
from = 20
date = 2022-12-04
description = """在写评语之前，我想先发表一下我的感想。菲姐，你是我的神！！怎么可以有人长得又好看身材又好学习体育全能写字还跟打印似的（此处省略N个优点）……真的很厉害。俗话说的好：三班有嘉敏，一班有菲姐。十大提名几乎每个都有人投你也就算了，积分榜上的分数直接断层第一！！！华附大仙班预备学子加油！以后我就可以吹我有个清北的同学啦！"""