name_en = "Sophia"
nickname = ["菲姐", "苏er菲", "苏伊士运河", "尽职尽责的政治科代表", "苏公鸡", "苏菲~", "菲菲"]
plots = ["上课睡觉，下课疯玩"]
relationship = [{ by = 5, is = "十八世孙" }]
reviews = [
    """对你我是一定要尊一声菲姐的，这一个学期，你实在给了我太多太多惊喜。
一开始品读你的“大眼睛”，透过你立意高远的文字，我了解了你超越一众凡夫俗子的思想深度；“祈福杯现场书法大赛”上，你挥毫泼墨，将二等奖收入囊中，这一手好字是你一生的财富，至今课室里还挂着你娟秀的正楷；校园模型大赛上，作为总工程师，你又展现了卓越的领导才能、沟通能力和协调能力，保障了我们在大赛上取得了绝对胜利；在元旦晚会演出的排练时，我也有幸见到了曼妙动人的舞姿；而十分难得的是，你很清楚自己想要的是什么，有壮士断腕的魄力和及时止损的勇气。你啊你，真的让我一想起来就在心里称赞不已。菲姐，好荣幸认识你！""",

    """菲姐性格直爽，有着坚毅的目光，真的很有些侠女的感觉。开学时的原创杂志，又让为师感叹于你的文化底蕴。作为一班不可或缺的一员，你又有着很强的集体荣誉感。你能够尽职尽责，帮助集体维护利益，提醒同学注意遵守级组和学校的各项规章制度，又能向老师们提出合理的建议。很难得的，你又兼有孩子气的一面，记得寒假发公众号消息，为你庆祝生日时，“线人”来报，你在被窝里笑到蒙头撒娇。很开心能给你带去一份快乐，也谢谢你给我们这么多。""",

    """看着韬韬写下的关于你的印象，为师实在很想给他两脚，菲姐如此优秀，被他写成个啥咧？！
菲姐也是有着超越年龄的成熟，待人接物都十分有章法，这也得益于你良好的家庭教育，从未在他人之口中听到任何关于你的微词。
这学期从元旦演出排练，到模型制作大赛，再到值日班长述职报告，凡是你的责任，你无一不把它做到尽善尽美。进行述职报告时更是落落大方，看着你在台上侃侃而谈，我总会做白日梦：这是我家孩子多好。
菲姐加油哈，小穗都以你为榜样呢！""",

    """你是一个文静、伶俐的女孩，又是大家眼中的全才。你的爱好很广泛，画画、书法无所不能，跳绳、写作更是你的拿手戏。同学们最羡慕你能做到学习与特长发展两不误。每天每科的作业都认真完成，每次作文都写得生动优美，每次测试成绩都是优秀，特长比赛中你更是当仁不让的主角。马上就要升上初三，很快就要面对更艰苦的角逐。沉着应对，定有佳绩。""",

    """菲姐是一个大方爱笑的女孩，也是一个乖巧懂事的女孩，似乎从没见过你跟别人生气，在班级中有极好的人缘。你学习认真勤奋，书写端正，字体大方漂亮，这让为师羡慕不已；你做事认真，关心集体，帮助同学，是老师得力的助手，一直受老师同学的好评。三年来，菲姐一直状态稳定，几乎从没见你因为什么事而失态，真是非同一般的沉稳。继续保持就好，你真的是非常优秀！""",
]
[[comment]]
date = 2022-12-03
description = """你是一个浑身充满魅力的女孩，你认真努力并且积极向上。我总是能在排行榜上看见你名列前茅，你很聪明。但是更多的，是你那平易近人的气质，令我沉醉其中。我喜欢与你一起探讨题目，一起有一搭没一搭地聊天。你很有风趣，很幽默，总是令我在课堂上忍俊不禁，我很喜欢与你相处。希望以后你的日子里，满是快乐与色彩，鲜花与掌声。我们顶峰相见，我可敬的同桌！以上都是la胡言乱语的我的评价是不如宵宫"""
from = 35
[[comment]]
date = 2022-12-03
description = """你从来都是我们班上的佼佼者，琴棋书画样样精通。为人和善，学习成绩也十分亮眼，是许多大人口中的“别人家的孩子”是许多人仰望并且追逐的对象。所有人都相信你会考入理想的高中，加油，在高中继续奋斗吧！"""
from = 32
[[comment]]
date = 2022-12-04
description = """在写评语之前，我想先发表一下我的感想。菲姐，你是我的神！！怎么可以有人长得又好看身材又好学习体育全能写字还跟打印似的（此处省略N个优点）……真的很厉害。俗话说的好：三班有嘉敏，一班有菲姐。十大提名几乎每个都有人投你也就算了，积分榜上的分数直接断层第一！！！华附大仙班预备学子加油！以后我就可以吹我有个清北的同学啦！"""
from = 20
[anecdote]
embarrassment = "既然是糗事我怎么可能说呢。。。"
interests = "打游戏、弹钢琴、看小说、偶尔还喜欢学习"
want = "想去二次元拥抱帅哥们；想痛快地打一整天游戏"
[[article]]
content = "侠女菲姐的武侠梦"
date = 2021-05-18
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247489437&idx=1&sn=cd6b9232e4f3813ff21da68552a48f40"
[[article]]
content = "我以妙笔绘青春——第一届手绘杂志原创大赛"
date = 2021-03-04
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247487140&idx=1&sn=defc6000c7392dfb65d5a4afd7285bf5"
[[article]]
content = "千日圆满 感动初三"
date = 2023-04-29
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247491100&idx=1&sn=3e48217a9493b07c1218c250cc000cfb"
[[article]]
content = "记忆中的年味 - by 菲姐"
date = 2021-03-30
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247488363&idx=1&sn=b0bd69cee796a9873521c6c28f022f68"
[[article]]
content = "岁岁年年，元宵喜乐"
date = 2021-02-26
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247483702&idx=1&sn=295f4d94cf5be39ddb112e378372d2c0"
