name_en = "Tony"
nickname = ["半裸老男人", "（大）老鼠", "嫂子", "曾掏裆", "黑子", "不搬作业的化学科代表"]
plots = [
    "七年级中午进行生物讨论，狼人杀（带过一次爱丽），真心话大冒险",
    "体锻踢球",
    "晚修下位聊天",
    "躺平睡只剩男生更嗨了，困了就一起睡",
]
relationship = [
    { by = 11, is = "朋友" },
    { by = 18, is = "孙子" },
    { by = 31, is = "兄弟、损友" },
    { by = 6, is = "儿子" },
]
reviews = [
    """初见时，你皮肤黝黑，目光慵懒，浑身散发的气质有专属名字，就叫做随遇而安。你看起来那么漫不经心，似乎对一切都不放在心上，不禁让为师默默捏了一把汗:这学生学起习来，怕是也要随心而动了吧……阅读你的朋友圈，满屏都是我看不懂但是感觉很厉害的话，只是那些深奥的语言全部都只和足球有关。
如果不是那一次的微信长聊，我也许永远不会想到你对身边的人和事，见解会如此独到。同学们的喜怒哀乐，你都看在眼里；同学们的默默付出，你都记在心上，其实，你是一个有心人。
运动场上，你身手不凡，足球赛上你扑救那几球的帅气身影，至今仍然在我们心里挥之不去。在开放日排练间隙，你和江哥、阿怪切磋武艺的样子，给我们带来了超多欢乐；而你面对偷拍的人的镜头那淡泊的气质，又贡献了不少表情包，让人捧腹笑翻。这一学期你的成绩也稳中有升，级会上去领奖状的时候，我看到了你脸上的荣耀。虽然你经常“挑战”班主任权威，为师也不含糊，我们礼尚往来，一个学期就这样欢乐地过去了。下学期，我们精彩继续哈！""",

    """你的数学非常厉害，连级长都夸奖你好大喜功；你还是一个很负责任的学长，为学弟学妹们讲题那是英姿飒爽；你擅长运动，还记得监控下你在讲台上蹿下跳的灵巧模样，让大家真正了解了什么叫做青春。
但是命运似乎总是想要给你多一些考验，这学期你过的稍微有些坎坷，课室门口班牌上的告示以及腿上的疤，都在诉说着这一学期的不幸，希望你在下学期多看书，少打闹，成绩一路向上。
钦此。""",

    """我家韬韬是一个公认的极为英俊潇洒的人，你的理科成绩极好，就连九年级压轴题对你来说也不在话下，你还经常潜入九年级答题区偷题，并总能轻轻松松解答。化学也是你的拿手好戏。你可谓我们班的“足球天王”，绿茵场上你总是尽情挥洒着汗水，一个个惊险的救球透露出你精湛的球技。在每一个平常的日子，你都在散发着自己的个人魅力，认真好学的你着实给我们带来了超多快乐！""",

    """总以为你的字就是这么龙飞凤舞，也曾体谅地想过男孩子嘛，就是这样不拘小节。谁料在课间偶然见你认真地拓写着字帖，令我眼睛一亮，原来你是这样的深藏不露啊。你又像只活跃的袋鼠，最喜欢在绿茵场上挥洒汗水，有点担心你像小伙伴一样摔得鼻青脸肿。爱玩是每个孩子的天性，但注意安全理要时刻谨记哈！""",

    """你是一个很有运动天分的男生，几乎每一项体育运动在你的身上都显得轻巧而又从容，很喜欢看你运动时的模样，专注且充满能量。你也是一个有悟性的男生，学习对你来说应该不是一件很难的事，无论课上或课余，经常能看到你的不解和讨教。时光匆匆，初中三年转瞬即逝，记得刚刚八年级的时候，你还在刻意强调自己是“初二的男生”，很在意地装大的样子让人捧腹。还剩几个月的时间，保持现在的状态，或者再勤勉一点，就更好了!""",
]
[[comment]]
date = 2022-12-04
description = """黑子，姓曾，名韬展。身高六尺，身形魁梧强壮，肤色黝黑，善于奔行于足球场上谓守门员之席。据我所知，他是年级里为数不多受过训练的守门员，其专业程度可见一斑。而其运动能力更是惊为天人，转眼可行百余丈，众人皆叹曰，“此乃天神之速也”。武，可日行千里；文，可思帝王之事。尝呼，“何时可了却统一世界之大业？”常以“世界之征服者四”为介，练习统兵领将之事。不出一昼，可出柏林闪击至斯大林格勒，不为难也。"""
from = 9
[[comment]]
date = 2022-12-05
description = """你曾问我，《湖心亭看雪》里的“痴“有哪些。我说，有痴情、有痴景、更有痴人。未曾想过如今能见到对航天如此痴迷的人。你”精通“火箭各个零部件，对于航天上的里程碑也能顺手拈来，可谓是比航天员还专业；未曾想过如今能见着对化学如此痴迷的人。化学用语好似成为了一门语言，各种反应更是刻在了DNA里。就算是相公的痴迷，也要比你稍逊几分啊！"""
from = 16
[[comment]]
date = 2022-12-06
description = """打游戏很强，不会因为队友菜而生气，但有时候一直被人抢人头会心态爆炸，甚至关闭游戏。跟熟悉的人聊天很热情，乐于帮助他人。非常的热爱运动，即使下雨也会在球场上踢球，对足球运动员很熟悉。学习成绩优异，思维敏锐。"""
from = 18
[anecdote]
embarrassment = "在游戏中坠毁了一天的火箭"
interests = "踢球、航天"
want = "去现场看拜仁夺得欧冠冠军"
[[article]]
content = "我以妙笔绘青春——第一届手绘杂志原创大赛"
date = 2021-03-04
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247487140&idx=1&sn=defc6000c7392dfb65d5a4afd7285bf5"
[[article]]
content = "嫂子生日快乐！祝你文科开窍，给我们更多快乐哈"
date = 2021-10-03
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247490648&idx=1&sn=668881333f02319b1a9d38951562443a"
