name_en = "Tony"
nickname = ["黑子", "大老鼠", "曾掏裆", "嫂子", "半裸老男人"]
relationship = [
    { with = 6, is = "儿子" },
    { with = 18, is = "儿子" },
    { with = 3, is = "儿子" },
    { with = 14, is = "儿子" },
]
plots = [
    "七年级中午进行生物讨论，狼人杀（带过一次爱丽），真心话大冒险",
    "躺平睡只剩男生更嗨了，困了就一起睡",
    "体锻踢球",
    "晚修下位聊天",
]
[[comment]]
from = 9
date = 2022-12-04
description = """黑子，姓曾，名韬展。身高六尺，身形魁梧强壮，肤色黝黑，善于奔行于足球场上谓守门员之席。据我所知，他是年级里为数不多受过训练的守门员，其专业程度可见一斑。而其运动能力更是惊为天人，转眼可行百余丈，众人皆叹曰，“此乃天神之速也”。武，可日行千里；文，可思帝王之事。尝呼，“何时可了却统一世界之大业？”常以“世界之征服者四”为介，练习统兵领将之事。不出一昼，可出柏林闪击至斯大林格勒，不为难也。"""
[[comment]]
from = 16
date = 2022-12-05
description = """你曾问我，《湖心亭看雪》里的“痴“有哪些。我说，有痴情、有痴景、更有痴人。未曾想过如今能见到对航天如此痴迷的人。你”精通“火箭各个零部件，对于航天上的里程碑也能顺手拈来，可谓是比航天员还专业；未曾想过如今能见着对化学如此痴迷的人。化学用语好似成为了一门语言，各种反应更是刻在了DNA里。就算是相公的痴迷，也要比你稍逊几分啊！"""
[[comment]]
from = 18
date = 2022-12-06
description = """打游戏很强，不会因为队友菜而生气，但有时候一直被人抢人头会心态爆炸，甚至关闭游戏。跟熟悉的人聊天很热情，乐于帮助他人。非常的热爱运动，即使下雨也会在球场上踢球，对足球运动员很熟悉。学习成绩优异，思维敏锐。"""
