name_en = "Jarvis"
nickname = [
    "黑鸭",
    "鸭鸭",
    "鸭子",
    "鸭劳➗",
]
relationship = [
    { with = 6, is = "儿子" },
    { with = 14, is = "儿子" },
    { with = 3, is = "儿子" }
]
[[comment]]
from = 7
date = 2022-12-03
description = """“钟——帅——”印象中的你总是拖长的声音，摇晃着可爱的脑袋头同我打招呼。似乎你和数学有一段不解之缘，数学课上的你，一边英姿飒爽地行使贵族特权，一边绕过张婷的目光利剑，手捧绝世难题，向伙伴奔去。评讲台上的你摘下了数学聪明星桂冠，好多次以全卷满分130的名号称霸天下；语文课上你几乎总是文言文的救兵，更是难度标准的代名词，基础扎实，印象里你从未被打脸过。课余时间也常见你大胆耍威风，展示自己的强壮的肌肉，背起同学遍地走。你亦不忘在紧绷的学习生活间放松身心，篮球场上鸭神三分传话；核酸玩闹排大队；据说你王者*耀还玩得相当溜。富有个性的你与我度过太多值得回忆的时光。从七年级一起在纪委会结交开始，我们一起干过许多“正经事”：逃避宿管、雨天打球……希望未来我们友谊依旧，也祝福你能够取得更大的进步！"""
[[comment]]
from = 25
date = 2022-12-03
description = """周晋宇，人称周黑鸭，他十分聪明，数学很好。他喜欢打游戏，如《王者荣耀》《元神》，他成绩长期处于前列。
事件：其曾在跑一千米前，大嘘其要放水，要摆烂。但是他全程跟着钟彦慷跑。跑完后竟说已经放水了，可谓是深藏不露。他曾与我玩王者，我在上路单机打了五六分钟，他打野始终未来，害我被压在塔下。
我不知道他有什么梦想，但是他有一个强大的能力，可以识人心智。
他曾与盘柯篮球单挑，三个三分开局秒了盘柯，柯不服，和他打大比分，结果他三分成功暴打盘柯。"""
[[comment]]
from = 16
date = 2022-12-05
description = """故友长存，却与吾交际甚少。只记得你有“宽广无际”的人脉，跟谁聊天都能让人听得津津有味；四大贵族中，你不缺思维，又多一份严谨，是最被寄予厚望的一个；赛场上，不对等的身材与实力也让你跑出了不凡的成绩；课堂上，总不乏一个能把文言文翻译得头头是道的人。诗歌成语早已烂熟于心，早在数年前就一睹过你的风采。加油吧，望君必成！"""
[[comment]]
from = 13
date = 2022-12-06
description = """周晋宇，外号黑鸭，海拔约170厘米。形貌昳丽。身量苗条，体格风骚，粉面含春威不露，丹唇未启笑先闻。难怪，他还有个外号叫“9亿少女心中梦”。周晋宇最大的特点就是数学好到极点。遇到一些难题时，当我们大多数人都在抓耳挠腮，一筹莫展时，只见他紧锁眉头死死盯着试题。三秒后他眉头舒展，露出会心一笑，这时他肯定已经想好破题的方法，果然只见他大笔一挥，便开始在纸上又写又画，看得懂了以为他在做题，不知道的还以为他在涂鸦，三分钟后，他自信的拿着题目走上讲台，看着老师都还在苦思冥想，于是他把题目往讲台一丢，丢下一个“逊”字后，潇洒离去。"""