name_en = "Jarvis"
nickname = ["鸭劳", "鸭子", "鸭鸭", "黑鸭"]
relationship = [{ by = 6, is = "儿子" }, { by = 7, is = "盟友" }]
reviews = [
    """只差一点点，你可能就不归我管了。在一番波折之后，终于有缘相见。一个浓眉大眼的小男孩出现在我面前，看起来很聪敏的样子。你表情丰富，这一点似乎并不亚于为师，我存了好多你的表情包；你成绩优异，尤其是数学一科，常常听老师同学说起你数学又得到了很高的分数；你人缘不错，总会有人来向我打探关于你的情况；你参与活动十分积极，校园模型大赛上，你也乐在其中跟着一起忙得转圈圈；你还有着好脾气，开放日表演时，尽管妆容让为师描化得异常惊心动魄，你还是顺从地顶着压力完成了表演……一幕一幕，像电影一般，这一学期就这样落幕了，意犹未尽，下学期我们继续演绎精彩哈！很高兴认识你！""",

    """我家黑鸭聪明伶俐，总是能想出一些好玩的主意，课室里有你在，大家就不怕会寂寞；我家黑鸭英俊帅气，线上授课阶段，屏幕上黑鸭的颜值是大家公认的有着家传式优势；我家黑鸭又能说会道，还记得团建时你在辩论赛上的激昂洒脱；我家黑鸭国学底蕴又很深厚，还记得开放日的“成语风云”大赛上，你才思敏捷，数秒道破天机……
一个个平常的日子里，这只黑鸭带给我们无尽的快乐（微信表情又暂且不提），总之你有太多优点，好幸运遇见过你！""",

    """黑鸭长得浓眉大眼，身材匀称，这学期以来愈发标致起来，同学们说你认真思考时“头脑冷静，神态安详”，而深思熟虑之后的脑回路也往往清奇，总是令人叹为观止。你的外表仍不脱孩子气，又大又黑的眼睛十分热情，最喜欢看你耳朵变红，肉色的耳廓镶了一道火红的边框，配上或气恼或激动的神情，实在有意思。
从这个学期开始，你的人缘越来越好，下课时总是被男生簇拥，拉去聊天；你的数学成绩稳居班级前五，其他科目也毫不逊色；你在体育方面也十分出色，每次第九节下课你都会喊一句“狗子出去打球吗？”而后前呼后拥，声势浩荡地向操场进发，展现自己青春的活力；你确乎有一种吸引力，似乎是个人的魅力和领袖的自信的奇怪混合产品。""",

    """你思维灵活，求知欲强，富于质疑精神，对事物常有不落俗套的看法。老师喜欢你那种敢想、敢说、敢问、敢辩的课堂表现；但老师更希望看到你干净整齐的作业，看到你的学习成绩有不断的进步。愿你坚持不懈，再创辉煌！""",

    """黑鸭个性活泼开朗，待人热情随和，坦诚友善，喜欢搞笑逗乐，也乐于帮助别人，在班里人缘极其不错。黑鸭有头脑，有思想，有主见，独断能力很强。青春的力量在你的身上渐渐萌发，在寻找自我，但是也要尽量克制，只要熬过这一段雨季，花季就更显灿烂了。""",
]
[[comment]]
date = 2022-12-03
description = """“钟——帅——”印象中的你总是拖长的声音，摇晃着可爱的脑袋头同我打招呼。似乎你和数学有一段不解之缘，数学课上的你，一边英姿飒爽地行使贵族特权，一边绕过张婷的目光利剑，手捧绝世难题，向伙伴奔去。评讲台上的你摘下了数学聪明星桂冠，好多次以全卷满分130的名号称霸天下；语文课上你几乎总是文言文的救兵，更是难度标准的代名词，基础扎实，印象里你从未被打脸过。课余时间也常见你大胆耍威风，展示自己的强壮的肌肉，背起同学遍地走。你亦不忘在紧绷的学习生活间放松身心，篮球场上鸭神三分传话；核酸玩闹排大队；据说你王者*耀还玩得相当溜。富有个性的你与我度过太多值得回忆的时光。从七年级一起在纪委会结交开始，我们一起干过许多“正经事”：逃避宿管、雨天打球……希望未来我们友谊依旧，也祝福你能够取得更大的进步！"""
from = 7
[[comment]]
date = 2022-12-03
description = """周晋宇，人称周黑鸭，他十分聪明，数学很好。他喜欢打游戏，如《王者荣耀》《元神》，他成绩长期处于前列。
事件：其曾在跑一千米前，大嘘其要放水，要摆烂。但是他全程跟着钟彦慷跑。跑完后竟说已经放水了，可谓是深藏不露。他曾与我玩王者，我在上路单机打了五六分钟，他打野始终未来，害我被压在塔下。
我不知道他有什么梦想，但是他有一个强大的能力，可以识人心智。
他曾与盘柯篮球单挑，三个三分开局秒了盘柯，柯不服，和他打大比分，结果他三分成功暴打盘柯。"""
from = 25
[[comment]]
date = 2022-12-05
description = """故友长存，却与吾交际甚少。只记得你有“宽广无际”的人脉，跟谁聊天都能让人听得津津有味；四大贵族中，你不缺思维，又多一份严谨，是最被寄予厚望的一个；赛场上，不对等的身材与实力也让你跑出了不凡的成绩；课堂上，总不乏一个能把文言文翻译得头头是道的人。诗歌成语早已烂熟于心，早在数年前就一睹过你的风采。加油吧，望君必成！"""
from = 16
[[comment]]
date = 2022-12-06
description = """周晋宇，外号黑鸭，海拔约170厘米。形貌昳丽。身量苗条，体格风骚，粉面含春威不露，丹唇未启笑先闻。难怪，他还有个外号叫“9亿少女心中梦”。周晋宇最大的特点就是数学好到极点。遇到一些难题时，当我们大多数人都在抓耳挠腮，一筹莫展时，只见他紧锁眉头死死盯着试题。三秒后他眉头舒展，露出会心一笑，这时他肯定已经想好破题的方法，果然只见他大笔一挥，便开始在纸上又写又画，看得懂了以为他在做题，不知道的还以为他在涂鸦，三分钟后，他自信的拿着题目走上讲台，看着老师都还在苦思冥想，于是他把题目往讲台一丢，丢下一个“逊”字后，潇洒离去。"""
from = 13
[anecdote]
embarrassment = "晚修和俊希一起搂抱着学习被蔡芸抓拍"
interests = "唱、跳、Rap、篮球"
want = "和坤坤合影"
[[article]]
content = "值日班长周晋宇的述职报告"
date = 2021-12-20
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247491002&idx=1&sn=6212e393dfb1386bf308f3dc6ce0cdf7"
[[article]]
content = "我以妙笔绘青春——第一届手绘杂志原创大赛"
date = 2021-03-04
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247487140&idx=1&sn=defc6000c7392dfb65d5a4afd7285bf5"
[[article]]
content = "迟到的祝福：周黑鸭生日快乐！我家黑鸭越来越优秀，越来越帅气！！"
date = 2021-10-02
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247490647&idx=1&sn=cc525550d8156116ab551da8ade8cc83"
