name_en = "Hannah"
nickname = ["阿好", "HH"]
relationship = [{ by = 28, is = "革命盟友" }]
reviews = [
    """在刚刚拿到班级名单的时候，你的名字就成功引起了我的注意，这个因地制宜的名字针不戳！后来终于见到你了，一个蓬蓬头的小女孩，笑起来眼睛会眯成一条线。你成绩极好，一直稳居年级前十，更可贵的是，和你相处完全没有师生的隔阂感。还记得一起在长隆的鬼屋里，被吓得抱着xxs哀嚎。你天生音色很特别，这是你的财富，而且你有着超乎常人的文学灵性，文笔细腻，写起诗来真是让人赞叹不已，因为我还记得，你的“及时我什么都没有了，至少，我还有你”。不过人无完人，如果你能在与同学相处时，再稍加留意下方式和尺度，你会更加可爱。比如那让人难以忘怀的棒棒糖的分享……好了，我很高兴认识你！""",

    """人如其名，你性格温婉如玉，一团和气，很有儒学传统的中庸气质。这个学期你收获满满，不仅仅是语文的单科状元，连总分也屡次在年级乃至联考中数一数二。
你细心体贴，瑶瑶生病落下了课程，你都看在眼里，又不惜利用自己的课余时间帮她补习。你有着超强的自律性和极其清晰的奋斗目标，优秀对于你已经成为了一种习惯，加油哈，继续给我们更多惊喜！""",

    """第一眼见到你，觉得你温暖又害羞，让人觉得你像和煦的春风，轻轻柔柔。相处久了，发现你其实是那炽烈的阳光，奔放而热烈。
你是热情的，不拘小节，对谁都大大方方，就连你周边的环境也如你的性格一样随让人觉得舒服。虽然你看起来大大咧咧，笔下却能写出无比细腻的文章，你将所有的美好都写在寸寸信笺之上，又展现在生活的精彩之中。
你的努力和刻苦也为你带来了回报，班里的人对你所取得的成绩都是心服口服的。你又很谦虚，虽然有时谦虚得过了头。
你一定能继续努力下去的，并且相信你一定能收获应有的回报，也愿你和身边的人总能融洽的相处，永远“何好”。""",
]
[anecdote]
embarrassment = "晚自习说话被发现"
interests = "睡觉"
want = "连着睡好几天觉"
[[article]]
content = "何好的政治思想"
date = 2021-03-11
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247487144&idx=1&sn=add35043f5a8147491e17effc7e74af4"
[[article]]
content = "我以妙笔绘青春——第一届手绘杂志原创大赛"
date = 2021-03-04
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247487140&idx=1&sn=defc6000c7392dfb65d5a4afd7285bf5"
[[article]]
content = "何好生日快乐！初秋微风正好，恬然淡泊最开心哦！！"
date = 2021-08-20
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247490616&idx=1&sn=2d63350cf38bf9f475f07190cc8d1231"
