nickname = [
    "真菌",
    "摇摆",
    "菇菇",
    "单细胞",
    "婷婷",
]
relationship = [
    { with = 10, is = "dear舍友" },
    { with = 28, is = "好大儿" },
    { with = 30, is = "傻儿子" },
    { with = 33, is = "十八世孙" },
    { with = 23, is = "死鬼" },
]
plots = [
    "赖床",
    "因为肾虚与不想上厕所的同学去厕所",
    "快乐干饭",
    "傍晚与宿管斗智斗勇",
]
[[comment]]
from = 15
date = 2022-12-03
description = """真菌乃一班之名列前茅者，能文能武。不急不躁是一种态度，一种张弛有度，一种不急不躁，一种泰然自若。这正是杨珺婷所有的。每逢测试，他人浮躁，她却不急不躁；每逢下发成绩，他人幸甚至哉，她却泰然自若"""
[[comment]]
from = 35
date = 2022-12-03
description = """你和其他的女孩子不太一样，你有种独特的气质。班上的同学们都总能看见课间时你奋斗的背影，你总能在吵闹的课间沉迷于自己的学业，不得不让人佩服。听说你回到宿舍也会刻苦学习，不愧是我们班的标兵。排行榜上你的名字永远高挂，它是来的情有可原的。你也很认真对待体育，每次都能看见你遥遥领先。希望以后的日子里你也永远当那只领头羊！"""
[[comment]]
from = 33
date = 2022-12-07
description = """她是“帅”的代名词，她是无数女生的偶像，是无数男生的心中梦。她在操场上英姿飒爽，轻轻松松拿下体育满分；她在学习上也名列前茅，金榜题名，摘得桂冠。
真的会有这么完美的人嘛！！！婷婷真的太帅了！！！"""