name_en = "Tina"
nickname = ["单细胞", "婷婷", "摇摆", "真菌", "菇菇"]
plots = ["傍晚与宿管斗智斗勇", "因为肾虚与不想上厕所的同学去厕所", "快乐干饭", "赖床"]
relationship = [
    { by = 10, is = "好friend" },
    { by = 28, is = "女儿" },
    { by = 30, is = "儿子" },
    { by = 33, is = "儿子" },
]
reviews = [
    """“真人不露相”这句话用在你身上再合适不过了，平时看你文文静静，我曾以为我永远不会听到你的声音，却没想到有朝一日会拍到你模仿抖音那一段“倾国倾城的美貌”；我曾以为你这通身的大家闺秀的气派，是十指不沾阳春水养成的，却没想到有朝一日会看到你穿着志愿者的红马甲在操场上做义工的身影；我曾以为你会是一个羞涩腼腆的小姑娘，却没想到在那节班会课上，面对略显尴尬的环节和扑面而来的国王，你会表现得那么落落大方……你给了我太多没想到，接下来要继续加油呀！很高兴认识你，单细胞！""",

    """难忘课前演讲时你幽默风趣的表现，难忘课间打闹时你纯真率性的表演，难忘全班躁动时你出淤泥而不染的镇定。你学习一直很努力，几乎在各个科目的优秀作业名单里都能看到你的名字，成绩也一直名列前茅。你的性格又很温顺善良，现在脑海中又回想起那一次给你梳妆，人如其名，你真的像一只小羊，可爱却坚韧，乖的都有点让人心疼了。""",

    """看着龟哥为了夸赞你憋得面目狰狞，为师实在费解。
好喜欢你啊，这样的女儿来20个也不嫌多啊！乖巧懂事，成绩优异，长期位居年级前十；又不是一个呆板的学习机器，内个……听说……你十分热爱科学，尤其是生物，会利用生动的多媒体资源与同学积极讨论生物知识……；你的体育也很棒，在校运会上也取得了优异的成绩，为班级做出了突出贡献；你的优秀还体现在外教课上，尤为突出的是戏剧表演。优点太多了单细胞，你真是一个非常优秀的人，而且看你这小眼睛，总会让为师觉得你和小穗好像，真希望小穗有你万分之一啊！""",

    """难忘在跆拳道表演中你那标准的动作和凌厉的攻势，让为师啧啧惊叹。在生活中，你却性情温柔，全然没了赛场上的霸气。文文静静地看书，仔仔细细地做功课，就算拿到让人惊艳的成绩，也不见你有丝毫的骄傲。江河要做的事——奔流；而你要做的事——前进！祝愿自谦而坚韧的你能踏平赛场和学业的一切坎坷！""",

    """你在学习上是个非常自觉的女孩，特别是在假日中，不用父母的督促，你都能如平时那样早起身，抓紧时间去学习。同时，你从不会在学习上的疑难和偶尔的失败面前退缩，总能面带笑容去对待它们。想起你写的一篇篇文质兼美的作文、回忆着你脸上甜美的笑脸，真的是心情都会好起来。凭着这种乐观的精神，最终成功一定会属于你的！未来还要继续保持哦！""",
]
[[comment]]
date = 2022-12-03
description = """真菌乃一班之名列前茅者，能文能武。不急不躁是一种态度，一种张弛有度，一种不急不躁，一种泰然自若。这正是杨珺婷所有的。每逢测试，他人浮躁，她却不急不躁；每逢下发成绩，他人幸甚至哉，她却泰然自若"""
from = 15
[[comment]]
date = 2022-12-03
description = """你和其他的女孩子不太一样，你有种独特的气质。班上的同学们都总能看见课间时你奋斗的背影，你总能在吵闹的课间沉迷于自己的学业，不得不让人佩服。听说你回到宿舍也会刻苦学习，不愧是我们班的标兵。排行榜上你的名字永远高挂，它是来的情有可原的。你也很认真对待体育，每次都能看见你遥遥领先。希望以后的日子里你也永远当那只领头羊！"""
from = 35
[[comment]]
date = 2022-12-07
description = """她是“帅”的代名词，她是无数女生的偶像，是无数男生的心中梦。她在操场上英姿飒爽，轻轻松松拿下体育满分；她在学习上也名列前茅，金榜题名，摘得桂冠。
真的会有这么完美的人嘛！！！婷婷真的太帅了！！！"""
from = 33
[anecdote]
embarrassment = "无"
interests = "看书，追剧，吃螺狮粉"
want = "中考完去做美甲，而且还是延长款"
[[article]]
content = "单细胞小妙招"
date = 2021-03-12
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247487145&idx=1&sn=f58ec49006b04486afb578bc566c7601"
[[article]]
content = "我以妙笔绘青春——第一届手绘杂志原创大赛"
date = 2021-03-04
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247487140&idx=1&sn=defc6000c7392dfb65d5a4afd7285bf5"
[[article]]
content = "单细胞生日快乐哈，最喜欢你认真的样子。亦动亦静，未来定可期！"
date = 2021-08-21
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247490617&idx=1&sn=2d40e20ad92c179ad96e92a7d129505c"
[[article]]
content = "千日圆满 感动初三"
date = 2023-04-29
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247491100&idx=1&sn=3e48217a9493b07c1218c250cc000cfb"
[[article]]
content = "小老鼠进教室引动乱 温妈妈跺一脚杀小鼠"
date = 2021-08-11
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247490614&idx=1&sn=bdc0ef1dd28932f0ce276c138af6eb18"
[[article]]
content = "星星和飞机的启示"
date = 2021-05-28
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247489572&idx=1&sn=0552e7ea4ce535475d9dc87e60fadf74"
