name_en = "Augustine"
nickname = [
    "龟",
    "七分之四百九十五",
]
relationship = [
    { with = 34, is = "儿子" },
    { with = 35, is = "儿子" },
    { with = 14, is = "儿子" },
]
plots = [
    "打狗子",
]
[[comment]]
from = 20
date = 2022-12-04
description = """绿茵场上奔跑的身影，被汗水浸湿的球衣，黝黑的皮肤和黑框眼镜，全都刻画出你的样子。数学课上与老师积极互动探讨题目，被老师称为“数学贵族”，灵活的思维在你笔下化为条条辅助线，屡屡被老师请上台讲解你的方法。加油！祝前程似锦！"""
[[comment]]
from = 19
date = 2022-12-06
description = """你头脑机灵，反应敏捷，上课积极发言，及时完成各科作业，学习成绩优异。你思想健康，品行端正，要求进步。你爱好广泛，广泛的阅读使你的表达清晰流畅，喜欢运动的你总能见到你奋力拼搏的身影。经常能见到你自信的笑容，解题时的笃定。在初三的最后一个学期，希望你继续努力，向知识的深度和广度继续发展，使学习更上一层楼，考入你理想的高中。"""
[[comment]]
from = 34
date = 2022-12-08
description = """如果说有那么一位同学，学习好，体育强，虽然不算很高，但也不矮，那一定是龟龟。学习上，这位同学总是毫不掩饰他在理科上的天赋。除此之外，他在绿茵场上总是那么的英姿飒爽(狗头)，助跑，打门，一脚优美的弧线便出现在空中。"""