name_en = "Augustine"
nickname = ["七分之四百九十五", "龟", "龟哥", "龟总"]
plots = ["打狗子"]
relationship = [
    { by = 34, is = "儿子" },
    { by = 35, is = "儿子" },
    { by = 9, is = "跑步训练师" },
]
reviews = [
    """哈！我的野生林小钰！你的声音很好听，总是绵绵的，每次与你四目相对，你的目光又总是柔柔的。只要看着你，就理解了什么是岁月静好。难忘的是你强迫症发作，将为师手残留下的满壁疮痍都撕除干净；难忘的是你在开放日和元旦汇演排练时，随音乐舞动所张扬的青春的力量；难忘的是你在每节我的语文课前课后，都会围着讲台和我谈天说地；难忘的更有，你在那次课前演讲时，一一评点全班每个人的专属绰号，那么欢乐，那么暖心……你的成绩又给了我很大惊喜，本以为在花费超大量时间排练后，你的成绩会正常地下滑，真的没想到，你可以带着如此繁重的任务冲到年级前三。这个学期，我们一起度过了一段很难忘的时光，我很珍惜这个学期里的每一天，下个学期也要给我快乐和惊喜哦！很高兴认识你！""",

    """你文静美好，待人温和，是大家眼中的小乖乖；你字迹娟秀大方，批阅你的作业是一种享受；你热心善良，人缘又很好，看到你总会觉得今天很开心；你有很高的舞蹈天赋，生日时你的照片让大家都惊叹于你的才华和美貌……初中生活的三分之一已经过去了，很开心和你一起度过，接下来我们还要继续努力哈。""",

    """野生林小钰，你是班里各路妖魔鬼怪牛鬼蛇神中的一股清流，几次班级大考，各方神圣多半败下阵来时，你仍然屹立不倒，着实厉害。
你还有点强迫症，还记得在七年级时，为师为全班制作了纪律德育分数表格，要贴上墙壁，但因经验不足，手艺不精，使得可是最后满目疮痍，一大块一大块的边角料，像狗皮膏药一般死粘在白墙上。当全班同学都要放弃之际，你毅然舍弃了自己，亲自出马，用手抠撕下了全部“建筑垃圾”，把这项费时又费力，工程量巨大又艰难的工程完成了，你实在有着舍小家为大家的无私奉献精神，吾辈楷模。""",

    """在你合格地完成了本期的学业时，老师也有一番心里话要说给你听，沉默寡言是同别人交流的一堵墙，这使大家不易了解你优秀的一面。多想常常看到你开心的笑容，多想常常听到你爽朗的笑声。来呀，做个乐观开朗的孩子，生活一定会更添姿彩！""",
]
[[comment]]
date = 2022-12-04
description = """绿茵场上奔跑的身影，被汗水浸湿的球衣，黝黑的皮肤和黑框眼镜，全都刻画出你的样子。数学课上与老师积极互动探讨题目，被老师称为“数学贵族”，灵活的思维在你笔下化为条条辅助线，屡屡被老师请上台讲解你的方法。加油！祝前程似锦！"""
from = 20
[[comment]]
date = 2022-12-06
description = """你头脑机灵，反应敏捷，上课积极发言，及时完成各科作业，学习成绩优异。你思想健康，品行端正，要求进步。你爱好广泛，广泛的阅读使你的表达清晰流畅，喜欢运动的你总能见到你奋力拼搏的身影。经常能见到你自信的笑容，解题时的笃定。在初三的最后一个学期，希望你继续努力，向知识的深度和广度继续发展，使学习更上一层楼，考入你理想的高中。"""
from = 19
[[comment]]
date = 2022-12-08
description = """如果说有那么一位同学，学习好，体育强，虽然不算很高，但也不矮，那一定是龟龟。学习上，这位同学总是毫不掩饰他在理科上的天赋。除此之外，他在绿茵场上总是那么的英姿飒爽(狗头)，助跑，打门，一脚优美的弧线便出现在空中。"""
from = 34
[anecdote]
embarrassment = "空门踢飞"
interests = "足球、游戏"
want = "穿越"
[[article]]
content = "我以妙笔绘青春——第一届手绘杂志原创大赛"
date = 2021-03-04
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247487140&idx=1&sn=defc6000c7392dfb65d5a4afd7285bf5"
[[article]]
content = "千日圆满 感动初三"
date = 2023-04-29
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247491100&idx=1&sn=3e48217a9493b07c1218c250cc000cfb"
