nickname = [
    "彦慷师傅",
    "威猛先生",
    "钟帅",
    "盅盐糠",
]
relationship = [
    { with = 11, is = "玩笑箱" },
    { with = 13, is = "伙伴" },
    { with = 14, is = "忠臣" },
    { with = 32, is = "门客" },
    { with = 16, is = "兄弟" },
    { with = 18, is = "猪队友" },
    { with = 23, is = "支持者" },
    { with = 24, is = "合作者" },
    { with = 25, is = "小丑" },
    { with = 21, is = "帮手" },
    { with = 28, is = "指路人" },
    { with = 35, is = "盟友" },
]
[[comment]]
from = 25
date = 2022-12-03
description = """彦慷者，智也，壮也。
吾十分佩服其能组织众人，集中力量办大事，此乃吾等不具也。其德高望重，只要有难，其必助，且其不食言。
其爱好学习，爱好运动，练其体肤乐此不疲。其能跑千米而气不喘，可跳绳数百不言累，且其乃可与吾等说笑于其间，真乃神人也。
事件：吾曾与其谈论其梦想，其曰“着眼当下，勿想太远，以误学业”。其有梦想，但吾不知。想必为关乎大事之梦想也。若其成，吾之梦想也许亦能实现。
其不好游戏，好助人。吾之“一战”，其助吾甚多，其曾在“一战”败军之际，意图力挽狂澜，给吾指明道路，组织人手，东山再起，只可惜，吾之计划——以相声之节目夺一位而以“一战”上位中夺位之事未成，惜也。
主动热心，坚强耐心，拿出诚心与决心，用红心坚持铁心与公心，明确辨析大局意识、忧患意识、责任意识，注重学习意识与上进意识，最终育养出管理意识。"""
[[comment]]
from = 11
date = 2022-12-04
description = """身为班级的梁柱，你是同学们心目中的榜样。初中开学以来，你一直表现优秀，成绩颇佳，与人友善，尊敬师长，积极参加各种课外活动，课后与同学积极互动，是同学们的好榜样，能够做到德智体美劳全面发展的学。你做事谨慎、一丝不苟，认真负责，你一遍又一遍地修改我们项目的文稿，一遍又一遍地叮嘱我统计好人物关系表，一遍又一遍地督促我完成人物评价。这种认真负责的态度值得我学习。希望你一直能乐观看待事物，时时刻刻都满怀自信，让我们看到一个更开朗的你。希望你将来学业能更上一层楼，品学兼优，考上理想的学校，实现自己的理想。最后别忘了，我们一班一家人永远是朋友！"""
[[comment]]
from = 29
date = 2022-12-06
description = """简直就是别人家的孩子，老师眼中的好学生，绝对的三好学生。钟帅这个词是一个专有名词。非常的勤奋自律，上课认真听讲（？，在体锻的时候会去操场跑步或跳绳，简直就是自律的代言人！有人说学霸就是古板的，那么就大错特错！钟帅善良幽默，经常会组织一些有趣的活动，他很有领导力，有责任感。仙子下凡幸苦了！"""
[[comment]]
from = 14
date = 2022-12-07
description = """钟彦慷，是我们班最为称职的班长。他是我们班中少有的，能让老师安心，同学放心，大家开心的大人物。他威望远超大部分同学，得益于他说到做到和不知疲惫的勤奋。他是我这么多年以来见过的最令人佩服的人，你可以在任意课间看到他坐在课桌学习，也必能在体锻的操场上看到他的身影。如果说他有什么缺点的话，我是没看到，可能有点片面，不过他的确在什么方面都很优秀。如此优秀的人没有孤高，反而是平易近人。他尊重每个同学，尊重个人的独立人格。祝他在今后的日子里能成就他所要成就的事业。"""