name_en = "Kenneth"
nickname = ["威猛先生", "彦慷师傅", "盅盐糠", "钟帅"]
relationship = [
    { by = 11, is = "合作伙伴" },
    { by = 16, is = "手机智慧助手" },
    { by = 18, is = "孙子" },
    { by = 23, is = "男神" },
]
reviews = [
    """每一次批改你的作业都是一种享受，干净整洁、字迹漂亮，还会点缀有各种你的思路和感悟。你总是那么理性和严谨，似乎每次见到你，你都是在不断地刷题。还记得你将《阳光学业评价》击败，纠正了全年级的“琢磨”；还记得你提出合理建议，不接受大量机械性的惩罚抄写作业。看你整日拧起的眉头，我曾以为你是一个只会学习的人，却不想你在运动会上可以健步如飞；看你时刻伏案奋笔的状态，我曾以为你是一个极其珍惜自己时间的人，却不想又见识了你在烈日下挥汗如雨做志愿者的样子。Hey，钟大帅哥，你可真是个宝藏男孩，亦静亦动，内外兼修，很高兴认识你！""",

    """爱卿性行淑均，躬行勤谨。玄武初开，国运势微，会奸杠当道，民不堪其忧。爱卿殚精竭虑，克己复礼，倡行新政，三易其法，力除疲敝。遂世风清肃，大单日兴，而爱卿律己愈严，略无倨傲之姿，实乃大单肱股之臣，万民之福。
惟愿爱卿惜恤青春之光阴，悦享清平之盛世，万勿妄自菲薄，引喻失义。
钦此。""",

    """挺直的脊背，整洁的衣着，齐整的头发，这便是身为班长的钟大帅哥给人的第一印象，刚认识你时，大家以为你是个生人勿近的高冷男神，不敢靠近你与你交谈，但经过了一段时间，经过观察，大家会发现你在被表扬时，也会羞涩地低下头，遇到欢乐的事情时，也会露出憨憨的笑容。刚认识你时，总以为你是个只会学习的人，但你却在运动会上一展风采，让人恍然大悟，原来这是一个德智体美劳全面发展的阳光大男孩儿，很高兴认识你，钟大帅哥！""",

    """自信、勤奋的你是我最优秀的学生之一。你深深爱着我们的班集体，经常主动给老师好提出建议、又主动帮助同学。你能认真地学好每一门功课，在学习上有一种积极进取的可贵精神，这是多么令人钦佩呀！你是个聪明的孩子，我相信你最终将成为胸纳百川，恢宏大度的杰出人才！""",

    """朴实、执着、勤学好问是你的优点，课堂上，总能听到你积极回答问题的声音，看到你微微锁眉的思考面容，因而你的学习成绩位居班级前列，尊敬师长，团结同学，原则性强，使为师不得不喜欢你，你也轻松将本学期最多的优秀提名收入囊中，可谓实至名归。临近毕业，你还担纲领导大家积蓄回忆，真是一个有新的人，真心祝你金榜题名，前程似锦。""",
]
[[comment]]
date = 2022-12-03
description = """彦慷者，智也，壮也。
吾十分佩服其能组织众人，集中力量办大事，此乃吾等不具也。其德高望重，只要有难，其必助，且其不食言。
其爱好学习，爱好运动，练其体肤乐此不疲。其能跑千米而气不喘，可跳绳数百不言累，且其乃可与吾等说笑于其间，真乃神人也。
事件：吾曾与其谈论其梦想，其曰“着眼当下，勿想太远，以误学业”。其有梦想，但吾不知。想必为关乎大事之梦想也。若其成，吾之梦想也许亦能实现。
其不好游戏，好助人。吾之“一战”，其助吾甚多，其曾在“一战”败军之际，意图力挽狂澜，给吾指明道路，组织人手，东山再起，只可惜，吾之计划——以相声之节目夺一位而以“一战”上位中夺位之事未成，惜也。
主动热心，坚强耐心，拿出诚心与决心，用红心坚持铁心与公心，明确辨析大局意识、忧患意识、责任意识，注重学习意识与上进意识，最终育养出管理意识。"""
from = 25
[[comment]]
date = 2022-12-04
description = """身为班级的梁柱，你是同学们心目中的榜样。初中开学以来，你一直表现优秀，成绩颇佳，与人友善，尊敬师长，积极参加各种课外活动，课后与同学积极互动，是同学们的好榜样，能够做到德智体美劳全面发展的学。你做事谨慎、一丝不苟，认真负责，你一遍又一遍地修改我们项目的文稿，一遍又一遍地叮嘱我统计好人物关系表，一遍又一遍地督促我完成人物评价。这种认真负责的态度值得我学习。希望你一直能乐观看待事物，时时刻刻都满怀自信，让我们看到一个更开朗的你。希望你将来学业能更上一层楼，品学兼优，考上理想的学校，实现自己的理想。最后别忘了，我们一班一家人永远是朋友！"""
from = 11
[[comment]]
date = 2022-12-06
description = """简直就是别人家的孩子，老师眼中的好学生，绝对的三好学生。钟帅这个词是一个专有名词。非常的勤奋自律，上课认真听讲（？，在体锻的时候会去操场跑步或跳绳，简直就是自律的代言人！有人说学霸就是古板的，那么就大错特错！钟帅善良幽默，经常会组织一些有趣的活动，他很有领导力，有责任感。仙子下凡幸苦了！"""
from = 29
[[comment]]
date = 2022-12-07
description = """钟彦慷，是我们班最为称职的班长。他是我们班中少有的，能让老师安心，同学放心，大家开心的大人物。他威望远超大部分同学，得益于他说到做到和不知疲惫的勤奋。他是我这么多年以来见过的最令人佩服的人，你可以在任意课间看到他坐在课桌学习，也必能在体锻的操场上看到他的身影。如果说他有什么缺点的话，我是没看到，可能有点片面，不过他的确在什么方面都很优秀。如此优秀的人没有孤高，反而是平易近人。他尊重每个同学，尊重个人的独立人格。祝他在今后的日子里能成就他所要成就的事业。"""
from = 14
[anecdote]
embarrassment = "九年级上学期音乐课上被邀请才艺表演原先准备超级充分的《Prelude Op. 23 No. 5 in G Minor - Sergei Rachmaninoff》。然而在诸多因素影响下（比如说手如冰块冷、各式各样的起哄烘托出来的紧张氛围、钢琴质量也不太妙），我成功地彻底弹崩了！强弱失去对比，错音三小节一个，弹着弹着不知道弹到哪里去了……话说这样烂那摆烂就算了，可我万没想到的是全场一片静穆，老师站在后面为我翻页，结果弹完之后又是一片轰动，琴谱被传阅，然后收到奇奇妙妙的评语（such as 弹的曲目很高深？练了〔至少三年〕罢？）。好不容易下课后，内心只留下了满满的尴尬和对起哄文化的无奈。"
interests = "弹弹钢琴 & 到开源社区做志愿"
want = "用实干激扬青春，实现人生价值"
[[article]]
content = "钟大帅哥维新变法"
date = 2021-03-13
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247487146&idx=1&sn=a7f5bcb0ef0625b41d982a7fb759bff8"
[[article]]
content = "值日班长钟彦慷的述职报告"
date = 2021-12-01
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247490991&idx=1&sn=3b2c778d88d1e4860ef3958e72367090"
[[article]]
content = "我以妙笔绘青春——第一届手绘杂志原创大赛"
date = 2021-03-04
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247487140&idx=1&sn=defc6000c7392dfb65d5a4afd7285bf5"
[[article]]
content = "大单朝钟帅三变法 平杠王皇权稳如山"
date = 2021-07-25
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247490567&idx=1&sn=5fd134138df2210d7c35a0dae71be4d8"
[[article]]
content = "千日圆满 感动初三"
date = 2023-04-29
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247491100&idx=1&sn=3e48217a9493b07c1218c250cc000cfb"
