name_en = "Miu Miu"
nickname = [
    "小钰",
    "小鱼",
]
introduction = """从幼儿园到初二，我在英校度过了十多年，现在一回想这几年真的过的好快，感觉一眨眼就初三了。
初中是我记忆最深的时候，从踏进7B1到走出8B1，我真的很喜欢我们班。喜欢上课时我们班人整的活（特别是改芳姐凸透镜课件那次真的超好笑），喜欢我们班的团建，喜欢我们班同学们之间的友情（虽然我们班没有情侣但是那些男生真的很好磕诶doge）。每一次中午下课我们班的人总是第一个冲到饭堂当干饭人，食堂第一批到的就是我们班的人，还有一次我们都站在门口“迎宾”，来一个人就说一句欢迎光临。晚饭的时候要是看到火山和佩奇就回来一句“哟，稀客呀！”吃完饭就和菲姐波波还有真菌一起回宿舍，八下那段时间我们沉迷于海龟汤，每一次回宿舍都在说。回宿舍之路要经过幼儿园，幼儿园养了几只鸭子。有一次波波去“欺负”那些鸭子结果被老师抓个正着，我们走的时候都笑傻了。还有一次我和菲姐中午去吃螺蛳粉，一点多才回来，老师居然没有说我们直接放我们走了，她真的好温柔，我哭死。
到了八下，每个星期三下午都要去体锻，绕操场跑圈。这是我们每一个人的噩梦，跑完下来整个人都没了半条命，我们都是互相搀扶着走回去的。
晚修的时候就更好玩了，虽然不能讲话，但是我们各种手段层出不穷。我们班晚休就是一个分享会，传纸条的，传零食的，甚至传球的也有。七年级的时候怪哥和主持晚修的时候在座位上打羽毛球，我刚刚好坐在旁边将这一幕尽收眼底，第二天，他们就被爱丽发现了。就在如此环境下我们班还有学霸在认真学习，像钟帅啊，森妈啊这种，对于我来说可望而不可求啊，毕竟我属躺平类人士的。
有时间的话我还会去串门，来到现在的会议室里面“蹭课”。每一次一来都会收到好多私信。上一次回校，匡匡还专门给我带了奶茶，真的很高兴遇到了你们！
现在回忆起来有好多想说的，奖状墙，班牌，板报，还有同学们，我们亲爱的爱丽，级长和其它老师。祝愿我们都会越来越好！不要忘了林小钰哟。"""