introduction = """从幼儿园到初二，我在英校度过了十多年，现在一回想这几年真的过的好快，感觉一眨眼就初三了。
初中是我记忆最深的时候，从踏进7B1到走出8B1，我真的很喜欢我们班。喜欢上课时我们班人整的活（特别是改芳姐凸透镜课件那次真的超好笑），喜欢我们班的团建，喜欢我们班同学们之间的友情（虽然我们班没有情侣但是那些男生真的很好磕诶doge）。每一次中午下课我们班的人总是第一个冲到饭堂当干饭人，食堂第一批到的就是我们班的人，还有一次我们都站在门口“迎宾”，来一个人就说一句欢迎光临。晚饭的时候要是看到火山和佩奇就回来一句“哟，稀客呀！”吃完饭就和菲姐波波还有真菌一起回宿舍，八下那段时间我们沉迷于海龟汤，每一次回宿舍都在说。回宿舍之路要经过幼儿园，幼儿园养了几只鸭子。有一次波波去“欺负”那些鸭子结果被老师抓个正着，我们走的时候都笑傻了。还有一次我和菲姐中午去吃螺蛳粉，一点多才回来，老师居然没有说我们直接放我们走了，她真的好温柔，我哭死。
到了八下，每个星期三下午都要去体锻，绕操场跑圈。这是我们每一个人的噩梦，跑完下来整个人都没了半条命，我们都是互相搀扶着走回去的。
晚修的时候就更好玩了，虽然不能讲话，但是我们各种手段层出不穷。我们班晚休就是一个分享会，传纸条的，传零食的，甚至传球的也有。七年级的时候怪哥和主持晚修的时候在座位上打羽毛球，我刚刚好坐在旁边将这一幕尽收眼底，第二天，他们就被爱丽发现了。就在如此环境下我们班还有学霸在认真学习，像钟帅啊，森妈啊这种，对于我来说可望而不可求啊，毕竟我属躺平类人士的。
有时间的话我还会去串门，来到现在的会议室里面“蹭课”。每一次一来都会收到好多私信。上一次回校，匡匡还专门给我带了奶茶，真的很高兴遇到了你们！
现在回忆起来有好多想说的，奖状墙，班牌，板报，还有同学们，我们亲爱的爱丽，级长和其它老师。祝愿我们都会越来越好！不要忘了林小钰哟。"""
name_en = "Miu Miu"
nickname = ["小钰", "小鱼"]
relationship = [{ by = 21, is = "女儿" }]
reviews = [
    """哈！我的野生林小钰！你的声音很好听，总是绵绵的，每次与你四目相对，你的目光又总是柔柔的。只要看着你，就理解了什么是岁月静好。难忘的是你强迫症发作，将为师手残留下的满壁疮痍都撕除干净；难忘的是你在开放日和元旦汇演排练时，随音乐舞动所张扬的青春的力量；难忘的是你在每节我的语文课前课后，都会围着讲台和我谈天说地；难忘的更有，你在那次课前演讲时，一一评点全班每个人的专属绰号，那么欢乐，那么暖心……你的成绩又给了我很大惊喜，本以为在花费超大量时间排练后，你的成绩会正常地下滑，真的没想到，你可以带着如此繁重的任务冲到年级前三。这个学期，我们一起度过了一段很难忘的时光，我很珍惜这个学期里的每一天，下个学期也要给我快乐和惊喜哦！很高兴认识你！""",

    """你文静美好，待人温和，是大家眼中的小乖乖；你字迹娟秀大方，批阅你的作业是一种享受；你热心善良，人缘又很好，看到你总会觉得今天很开心；你有很高的舞蹈天赋，生日时你的照片让大家都惊叹于你的才华和美貌……初中生活的三分之一已经过去了，很开心和你一起度过，接下来我们还要继续努力哈。""",

    """野生林小钰，你是班里各路妖魔鬼怪牛鬼蛇神中的一股清流，几次班级大考，各方神圣多半败下阵来时，你仍然屹立不倒，着实厉害。
你还有点强迫症，还记得在七年级时，为师为全班制作了纪律德育分数表格，要贴上墙壁，但因经验不足，手艺不精，使得可是最后满目疮痍，一大块一大块的边角料，像狗皮膏药一般死粘在白墙上。当全班同学都要放弃之际，你毅然舍弃了自己，亲自出马，用手抠撕下了全部“建筑垃圾”，把这项费时又费力，工程量巨大又艰难的工程完成了，你实在有着舍小家为大家的无私奉献精神，吾辈楷模。""",

    """在你合格地完成了本期的学业时，老师也有一番心里话要说给你听，沉默寡言是同别人交流的一堵墙，这使大家不易了解你优秀的一面。多想常常看到你开心的笑容，多想常常听到你爽朗的笑声。来呀，做个乐观开朗的孩子，生活一定会更添姿彩！""",
]
[anecdote]
embarrassment = ""
interests = "跳舞听kpop看小说"
want = "想多去几个国家玩 想和之前同学一起聚"
[[article]]
content = "我以妙笔绘青春——第一届手绘杂志原创大赛"
date = 2021-03-04
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247487140&idx=1&sn=defc6000c7392dfb65d5a4afd7285bf5"
[[article]]
content = "林小钰生日快乐！豆蔻重填岁，明朝更登楼"
date = 2021-05-21
link = "https://mp.weixin.qq.com/s?__biz=MzkyNjIxNDI0NQ==&mid=2247489554&idx=1&sn=e22477c5ee4be4e355c7f53bb4a721ad"
