nickname = [
    "ccy",
    "yy",
    "吹杨",
    "yy姐姐",
]
relationship = [
    { with = 25, is = "好朋友" },
    { with = 31, is = "好朋友" },
    { with = 6, is = "跑步训练师" },
]
[[comment]]
from = 25
date = 2022-12-03
description = """陈琛杨，一名未成年男性，身型健壮，体育强悍，跃之高而远。其貌如玉树临风。其善于数学，数学十分好，可想出许多解题妙策。其爱好游戏与运动，其戏于《泰拉瑞亚》《使命召唤》《世界征服者4》等，皆有一定成就于其中。其腿之强韧，最高档可骑车上大斜坡。
事件：其与泓睿一样，可无手骑车。其曾与吾骑车，骑于路上，其松开车把，脱鞋，在车上边骑边检视，毕之，穿之如在平地，其间车如机魂大悦，平稳过弯。
吾不知其梦想，但其绘画可谓厉害。其画一草一植，勾出轮廓，定其区域，待到画成时，其画如以相机拍之。"""
[[comment]]
from = 1
date = 2022-12-06
description = """ccy是性格很外向，很容易聊得来的人。所以，他的一些小秘密也总会藏不住（比如：喜欢***对吧）。我印象最深的是我和他还有罗阿姨一起上课，下课后就直奔地铁站去找另外两个人玩，那一次我体会了为什么不能跟男生出来逛街（？）"""
[[comment]]
from = 28
date = 2022-12-07
description = """陈琛杨作为体育课king，身材好，手也好看。其性格开朗，讨人喜爱（虽然有点小贱）作为张婷御用工作人，他工作尽职尽责，毫无抱怨，甚至会因为别人抢了他的工作而暗自生气。为人正直，从不撒谎，从不抄作业，就算早上到了学校，发现自己还剩很多作业，他依旧不会抄。因为做过他的同桌，就知道他人真的很好，会时不时关心你，总是能让我有一种很温暖的感觉（真的）。她做事十分负责，作为“二战”的领导人，他亲手抄录剧本，好像写了好几张a4纸吧，字迹还特别工整。就是这样的一位yy，为我贫乏而枯燥的初三，创造出了一点彩色。我永远不会忘记“yy绣花”以及“九千少女心中梦，风流倜傥caocao杨。”"""