on: [push, pull_request]

name: CI

jobs:
  rust-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions-rs/toolchain@master
        with:
            toolchain: stable
            components: rustfmt
            override: true
      - uses: mbrobbel/rustfmt-check@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            abbr: Windows
            exec_path: ./target/release/graduate.exe
          - os: ubuntu-latest
            abbr: Linux(Ubuntu)
            exec_path: ./target/release/graduate
          - os: macos-latest
            abbr: Mac
            exec_path: ./target/release/graduate
    runs-on: ${{ matrix.os }}
    name: Build Executable on ${{ matrix.abbr }}
    steps:
      - uses: actions/checkout@main
      - uses: actions-rs/toolchain@master
        with:
          toolchain: stable
      - uses: actions-rs/cargo@master
        with:
          command: build
          args: --release
      - uses: actions/upload-artifact@main
        if: matrix.os == 'ubuntu-latest'
        with:
          name: config
          path:
            ./src/config.json
      - uses: SebRollen/toml-action@main
        id: read_toml
        with:
          file: 'Cargo.toml'
          field: 'package.version'
      - uses: actions/upload-artifact@main
        with:
          name: graduate-v${{ steps.read_toml.outputs.value }}-${{ matrix.abbr }}
          path:
            ${{ matrix.exec_path }}
