name: CI
on: [push, pull_request]

jobs:
  Format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions-rs/toolchain@master
        with:
            toolchain: stable
            components: rustfmt
            override: true
      - uses: mbrobbel/rustfmt-check@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  build_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: hecrj/setup-rust-action@v1
    - name: Install cargo-deb
      run: cargo install cargo-deb
    - uses: actions/checkout@master
    - name: Install dependencies
      run: |
        export DEBIAN_FRONTED=noninteractive
        sudo apt-get -qq update
        sudo apt-get install -y libxkbcommon-dev libasound2-dev
    - name: Build binary
      run: cargo build --verbose --release
    - name: Archive binary (Uncompressed)
      uses: actions/upload-artifact@v1
      with:
        name: graduate-x86_64-unknown-linux-gnu-uncompressed
        path: target/release/graduate
    - name: Compress binaries
      uses: svenstaro/upx-action@master
      with:
        file: target/release/graduate
        args: --best --lzma
    - name: Archive binary
      uses: actions/upload-artifact@v1
      with:
        name: graduate-x86_64-unknown-linux-gnu
        path: target/release/graduate
    - name: Pack graduate .deb package
      run: cargo deb --no-build
    - name: Rename graduate .deb package
      run: mv target/debian/*.deb target/debian/graduate-x86_64-debian-linux-gnu.deb
    - name: Archive graduate .deb package
      uses: actions/upload-artifact@v1
      with:
        name: graduate-x86_64-debian-linux-gnu
        path: target/debian/graduate-x86_64-debian-linux-gnu.deb
    - name: Install cross
      run: |
        cargo clean
        cargo install cross
    - name: Build binary for Raspberry Pi 3/4 (64 bits)
      run: cross build --verbose --release --target aarch64-unknown-linux-gnu
    - name: Archive binary
      uses: actions/upload-artifact@v1
      with:
        name: graduate-aarch64-unknown-linux-gnu-uncompressed
        path: target/aarch64-unknown-linux-gnu/release/graduate

  build_windows:
    runs-on: windows-latest
    steps:
    - uses: hecrj/setup-rust-action@v1
    - uses: actions/checkout@master
    - name: Enable static CRT linkage
      run: |
        mkdir .cargo
        echo '[target.x86_64-pc-windows-msvc]' >> .cargo/config
        echo 'rustflags = ["-Ctarget-feature=+crt-static"]' >> .cargo/config
    - name: Run the application without starting the shell
      run: |
        sed -i '1 i\#![windows_subsystem = \"windows\"]' src/main.rs
    - name: Build binary
      run: cargo build --verbose --release
    - name: Archive binary (Uncompressed)
      uses: actions/upload-artifact@v1
      with:
        name: graduate-x86_64-pc-windows-uncompressed
        path: target/release/graduate.exe
    - name: Compress binaries
      uses: svenstaro/upx-action@master
      with:
        file: target/release/graduate.exe
        args: --best --lzma
    - name: Archive binary
      uses: actions/upload-artifact@v1
      with:
        name: graduate-x86_64-pc-windows
        path: target/release/graduate.exe

  build_macos:
    runs-on: macOS-latest
    steps:
    - uses: hecrj/setup-rust-action@v1
    - uses: actions/checkout@master
    - name: Build binary
      run: cargo build --verbose --release
    - name: Open binary via double-click
      run: chmod +x target/release/graduate
    - name: Archive binary (Uncompressed)
      uses: actions/upload-artifact@v1
      with:
        name: graduate-x86_64-apple-darwin-uncompressed
        path: target/release/graduate
    - name: Compress binaries
      uses: svenstaro/upx-action@master
      with:
        file: target/release/graduate
        args: --best --lzma
    - name: Archive binary
      uses: actions/upload-artifact@v1
      with:
        name: graduate-x86_64-apple-darwin
        path: target/release/graduate
