name: CI
on: [push, pull_request]

jobs:
  Format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: dtolnay/rust-toolchain@stable
      - uses: mbrobbel/rustfmt-check@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  build_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: dtolnay/rust-toolchain@stable
    - name: Install cargo-deb
      run: cargo install cargo-deb
    - uses: actions/checkout@master
    - name: Install dependencies
      run: |
        export DEBIAN_FRONTED=noninteractive
        sudo apt-get -qq update
        sudo apt-get install -y libxkbcommon-dev libasound2-dev
    - name: Build binary
      run: cargo build --verbose --release
    - name: Archive binary (Uncompressed)
      uses: actions/upload-artifact@v1
      with:
        name: graduate-x86_64-unknown-linux-gnu-uncompressed
        path: target/release/graduate
    - name: Compress binaries
      shell: bash
      run: |
        wget https://github.com/upx/upx/releases/download/v4.0.1/upx-4.0.1-amd64_linux.tar.xz -O upx.tar.xz
        tar xvJf upx.tar.xz
        upx target/release/graduate --best --lzma
    - name: Archive binary
      uses: actions/upload-artifact@v1
      with:
        name: graduate-x86_64-unknown-linux-gnu
        path: target/release/graduate
    - name: Pack graduate .deb package
      run: cargo deb --no-build --no-strip
    - name: Rename graduate .deb package
      run: mv target/debian/*.deb target/debian/graduate-x86_64-debian-linux-gnu.deb
    - name: Archive graduate .deb package
      uses: actions/upload-artifact@v1
      with:
        name: graduate-x86_64-debian-linux-gnu
        path: target/debian/graduate-x86_64-debian-linux-gnu.deb

  build_windows:
    runs-on: windows-latest
    steps:
    - uses: dtolnay/rust-toolchain@stable
    - uses: actions/checkout@master
    - name: Enable static CRT linkage
      run: |
        mkdir .cargo
        echo '[target.x86_64-pc-windows-msvc]' >> .cargo/config
        echo 'rustflags = ["-Ctarget-feature=+crt-static"]' >> .cargo/config
    - name: Run the application without starting the shell
      run: |
        sed -i '1 i\#![windows_subsystem = \"windows\"]' src/main.rs
    - name: Build binary
      run: cargo build --verbose --release
    - name: Archive binary (Uncompressed)
      uses: actions/upload-artifact@v1
      with:
        name: graduate-x86_64-pc-windows-uncompressed
        path: target/release/graduate.exe
    - name: Compress binaries
      shell: pwsh
      run: |
        Invoke-WebRequest -Uri "https://github.com/upx/upx/releases/download/v4.0.1/upx-4.0.1-win64.zip" -OutFile "upx.zip"
        Expand-Archive -Path upx.zip -DestinationPath upx.exe
        .\upx.exe target\release\graduate.exe --best --lzma
    - name: Archive binary
      uses: actions/upload-artifact@v1
      with:
        name: graduate-x86_64-pc-windows
        path: target/release/graduate.exe

  build_macos:
    runs-on: macOS-latest
    steps:
    - uses: dtolnay/rust-toolchain@stable
    - uses: actions/checkout@master
    - name: Build binary
      run: cargo build --verbose --release
    - name: Open binary via double-click
      run: chmod +x target/release/graduate
    - name: Archive binary (Uncompressed)
      uses: actions/upload-artifact@v1
      with:
        name: graduate-x86_64-apple-darwin-uncompressed
        path: target/release/graduate
    - name: Compress binaries
      shell: bash
      run: |
        brew update
        brew install upx
        upx target/release/graduate --best --lzma
    - name: Archive binary
      uses: actions/upload-artifact@v1
      with:
        name: graduate-x86_64-apple-darwin
        path: target/release/graduate
