name: Generate debug execuable
on:
  workflow_dispatch:

jobs:
  build_windows:
    runs-on: windows-latest
    steps:
    - uses: dtolnay/rust-toolchain@stable
    - uses: actions/checkout@master
    - name: Build binary
      run: cargo build --verbose --release
    - name: Archive binary (Uncompressed)
      uses: actions/upload-artifact@v3
      with:
        name: graduate-x64-Windows-debug
        path: target/release/graduate.exe
